### ISSUE TITLE
Looking for Contributors

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#1]
If anyone is interested (@natiki, @maliming, @ahmed007boss, @rstraszewski, @ktngoykalolo) I started a BlazorBoilerplate repo that I am hoping to get some contributors to help build. It is very lean now but it has to start somewhere.  

http://blazorboilerplate.com/
https://github.com/enkodellc/blazorboilerplate

**Comment by 274188A** [comment]
Maybe team up with the people over at [ASP.NET Boilerplate](url)?  They have a solid framework for the server-side already - maybe it could be adapted to use Blazor. 

They are busy building the [next gen](https://abp.io) of their framework. 

Worth a look...

**Comment by enkodellc** [comment]
@274188A  I definitely would reach out but Asp.net Boilerplate has been around for years and in my opinion their team limits their project to push people into their paid product. This can be seen by lack of features for their a password forget feature as an example. They have a valid PR for it that works but have not implemented it. I also am not a fan of their external "abp" components. I understand those are helpful in most instances and provide great functionality but in my opinion obfuscates code customization / functionality. I guess I like to see and search the code and having those components require more research.  Also I have not seen a clear path to Blazor and I am interested in it now.

**Comment by natiki** [comment]
@enkodellc Happy to help out where I can. I am pretty time poor atm but will contribute. I would however only like to do this as part of the "[next gen](https://abp.io/)" framework.

We are heavy users of the existing ABP Boilerplate framework in both WebForms and MVC. However we have now started internally converting everything to .NET Core and ultimately .NET 5. As Blazor is to be  a first class  citizen of .NET 5 (i.e. .NET Core 5) doing it in their next gen framework has to be the place to start. (IMHO I don't see the ABP team maintaining the v1 of the framework for longer than 24 months after the next gen becomes available)

**Comment by enkodellc** [comment]
@natiki thanks for the feedback. I definitely want it to be as much next gen as possible but still functional. 

> The next release, now called .NET 5, will be a single platform that can replace both .NET Core 3 and .NET Framework 4.8. It will ship in November 2020, with the first preview available in the first half of 2020, Microsoft says

With that said I would like to target .Net Core 3 and update next year when .Net 5 is previewed.
If you have any resources or examples you can point me to I would greatly appreciate it. I understand people have time constraints and I do to but I am building this framework to help me with a client project so I will moving it along as much as I can in parallel with that project. Thanks!

**Comment by natiki** [comment]
> With that said I would like to target .Net Core 3 and update next year when .Net 5 is previewed.
Agreed. But it "needs" to be done using https://abp.io/ ie "next gen" and not the current https://aspnetboilerplate.com/.

I have read the roadmap.... Is the intention here to produce a Blazor equivalent of what ASP.NET and Module ZERO offers out of the box? 

Have a look at:

- https://github.com/aspnetboilerplate/aspnetboilerplate/issues/3323
- https://github.com/abpframework/abp/issues/394

because I suggest we at least collaborate with the ABP guys to get a direction to build this

**Comment by enkodellc** [comment]
Yes and No. I would like to have most of the features Module Zero offers but I the goal would be to have more functionality and examples that are real world without having a company oversee and control the repository. I want to see a community put it together and share the knowledge instead of have to pay for the enterprise version.  I will continue to develop and hopefully some others will want to contribute in this manner. I did a lot of work with the MEAN.IO project and that was fun and rewarding but Angular was a big learning curve whereas Blazor seems faster to code and maintain for me.

**Comment by natiki** [comment]
Fair enough. I am still happy to contribute on this basis. I don't know much about Blazor atm but need to learn it.

**Comment by enkodellc** [comment]
@natiki  Thanks. Blazor is super simple.. if you know C#. I personally feel it is much easier to build and maintain than Angular.  My weakness is in the "Best Practices" arena so that is where I will need the most feedback from my code. I have several examples not just aspnetboilerplate to review and implement. Let me know if there is a part of the app you are willing to take ownership of... Identity / server framework / or something like that.  I just implemented Serilog and working through that setup. Next I think I will do services for Email... make a path toward password reset functionality. Which is one thing aspnetboilerplate / open-source version did not implement.

**Comment by mlscloud** [comment]
Still I would like to contribute and take ownership for server framework.

**Comment by enkodellc** [comment]
@mlscloud I created a gitter, PM me on there and let's discuss the best approach to collaborate and what exactly you want  to take ownership of.  https://gitter.im/blazorboilerplate/community
