### ISSUE TITLE
MudGrid

### ISSUE THREAD

**Issue by wint100** [enkodellc/blazorboilerplate#1026]
Have you looked at the MudDataGrid instead of the Mudgrid. Just curious as it provided filtering without all the code required.

I seem to have issues with the filtering solution in the boilerplate, when tables are empty, so moving to the MudDatagrid seems an easier to manage solution.

Many Thanks for all your hard work.

**Comment by enkodellc** [comment]
Sorry, have not looked at MudDataGrid, it was not released when we built most of BlazorBoilerplate.   

@GioviQ  have you tested it out yet?

**Comment by GioviQ** [comment]
MudDataGrid (Experimental) is not a replacement of MudGrid and for what I see in the docs, it seems a replacemente of MudTable when you do not need server side filtering, pagination, etc.

At the moment for what I need at work, MudTable is the best choice, because I often work with huge amount of server side data.

**Comment by wint100** [comment]
Ok good info, thanks.

I looked at the datagrid for inbuilt filtering and CRUD operations. I was trying to avoid the additional filter models and handling. Although I ran into a few issues with the mud datagrid, so moved to the syncfusion datagrid. That seems to work better but it's not perfect.

**Comment by wint100** [comment]
I've tried a few different grids and tables now, from Syncfusion, Mud and Telerik all seem to crash in some way when adding a new Todo item. The most helpful exception comes from Telerik, ( Error: System.MissingMethodException: Cannot dynamically create an instance of type 'Breeze.Sharp.EntityAspect'. Reason: No parameterless constructor defined.)

Adding with Mudtable complains about detected cycle of greater than the max of 64. 

So maybe breezesharp is the culprit for all grids. I've updated to the latest fork that you have released.

**Comment by GioviQ** [comment]
You should consider that this repository is not tested with third party (paid) components, but with MudBlazor components, so other components may have very different requirements.

Also BreeseSharp is not mandatory, you can create your own DTO.

**Comment by wint100** [comment]
Yes it's a shame the mud components didn't have the required features. I'll certainly take another look though. 

This template you have created is far superior to anything anything else I've come across, so I really do want to stick with it.

**Comment by wint100** [comment]
Ditching Breezesharp was the answer. Even MudDataGrid had issues when it came to editing. Now I've used the same method as the TenentInfo, by creating my Dto manually and creating another controller and manager (Server Project) to handle the CRUD operations in my Grid. Synfusion, Muddatagrid and Telerik grids are now happy.

I can still use the ApiClient on my client side, which is used in the razor pages.

**ApiClient Code**
![image](https://user-images.githubusercontent.com/22261052/227526537-a40bacc0-f20f-42dd-ad9c-44d5ac0c5db9.png)

**Razor Page**
![image](https://user-images.githubusercontent.com/22261052/227526773-eebb8643-7901-42de-a3c2-2bbd1ac6e197.png)

**MappingController**
![image](https://user-images.githubusercontent.com/22261052/227526891-7b1465a8-b0fa-48b3-8c21-db2c10bd33ab.png)

**MappingManager**
![image](https://user-images.githubusercontent.com/22261052/227526977-7332d3a6-ee51-4628-a715-b34100c6d8ff.png)
