### ISSUE TITLE
Datagrids

### ISSUE THREAD

**Issue by wint100** [enkodellc/blazorboilerplate#1027]
I've tried a few different datagrids (MudGrid, Syncfusion) and get errors trying to edit and delete with the ToDo table.

The latest error I get is about the Key missing on the dto [CreateEntity failure with KeyProperties not defined]. I noticed the Entity generator doesn't create a Key for the Id in the dto.Db.ToDo class.

Should it do? I'm really struggling to find out why none of the datagrids work for editing, they all crash the blazor app in some way.

I've removed the IAuditable from the Todo Model, which seemed to help the Syncfusion grid a little, but it still throws the above error when trying to edit items.

**Comment by enkodellc** [comment]
If you get key issues or metadata issues after making EF model changes require you to turn off VS and delete your bin/ obj folder as Visual Studio is caching your models. 

My team uses MudTable almost exclusively, I really don't have the time to test others out right now to give other examples. I suggest you reach out on this channel for other suggestions: https://app.gitter.im/#/room/#aspnet_Blazor:gitter.im

**Comment by wint100** [comment]
I've progressed slightly. I'd used a guid as the table key instead of a bigint and this could have caused issues.

MudDataGrid is experimental and I had a couple of issue. Syncfusion grid seems to be more stable.

I'll do more testing and report back on this.

**Comment by enkodellc** [comment]
any update. We have been using MudTable mostly. Either way this is technically out of scope with the BB core functionality.  If you have insight to share for others who read these issues then please post. Thanks
