### ISSUE TITLE
Hot Reload not working

### ISSUE THREAD

**Issue by Trollator** [enkodellc/blazorboilerplate#1033]
I am working on a project with several components, where the hot reload function does not work. After the hot reload I get various error messages like 
"Your debugged process is corrupted, it is recommended to restart it".
or 
"Error in applying the processing steps to the executed application. This error was not expected."

And the page is not updated.

**Comment by enkodellc** [comment]
It has not been working for a long time. I haven't had the time to determine the issue.

**Comment by enkodellc** [comment]
@Trollator any headway?

**Comment by Trollator** [comment]
Nothing new.

**Comment by enkodellc** [comment]
Closing , dup of #264
