### ISSUE TITLE
when i open i got about:blank and i wait and visual studio show message

### ISSUE THREAD

**Issue by wisamidris7** [enkodellc/blazorboilerplate#1040]

**Comment by wisamidris7** [comment]
I Clone It Yestraday

**Comment by wisamidris7** [comment]
i runned the client and it show about:blank

**Comment by IdrisQashan** [comment]
Me to i have this problem

**Comment by enkodellc** [comment]
What branch are you using? Use the Maui branch if you are not already.

**Comment by IdrisQashan** [comment]
The problem was from toentity in seeder in identiy server you should fix it

**Comment by enkodellc** [comment]
@IdrisQashan  can you submit a PR for this?

**Comment by wisamidris7** [comment]
He Mean in seeder in automapper when mapping i got this problem and i think you have to fix it cause app wont open like this here the problem
![Screenshot 2023-05-27 041836](https://github.com/enkodellc/blazorboilerplate/assets/104096256/cd96ef89-031e-4b72-bfd5-588f468b63e0)
![Screenshot 2023-05-27 041832](https://github.com/enkodellc/blazorboilerplate/assets/104096256/b99abbb0-821a-4c00-b8cc-33d64d7226ab)

**Comment by wisamidris7** [comment]
ToEntity It's probelm  or i think there something i can install to make ToEntity work are there a soultion

and also when i maked ToEnitity In My Own App From IdentityServer4 I got also this and i just used mapster and mapster configuration for making something rather than ToEntity Cause ToENtity Used Automapper Inside

I can't use automapper 12 cause the identityserver4 maked a error for automapper and i want to use automapper 12 but i used mapster for this

**Comment by GioviQ** [comment]
@wisamidris7 you still are not using Maui branch to solve this

**Comment by wisamidris7** [comment]
It Work Without ToEntity Try It With You Self

**Comment by enkodellc** [comment]
Just updated master branch. Take a look at that if you like. Is is published so I know it is working on production IIS as well as local.
