### ISSUE TITLE
Dynamic components stopped working

### ISSUE THREAD

**Issue by AlexanderZender** [enkodellc/blazorboilerplate#1044]
Hello,

in our Blazor Boilerplate based application, the components that are based on the DynamicComponentContainer stopped working overnight.
I also downloaded the latest release of Blazorboilerplate to ensure it isn't only our application:
![image](https://github.com/enkodellc/blazorboilerplate/assets/79153884/288aba2f-9559-499b-b10d-10c14f2cea51)

As you can see, the nav menu, footer and toprightmenu is not rendered.
When inspecting the dev tool in edge, the component name appears with some id(?) 
![image](https://github.com/enkodellc/blazorboilerplate/assets/79153884/24c3b6a1-db05-4ae5-b19d-36b2a0229b3f)

This issue started this week with 2 different laptops (mac and windows) and different browsers.
Do you have any ideas what might have caused this?

**Comment by enkodellc** [comment]
Oh yes, this error happened when we updated Visual Studio version 16.4 I believe. Either downgrade you VS version or upgrade to 
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.7.0 Preview 1.0

**Comment by enkodellc** [comment]
FYI: https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.6.3

_A regression was introduced into the razor compiler that broke certain tag helpers with explicit partial classes. Until this bug is fixed customers can work around by pinning back to the 7.0.203 SDK._
