### ISSUE TITLE
Blazor Developer's looking for work

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#1046]
If you are interested in a developer job using Blazor and the .net core architecture. Comment on this issue so others can find devs.

**Comment by enkodellc** [comment]
> Interested

@emi-ekun  contact me via: keith@blazorboilerplate.com

**Comment by Mahdi7s** [comment]
Interested 😍

**Comment by enkodellc** [comment]
@Mahdi7s pm [keith@blazorboilerplate.com](mailto:keith@blazorboilerplate.com)  I just talked with emi-ekun but always looking to connect with other devs.

**Comment by bingoabs** [comment]
Interested, I will send you an email.

**Comment by asimp51** [comment]
interested. CV is sent.

**Comment by freeborn5** [comment]
Sign me Up!

**Comment by codemedic79** [comment]
Interested

**Comment by enkodellc** [comment]
> Interested

@codemedic79  we just filled the role. Thanks.

**Comment by h-pannu** [comment]
interested
