### ISSUE TITLE
Build doesn't work on MacOS or Linux

### ISSUE THREAD

**Issue by derigel23** [enkodellc/blazorboilerplate#1072]
For example, this script is not x-platform.
https://github.com/enkodellc/blazorboilerplate/blame/ebe90a1042d706b1fd804368a97472e653c2fbac/src/Shared/Modules/BlazorBoilerplate.Theme.Material/BlazorBoilerplate.Theme.Material.csproj#L24
There is no `del` command on Linux.

**Comment by enkodellc** [comment]
Thank, those files are deprecated so I just removed them from the master / repo.
