### ISSUE TITLE
unable to connect to web server blazorboilerplate.client

### ISSUE THREAD

**Issue by madhusudhan-v** [enkodellc/blazorboilerplate#1084]
<img width="597" alt="image" src="https://github.com/enkodellc/blazorboilerplate/assets/3640748/9ae7cd09-99d2-4842-91fe-3cde75e57bbc">

**Comment by enkodellc** [comment]
what branch are you using?

**Comment by GioviQ** [comment]
The  WASM Client project cannot be launched by itself, because it is hosted in server project, so run Server project.
