### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by AlexanderZender** [enkodellc/blazorboilerplate#1093]
Hey,

is there any plan for the next official release of the repo?

Thank you

**Comment by AlexanderZender** [comment]
@enkodellc That sounds fantastic, does that mean the maui branch will be included in the new release or will they stay as two separate "versions"?

**Comment by moemura** [comment]
"remove_IS4_6" branch already on .Net 8

**Comment by enkodellc** [comment]
FYI I am working on a new release / publish. with .net 8. Should be done in the next week.  @AlexanderZender  they will still 2 different branches.

**Comment by Alexander-Zender** [comment]
@enkodellc Hey sounds great! Cant wait for the next release.

**Comment by enkodellc** [comment]
7.0.17 - Removed IS4 and Toolbelt, upgraded to .net 7.0.17. I will create this release and in the coming weeks I will be doing a .net 8 release with a bit more more work. Planning on putting some more production items we found out during our production release changes.
