### ISSUE TITLE
Cannot compile blazorboilerplate - many errors

### ISSUE THREAD

**Issue by zackmorgs** [enkodellc/blazorboilerplate#114]
First off, thanks for this awesome project - I really will be needing it for mine and hope someone can help me fix this.

**Problem:** Cannot compile solution

- [.net core 3.1](https://dotnet.microsoft.com/download/dotnet-core/3.1) (x86, x64 installed)
- Visual Studio Community 2019 Preview - Version 16.5.0 Preview 1.0
- cloned

[Screenshot](https://i.imgur.com/QZedSZ4.png)

**Comment by enkodellc** [comment]
@zackmorgs Do you have any flags from your nuget dependencies? Check the Very last error in the list, Sometime when VS throws a bunch of errors it is only one and it is the very last one. Not sure why VS does that but it does it to me. In any case I have not seen this issue and have only one other person submit an issue like this and I never heard back from him on how he solved it if any. https://github.com/enkodellc/blazorboilerplate/issues/104

Also try starting another Blazor Solution from Microsoft's Blazor templates to see if that runs fine.

**Comment by zackmorgs** [comment]
Nada my friend, thanks for the speedy reply.

[Screenshot](https://i.imgur.com/14eidhj.png)

**Comment by enkodellc** [comment]
Zach Try posting to the aspnet/Blazor forum on Gitter, They are usually very fast and have a great knowledge base. Like I said I have only had a couple people of the 400+ BB users have this issue.

https://gitter.im/aspnet/Blazor

**Comment by richbryant** [comment]
Yeah, this looks like something's very wrong right from the beginning.  Push a repo somewhere.  That's going to be the only way to debug this many errors.

**Comment by enkodellc** [comment]
@richbryant  He mentioned he cloned the repo. So assuming @zackmorgs cloned it properly and he has all the dependencies it should be fine. My first guess he is does not have all his dependencies... Maybe my list is dependencies is not comprehensive.

**Comment by enkodellc** [comment]
@zackmorgs  did you run:  dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview4.19579.2

**Comment by enkodellc** [comment]
@zackmorgs any updates? I am closing but would greatly appreciate any updates. Hopefully you sorted it out.

**Comment by zackmorgs** [comment]
I cloned the project again and didn't have the same problems. Very strange. Thanks all!

**Comment by enkodellc** [comment]
We refactored the whole project a couple days ago. Glad it is working for you now!
