### ISSUE TITLE
The sidebar icons are off with the padding for non dropdown items 

### ISSUE THREAD

**Issue by maximus258** [enkodellc/blazorboilerplate#116]
this code added to site.css should fix the issue. 

.app-sidebar .mdc-nav-li .material-icons {
    margin-right: 8px;
    padding-left: 0px;
}

**Comment by enkodellc** [comment]
@maximus258 Thansk, did you want to submit a PR?

**Comment by maximus258** [comment]
@enkodellc  I don't know how to submit a PR yet...  Next time I will :)

**Comment by enkodellc** [comment]
No problem. Git is not very hard but simple PR's like that can be done through github. Thanks for the input and hopefully you like Blazor Boilerplate. I think a lot of people will like version 0.6.0 with the CSB or SSB.
