### ISSUE TITLE
Encryption at Rest

### ISSUE THREAD

**Issue by trihugger** [enkodellc/blazorboilerplate#118]
One of the major topics in an enterprise application is encryption at rest. With SQL server 2016+ it is possible to do encryption at rest. .Net Core wasn't compatible until recently, which I think now supports only TDE (Transparent Data Encryption). 

I don't know enough to implement enough, but here's an article I found.

https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-3.1

Thank you

**Comment by soomon** [comment]
is there any special reason why you want to encrypt the binaries of your application? 
isn't it enough to encrypt the data using MSSQL or any other database?
which environment are we talking about? a cloud or on premises?

**Comment by las3r** [comment]
So this is something you set up at the SQL Server end, and not the application. It is nothing more than configuration in SQL Server and/or SQL Azure. See: https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption?view=sql-server-ver15.

If you want to turn on TDE, you can (already) do it without needing to change anything in your application code. Please keep in mind that the data is not encrypted at all, it is just the database itself which is encrypted.

**Comment by enkodellc** [comment]
@trihugger I am closing this from @las3r comments
