### ISSUE TITLE
Non-issue: dotnet run watch

### ISSUE THREAD

**Issue by zackmorgs** [enkodellc/blazorboilerplate#119]
I really like working on blazor apps with dotnet run watch command. I was wondering if there is any case the project can be modified to use this ability. 

Sorry if this is posted in the wrong place, just really wanted to know.

**Comment by enkodellc** [comment]
@zackmorgs  yes if you run in SSB mode / Server side Blazor you can debug & watch Blazor UI. The best place to ask blazor questions in my experience is here:  https://gitter.im/aspnet/Blazor

I prefer CSB but you can definitely do SSB to debug and then do final tests in CSB and release in CSB.

**Comment by enkodellc** [comment]
@zackmorgs if you have BB specific issues you can first post on the gitter https://gitter.im/blazorboilerplate/community and if it is really an issue then post on the Github repo issues.
