### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by win32nipuh** [enkodellc/blazorboilerplate#133]
Hi Keith, 
are you still going to create a NuGet package?  
It will be very useful package for Blazor developers.

**Comment by enkodellc** [comment]
@win32nipuh a Nuget template package is on the very bottom of my todo list.  I don't plan on getting to that for several months yet. I have been so busy with maintaining BB, answering questions, updating MatBlazor as well as my own projects that this will be far down the line.
