### ISSUE TITLE
CS0246: The type or namespace name 'App' could not be found

### ISSUE THREAD

**Issue by Oleg26Dev** [enkodellc/blazorboilerplate#136]
VS2019 (16.4.3)
I have created the solution with projects like the BB has. But receive the error in the Client:
public void Configure(IComponentsApplicationBuilder app)
{
app.UseLoadingBar();
app.AddComponent<App>("app"); //<-----------Error
}
error CS0246: The type or namespace name 'App' could not be found
Reviewed again and it seems the same as BB. One thing: I have removed all CSB, SSB configurations.

What can be the reason and how to fix it?

I have no ideas what is wrong. 
Uploaded the project there, may be you can help to understand:
https://send.firefox.com/download/ce4b84de86788228/#WjSILVKJppyyk2LHV5hSRw

Thank you

**Comment by enkodellc** [comment]
You are definitely missing something. I get the same error, I tried debugging but I apologize I don't have the time to solve / fix everyone's issues.

**Comment by enkodellc** [comment]
FYI I put the  <PropertyGroup/> Back in the .proj files and I got it to compile. You gutted too much. Please go back and review those.
