### ISSUE TITLE
Implement Identity Server 4

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#14]
@ganmuru has agreed to implement Indentity Server 4 into Blazor Boilerplate.

**Comment by marc-mueller** [comment]
Any roadmap on this feature?

**Comment by enkodellc** [comment]
@marc-mueller  I had one person verbally commit to building it but I have not heard from him in weeks. I have not used IS4 before and unfortunately since we are using .net core authorization for now it is on the bottom of the list for features.

**Comment by ganmuru** [comment]
@enkodellc tied up in another personal project and will be done with it in another couple of weeks. Will start integrating IS4 after that.

**Comment by enkodellc** [comment]
Thanks to @ganmuru  we have an IS4 branch.  I will be testing it out a bit. @marc-mueller please test and submit PR's / suggestions as the more eyes we have on it the better.

**Comment by enkodellc** [comment]
@marc-mueller if you could please test out the IS4 branch and let me know if you have any issues. Please delete your database before running. Thanks

**Comment by ganmuru** [comment]
Get latest before you test. Also make sure your database is deleted and have the appsettings.json set to Target sqlserver
