### ISSUE TITLE
Hosting BB in local IIS yields HTTP Error 500.30 - ANCM In-Process Start Failure 

### ISSUE THREAD

**Issue by soomon** [enkodellc/blazorboilerplate#140]
I have installed the current hosting bundle and enabled stdout logging.
The log file in .\logs reads:

2020-01-21 22:55:28.640 +01:00 [FTL] BlazorBoilerplate Host terminated unexpectedly
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at BlazorBoilerplate.Server.Startup.ConfigureServices(IServiceCollection services) in D:\prog\visual studio\blazorboilerplate\src\BlazorBoilerplate.Server\Startup.cs:line 169

studio\blazorboilerplate\src\BlazorBoilerplate.Server\Startup.cs:line 169 says:
storeMy.Open(OpenFlags.ReadWrite);

I have imported into the computer store but that doesn't help.
Which permissions does BB expect?

**Comment by enkodellc** [comment]
Did you copy the ssl thumbprint to your appsettings file?

**Comment by soomon** [comment]
No I did not. Startup.cs says: // Make sure Certificate is in the Web Hosting folder && installed to LocalMachine or update settings below
I chose option1: it is in local store and in the app directory. 

I tried adding the thumbprint but it didn't help:
2020-01-21 23:46:38.650 +01:00 [FTL] ProjMan Host terminated unexpectedly
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The system cannot find the file specified.

can you please provide an example on how to write the thumbprint? I tried all caps, small letters and with spaces in between as shown in the properties dialog of the certificate file.

**Comment by enkodellc** [comment]
The Readme has IIS hosting instructions including ssl tips. https://github.com/enkodellc/blazorboilerplate#publish-on-iis---what-works-for-me-on-my-windows-server-2016--sql-server-2014-enkodellc

Here is an example of my SSL settings: 

    "UseLocalCertStore": "true",
    "CertificateThumbprint": "‎143fbd7bc36e78b1bcf9a53c13336eaebe33353a"

**Comment by enkodellc** [comment]
Any update on this issue? I am going to close as this a user specific issue. If there are any other recommendations for Tips / Wiki please let me know.
