### ISSUE TITLE
Migration and Connection to Sql Server

### ISSUE THREAD

**Issue by cedriccbcomputer** [enkodellc/blazorboilerplate#141]
Hello,
I want to pass the site to Sql Server, doc I created an empty database on SQL Server, I changed the Default connection with my connection information.
But I am trying to initialize my new base with this command
-dotnet ef migrations add InitialApplicationDbMigration --context ApplicationDbContext -o Migrations \ ApplicationDb
-dotnet ef migrations add InitialConfigurationDbMigration --context DbContextOptionsBuilder -o Migrations \ ConfigurationDb
-dotnet ef migrations add PersistedGrantDbContext --context PersistedGrantDbContext -o Migrations \ PersistedGrantDb

And here is the error:
Error MSB4006: There is a circular dependency in the target dependency graph that implies the target "GetEFProjectMetadata". [C: \ Users \ cedri \ Source \ rest \ blazorinnova \ src \ docker-compose.dcproj]
Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.

Can you help me ?
Thank you

**Comment by enkodellc** [comment]
@cedriccbcomputer  You should not need to run those commands. Just remove any BlazorBoilerplate database you have and make sure your connection string is correct.  Are you using Docker?

**Comment by enkodellc** [comment]
@cedriccbcomputer  can you please update what the issues was and how you solved it for reference. Thanks

**Comment by cedriccbcomputer** [comment]
Hello, I solved my problem by removing from the project all the Docker part of the solution

**Comment by enkodellc** [comment]
@cedriccbcomputer the default repo has the docker project in the solution for reference but it is exclude as a project. Did you include it and get the error. Deleting it is fine if you don't use docker.

**Comment by cedriccbcomputer** [comment]
Hello, No he was excluded from the project but he was still making dependencies during the compilations.
I had a question about the connection When I connect by launching the project in debug mode it works well and when I launch the project in normal mode the connection is not made without any error it automatically returns to the connection window?

**Comment by enkodellc** [comment]
Thanks for letting me know. I will most likely take the docker project out then and put it up as a zip file or something.

As for your connection string issue. Start with checking all your appsetting.json files. 

- appsettings.json
- appsettings.development.json
- appsettings.production.json
