### ISSUE TITLE
Refresh log records

### ISSUE THREAD

**Issue by win32nipuh** [enkodellc/blazorboilerplate#143]
May be it can be useful to have a button <refresh> to refresh the table only, not entire page here
https://blazorboilerplate.com/blazor_middlware_audit

I.e. re-load data to the table

**Comment by enkodellc** [comment]
@win32nipuh again this would be a good candidate for a newbie to contribute. Maybe someone will / you will want to learn how do do this and then submit a PR. Then you will learn and other's can learn from you. Thanks
