### ISSUE TITLE
Adding New Claims Records

### ISSUE THREAD

**Issue by 274188A** [enkodellc/blazorboilerplate#150]
Just a clarification question: 
Am I correct in assuming assigning new claims to a new or existing role is more-or-less a manual work flow right now?
cheers
John

**Comment by enkodellc** [comment]
Correct, Do you have an example of something more automated or possibly describe your expected or ideal workflow?

**Comment by 274188A** [comment]
i saw something like this: https://kenhaggerty.com/articles/article/aspnet-core-22-user-claims

i've seen a tree view used to show the summary view of claims to roles before...somewhere...

**Comment by enkodellc** [comment]
John, I think what BB has is quite similar to what it done in the link.. more like almost exactly. 

I agree a treeview would be a nice feature. It is on the MatBlazor roadmap so once it is done I am sure it will happen at some point.  I agree we could go much further with admin tools but I me and the other contributors are working on an architecture refactor now... Hopefully after that we can do some additional features but contributors are always needed and appreciated.
