### ISSUE TITLE
ApplicationPermissions: How to use?

### ISSUE THREAD

**Issue by TCrosmanDSI** [enkodellc/blazorboilerplate#161]
I've been tinkering with the ApplicationPermissions.  Do you have an example as to how to use these with the [Authorize] attribute? Dynamically

**Comment by enkodellc** [comment]
Dynamically.. no I don't think I have come across that scenario yet. This sounds more like a question for .Net Core or this gitter -> gitter: https://gitter.im/aspnet/Blazor

If you have more questions please post them to https://gitter.im/blazorboilerplate/community  our gitter and we can move them to issues if needed. Thanks!
