### ISSUE TITLE
Try to integrate Blazorise

### ISSUE THREAD

**Issue by RalfPreuss** [enkodellc/blazorboilerplate#164]
Hi Keith,
first of all i want to note that this is a very great template.

Last weekend I tried to include Blazorise (material) in the project
but unfortunately I failed. When using a Blazorise component 
the browser reports the following error:

System.InvalidOperationException: Cannot provide a value for property 'ComponentMapper' on type 'Blazorise.Card'. There is no registered service of type 'Blazorise.IComponentMapper'.

I followed the instructions below
https://blazorise.com/docs/usage/material/

Best wishes
Ralf Preuss

**Comment by enkodellc** [comment]
@RalfPreuss  Thanks. This sounds like an issue for Blazorize to review.  Checkout their gitter:  https://gitter.im/stsrki/Blazorise?at=5e398cbcf6945f41ef5ad0f6
