### ISSUE TITLE
How to redirect the user directly to login page and do not show any content until authenticated?

### ISSUE THREAD

**Issue by veemat-home** [enkodellc/blazorboilerplate#180]
How to redirect the user directly to login page and do not show any content until authenticated?

**Comment by enkodellc** [comment]
@veemat-home thanks for using Blazor Boilerplate. Please direct these questions in the gitter chat as this is a user specific issue. https://gitter.im/blazorboilerplate/community

Please also review the source code and comments as I put a comment in the source already for this situation.  Look in the MainLayout.razor to find the code / comments
