### ISSUE TITLE
User registration is not catching duplicate username exception

### ISSUE THREAD

**Issue by hrrysnplusplus** [enkodellc/blazorboilerplate#189]
if you create a user with the username "hello"
and you try to create another user with the username "hello"

Expected: Error should show for duplicate username 
Actual: exception is thrown, but not caught, message says success even though user is not created

Thank you for this project this wonderful project!!!

**Comment by enkodellc** [comment]
Thanks I will try and get to this in the next 24 hours.

**Comment by hrrysnplusplus** [comment]
I fixed the bug but I never contributed to a github project before, I use TFS. heres the code for Register.razor page

 if (response.StatusCode == 200)
            {
                matToaster.Add("New User Email Verification was sent to: " + registerParameters.Email, MatToastType.Success, "User Creation Sucessful");
                navigationManager.NavigateTo("");
            }
            else
            {
                matToaster.Add(response.Message, MatToastType.Danger, "User Creation Failed");
            }

**Comment by enkodellc** [comment]
@hrrysnplusplus  Thanks! You can actually submit small PR's like this through github. If you want to do a your first Commit you will need to Fork the repo, then edit the file and then submit it as a PR:

https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository

https://opensource.com/article/19/7/create-pull-request-github

I can submit the changes as well after I test if you don't want to do the PR but I think it would be a good way for you to learn! Let me know.

Thanks again for using Blazor Boilerplate.

**Comment by hrrysnplusplus** [comment]
Thank you for allowing me be involved! All I ever wanted was to be a part of something! I'll submit the pull request

**Comment by enkodellc** [comment]
Harrison, no problem. Glad you were able to sort it out and contribute!  Years ago I got involved in a project on Github to learn Angular [MEAN.IO]. When I  started Blazor Boilerplate it was one of my goals is to get people involved because I enjoyed sharing and learning with people around the world.
