### ISSUE TITLE
Site Doesn't load on iOS devices

### ISSUE THREAD

**Issue by Redeye51** [enkodellc/blazorboilerplate#19]
Sorry if this is not the correct place for this but I tested your site on various devices and everything works except iOS devices. I've tested it on iPhone iPad and both hang on the loading screen. Is this a known issue?

**Comment by enkodellc** [comment]
I see you closed this issue. I did some testing on IOS but not extensively. Did you find a reason why it was not loading for you or what was your reason to close the issue?

**Comment by Redeye51** [comment]
No I didn't. I noticed that you used the Blazor with identities app
https://github.com/stavroskasidis/BlazorWithIdentity and it had the same
issue.

**Comment by enkodellc** [comment]
Thanks for the heads up on the repo I started with. I think I will wait for his solution for a few days and if he cannot sort it I will take a stab. I thought I had it working at one point but have been focused on new features.

**Comment by enkodellc** [comment]
Looks like it is a Blazor / AspNetCore issue:
aspnet/AspNetCore#12992

**Comment by Redeye51** [comment]
You sir are correct. I've been reading over that thread.  Thanks for taking the time to look into it.

Cheers!

**Comment by enkodellc** [comment]
This is now resolved with Preview9. I just tested on Iphone & Ipad.
