### ISSUE TITLE
Support Progressive Web Apps

### ISSUE THREAD

**Issue by halybang** [enkodellc/blazorboilerplate#192]
Blazor WebAssembly 3.2.0 support PWA, so BlazorBoilerplate will support?
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-2-release-now-available/

**Comment by enkodellc** [comment]
@halybang the latest code is on the 'restructure' branch. I committed last night: Blazor WebAssembly 3.2.0

https://github.com/enkodellc/blazorboilerplate/tree/restructure

Please join the chat on Gitter: https://gitter.im/blazorboilerplate/community  

There are some issues it seems but I had it running locally. Thanks for showing interest in Blazor Boilerplate!

**Comment by halybang** [comment]
To support PWA, Blazor Client need to include service-worker.js gen by Microsoft.

**Comment by GioviQ** [comment]
@halybang Please test PWA on development branch. At the moment I have included service worker but I do not use it. It's just the same web app, but in another browser window.
