### ISSUE TITLE
WebWindow support

### ISSUE THREAD

**Issue by halybang** [enkodellc/blazorboilerplate#193]
Any plan for support WebWindow? May we can share UI between SBS / CBS / PWA / WebWindow?
https://gunnarpeipman.com/blazor-hybrid-application-experimental/

**Comment by enkodellc** [comment]
@halybang I will have to take a look at WebWindow a bit more. You are the first to have brought it up. I like to discuss new features on the https://gitter.im/blazorboilerplate/community  if you want to join the chat there.

**Comment by GioviQ** [comment]
Planned with .NET 6
