### ISSUE TITLE
Login issue browser dependent

### ISSUE THREAD

**Issue by GioviQ** [enkodellc/blazorboilerplate#194]
Clone the repository
Run Debug_CSB
In Chrome (last version) Login with user or Admin, but no redirect at all.
In the console you read:

A cookie associated with a resource at http://localhost/ was set with `SameSite=None` but without `Secure`. It has been blocked, as Chrome now only delivers cookies marked `SameSite=None` if they are also marked `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5633521622188032.

**Comment by enkodellc** [comment]
Might need to review this: https://docs.microsoft.com/en-us/aspnet/core/security/samesite?view=aspnetcore-3.1

If you have time take a look and see what you can come up with. I won't get a chance to thoroughly look at it till tomorrow / Monday.

**Comment by GioviQ** [comment]
See https://github.com/enkodellc/blazorboilerplate/pull/195

**Comment by enkodellc** [comment]
Resolved with #195. Thanks @GioviQ  for fixing your own Issue and then more. We need more contributors like you.
