### ISSUE TITLE
Support for Blazor Testing?

### ISSUE THREAD

**Issue by Kronos11** [enkodellc/blazorboilerplate#199]
Are there any plans to add in tests using something like: https://github.com/egil/bunit
In order for this to be a true enterprise template I believe this will be required.

**Comment by Kronos11** [comment]
apologies I just saw this was already on the roadmap

**Comment by enkodellc** [comment]
@Kronos11 Take a look at the restructure branch. There is some tests in there. Honestly haven't ran or reviewed that part of the code yet.
