### ISSUE TITLE
Reset Password Failed

### ISSUE THREAD

**Issue by Fallenlight** [enkodellc/blazorboilerplate#20]
Hi, first of all thank you for the great boilerplate!!!

I successfully managed to (tried with the latest version - 01.8) : 
- Create new user, got email verification email and login.
-Tested forgot password, got email.
but unfortunately when i tried to reset the password, receiving "Failed to Reset Password" logs does not have anything either.

**Comment by enkodellc** [comment]
@Fallenlight  Thanks for reporting and using BlazorBoilerplate.  Yes most likely caused by the latest Middleware feature. I tested most items but not that yet.  If you want to try and debug you can. Might be a few days before I get to it.

**Comment by enkodellc** [comment]
Looks like it was most likely caused the be latest update to Preview 7. The **[ValidateAntiForgeryToken]** was no longer recognized but of course it compiles. Got to love Beta software. Please retest and if you use BlazorBoilerplate consider contributing or donating. Thanks!

**Comment by Fallenlight** [comment]
Cheers! Tested works like a charm.

**Comment by Fallenlight** [comment]
@enkodellc I have tried to debug c# code in ResetPassword.razor page, I am able to open the DevTools window but can`t see the C# code. (No Blazor.dll available in devtools) Server-side debugging works fine. I know this is a kind of very basic question but I feel like crippled without able to debug. Thanks!

**Comment by enkodellc** [comment]
@Fallenlight I am in the same boat, I know there is a some debugging available Client-Side but I have mostly just used the Console and the Log files to track down issues. So far all of the Client-Side code has been pretty easy and not needed much debugging or the errors are in the Browser console debugger. I learned most of that doing Angular:) I know they are working and have made Client Side debugging better but there is a long ways togo. Remember the timeline for Client-side Blazor is still over a year away from "production ready" according to what I have read.

This might help: https://docs.microsoft.com/en-us/aspnet/core/blazor/debug?view=aspnetcore-3.0
