### ISSUE TITLE
Logging not working for restructure branch

### ISSUE THREAD

**Issue by justSteve** [enkodellc/blazorboilerplate#202]
I've taken a couple swings with **restructure** and am finding that Serilog is not getting instantiated. Working against **master** with no db and Noah's stub for Serilog to SQL config -- both the Serilog table and and file-based log are created.

Copied the Serilog config object to **restructure**, changed _DefaultConnection_ to a non-existing db and all tables **except** Serilog are created. And no log file is created. No errors reported.

**Comment by np-at** [comment]
Try stopping and then running it again (leaving the db untouched between runs).
It seems like Serilog is attempting to use the db connection before EFCore has created it.  Although EFCore is set up to create a new db, Serilog.MSSqlServer is not.
Additionally Serilog doesn't seem to throw errors when it can't find the target database for some reason.....

**Comment by justSteve** [comment]
You are correct! First run fails - 2nd one works. thx

**Comment by np-at** [comment]
I just added a convenience method to #201 branch that gets rid of that issue (probably not appropriate for production but makes dev life easier)
