### ISSUE TITLE
Login form focus jumps back to 'user' field

### ISSUE THREAD

**Issue by justSteve** [enkodellc/blazorboilerplate#205]
Both restructure and master show this UI misbehavior:

The page opens with focus on the User Name control.
Enter a name
Tab to password control
In FF the focus till quickly revert back to the UserName control.
In CH* it'll take 2 tab presses to move focus
(no error reported).

Repeat the same and instead of tab to change field, use a mouse click. And wait just a moment to witness that focus snaps back to user name control.

**Comment by GioviQ** [comment]
If you use http and not https, it could be a cookie issue. See my PR https://github.com/enkodellc/blazorboilerplate/pull/195.

**Comment by enkodellc** [comment]
@justSteve I will try and get @GioviQ PR's through tomorrow. I spent most of the day fighting with Blazor / EF for the Multi-Tenant PR and lost the battle.

**Comment by enkodellc** [comment]
@justSteve The second tab for chrome is because it focus' the Remember me Checkbox.   To set the Tabs user the attribute _tabindex="x"_


```
            <div class="form-group">
                <MatTextField id="userName" @bind-Value="@loginParameters.UserName" Label="User Name" Icon="person" IconTrailing="true" FullWidth="true" Required="true" tabindex="1"></MatTextField>
            </div>
            <div class="form-group">
                <MatTextField @bind-Value="@loginParameters.Password" Label="Password" Icon="lock_outline" IconTrailing="true" FullWidth="true" Required="true" Type="password" tabindex="2"></MatTextField>
            </div>
            <div class="form-group">
                <MatCheckbox @bind-Value="@loginParameters.RememberMe" class="filled-in chk-col-blue" tabindex="4">Remember Me</MatCheckbox>
                <MatButton class="float-right" Type="submit" Raised="true" tabindex="3">Login</MatButton>
            </div>
```

**Comment by enkodellc** [comment]
@justSteve  after finding some time and doing some of my own testing I see that the problem was caused by the SetFocus JS function.  I think I sorted it out. Pushing the PR now.

**Comment by enkodellc** [comment]
FYI for future reference: https://blazor-university.com/javascript-interop/calling-javascript-from-dotnet/passing-html-element-references/
