### ISSUE TITLE
Speed up blazor development time

### ISSUE THREAD

**Issue by Kronos11** [enkodellc/blazorboilerplate#206]
what do you think about improving development time in the template with something like this?
https://remibou.github.io/Make-your-Blazor-development-faster/

**Comment by enkodellc** [comment]
Use the restructure branch and submit your PR to that branch. I think that would help a lot of people out. Thanks!!

**Comment by Kronos11** [comment]
Not needed anymore due to: https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/?
