### ISSUE TITLE
EF migration issues

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#207]
Anybody out there in BB land willing to take a look EF migrations on the restructure branch. I tried merging the Multi-Tenant PR into the restructure branch and then I wanted to clear the existing migration and start a new one.  Well I am not very good with EF and it was throwing this error and I could not sort out a work around.

_Unable to create an object of type 'ApplicationDbContext'. For the different patterns supported at design time"_

I started a wiki for tips / references:  https://github.com/enkodellc/blazorboilerplate/wiki/Creating-new-Model---Controllers---Migrations

This is why I despise EF. It errors, cannot sort it out and waste a ton of time. I prefer to just write my sql scripts and avoid all the automagic EF BS.

**Comment by GioviQ** [comment]
Can you commit the not working code?

**Comment by enkodellc** [comment]
I am going to push my changes to the restructure branch soon. Want the code to at least work and commenting out the offending code. Then I will be merging your latest PR into the Restructure Branch.  Once that is done if you want to review and submit more PR's against that branch it will be preferred. I want to halt dev on master.

**Comment by enkodellc** [comment]
@GioviQ the restructure branch is ready for review. @mobinseven said he is not ready for the Tenant PR yet so it is not critical to get the EF migrations working but it will be needed at some point. Thanks.
