### ISSUE TITLE
Code Generator Tool from SQL

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#208]
One of my big goals once the restructure branch is going is to build a code generator for existing Sql projects. Not sure if this is completely feasible but I am going to try. I have an Asp.net project that I want ported to Blazor. One of the main reasons why I started Blazor Boilerplate is for that project. So if anyone is interested in collaborating let me know.  FYI this would be a couple months out.

**Comment by GioviQ** [comment]
It is not clear to me. Do you mean existing SQL DB -> Entity Framework?

**Comment by enkodellc** [comment]
My goal would be to take an existing SQL DB and do code generation for all the layers of the application.  Even if it is very basic to start it would save time / typos. I have done it once before.

- CommonUI -> Pages -> Create Basic Pages for CRUD
- Server -> Controllers 
- Server -> Services
- Tests
- etc.

 I have 70+ tables in my project and most are CRUD and would need some modification / Dto but it might be cool to create a script to build those objects. Just an idea. I am pretty swamped with BB features and updates at the moment.

**Comment by juicebyjustin** [comment]
@enkodellc have you made any progress on this?

**Comment by enkodellc** [comment]
@GioviQ  has added most of the code automation within BB by using T4 templates in the src/Utils folder. I am closing
