### ISSUE TITLE
I am unable to get this to work with MS SQL

### ISSUE THREAD

**Issue by tygar45** [enkodellc/blazorboilerplate#21]
I get error "provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server" I am sure the connection string is correct, I use the same connection string in other projects.

**Comment by enkodellc** [comment]
Hi @tygar45 Thanks for using BlazorBoilerplate. I believe you have to review your  connection string and or server settings:

Here are some resources that might help:
https://www.c-sharpcorner.com/article/resolve-error-40-could-not-open-a-connection-to-sql-server/
https://stackoverflow.com/questions/9945409/how-do-i-fix-the-error-named-pipes-provider-error-40-could-not-open-a-connec
https://stackoverflow.com/questions/9945409/how-do-i-fix-the-error-named-pipes-provider-error-40-could-not-open-a-connec

**Comment by tygar45** [comment]
I output the connection string to the console and discovered it wasn't changing from localhost. Here is what I got in the appsettings:`   
 "DefaultConnection": "server=.\\SQL17; database=Test; Integrated Security=true",
    "MSSQL": "server=.\\SQL17; database=Test; Integrated Security=true",
    "SqlLiteConnectionFileName": "data.db"`

 "DefaultConnection" still outputs the server as localhost, but if I use MSSQL it connects.

**Comment by enkodellc** [comment]
This is the exact Connection string I use:

`"DefaultConnection": "Data Source=localhost;Initial Catalog=blazor_boilerplate;Trusted_Connection=True;MultipleActiveResultSets=true"`

And in my Server Startup.cs it is

` options.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"))); //SQL Server Database
   `
This is exactly how it is in the repo. Out of the 75+ people using the repo no one else has had an issue. So this is most likely a configuration on your SQL Server. I cannot help much as it is your server  so please research StackOverflow or other resources. The only other thing I can suggest is delete the existing blazor_boilerplate database on your SQL server if it already exists. You may need to add an alias to your server. Another idea is to actually create a SQL user and not use the TrustedConnection. I don't see any credentials in your pasted script. I will be closing this issue as it is specific to you.
