### ISSUE TITLE
Localization and Multi-Language Support

### ISSUE THREAD

**Issue by Stephen250** [enkodellc/blazorboilerplate#210]
Hey! 

Fantastic template you have here, has definitely saved me a lot of time not having to recreate already existing features. 

In the road map, is there any plans for multi-language/localization support?

**Comment by enkodellc** [comment]
Stephen, it is not currently on the roadmap, but I know it will be at some point. If you are will to contribute the current branch is 'restructure' so fork that. Also there is a lot of discussion in our gitter:  https://gitter.im/blazorboilerplate/community

**Comment by mobinseven** [comment]
That's an important feature which we can reach easily. I am currently using BB as a Persian (Farsi) platform, which is a RTL language too. I suggest we should define a class of constant strings containing every single language related text (log message, menu title, etc.) in the shared project. Then (for example) in constructing user session let users select which language they want to use. And in startup we could set the server language. For RTL languages (Persian, Arabic, Hebrew, ...) we need to alter styling as well. I don't think MatBlazor currently supports RTL styles. So there will be more to do about that.

**Comment by enkodellc** [comment]
@mobinseven  Thanks for your feedback. I figured it would be a fairly minor refactor, also like you said there are a lot of examples out there so it wouldn't be a huge undertaking. If you or anyone wants to start a PR.. As for MatBlazor the dev has slowed down quite a bit. Might consider doing a fork of it and try and gain support as SamProf has been non-responsive. Hopefully he will add some collaborators to help keep the repo growing.

**Comment by soomon** [comment]
Actually I thought my idea of a dumb text file with tons of strings in it would be too easy xD
Is that actually how it's usually done?

I will help translation BB to German :)

**Comment by GioviQ** [comment]
I suggest standard solution like shared resource library (dll satellite).
See
https://docs.microsoft.com/it-it/dotnet/framework/resources/packaging-and-deploying-resources-in-desktop-apps
https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization

**Comment by Stephen250** [comment]
Thank you all for the feedback, I had stumbled upon this yesterday and am curious what you think:

[https://dev.to/j_sakamoto/how-to-localize-texts-in-your-blazor-app-phn](https://dev.to/j_sakamoto/how-to-localize-texts-in-your-blazor-app-phn)

[https://github.com/jsakamoto/Toolbelt.Blazor.I18nText/blob/master/README.md](https://dev.to/j_sakamoto/how-to-localize-texts-in-your-blazor-app-phn)

It seems that it is regularly kept up to date, not sure if it supports RTL though.

**Comment by soomon** [comment]
> Thank you all for the feedback, I had stumbled upon this yesterday and am curious what you think:
> 
> https://dev.to/j_sakamoto/how-to-localize-texts-in-your-blazor-app-phn

It's from Japan, it has to be good! :D
Well, if other solutions require SSB or an api backend, using a library like this will be very helpful to everyone using CSB. It seems o be easy to use and without a lot of overhead.

**Comment by Blackleones** [comment]
yesterday at [blazordeskshow](http://blazordeskshow.com/) I've asked Daniel Roth about supporting .resx file and localization on Blazor WASM and he told me that it will be supported since the next preview.

**Comment by enkodellc** [comment]
@Blackleones  I am impressed you able to ask questions to Daniel Roth. That is good news for localization. If that is correct then I think we can put Localization on the timeline and maybe one of you or another one of BB amazing contributors want to take on the challenge when the next preview is released.

**Comment by GioviQ** [comment]
Please https://github.com/enkodellc/blazorboilerplate/pull/262

**Comment by GioviQ** [comment]
@soomon  You can add German language on development branch.
@Blackleones I used IStringLocalizer but I have refresh issue on WASM. Please see development branch.

**Comment by soomon** [comment]
> @soomon You can add German language on development branch.
WIll do :)
