### ISSUE TITLE
DTO with children objects

### ISSUE THREAD

**Issue by GioviQ** [enkodellc/blazorboilerplate#213]
DTO's are a common pattern and in this project they are widely used.
In my experience I never used directly because I used http://breeze.github.io/doc-cs/

What is a best practice to manage a DTO with a lot of children DTO objects and each child can be "added", "updated", "deleted", without writing a lot of code looping all the child collection finding differences with db entities and save changes?

**Comment by enkodellc** [comment]
Honestly I have not done much API / DTO so I just used some patterns that I found. I am VERY open to suggestions and other options.

**Comment by enkodellc** [comment]
@GioviQ I am very busy with my projects but I will make time to review this soon.
