### ISSUE TITLE
Cancel button behaviour in edit dialog

### ISSUE THREAD

**Issue by GioviQ** [enkodellc/blazorboilerplate#217]
E.g. see Users in Admin Section

Cancel button now closes only the dialog. The changes are not canceled although not saved and you see them in the table.
Used DTO has now no CancelChanges method, so at the moment the fast solution is to reload the list when closing the dialog.

What do you think about it?

**Comment by enkodellc** [comment]
This is very odd. I would prefer not to have the list reload. I think it actually would be best to disconnect the temp user from the list. I see we need a Clone() method in our Dto. I pushed the changes now. Please review and let me know what you think.

**Comment by enkodellc** [comment]
Also if this is the correct fix then we will want to update all Dto's to be IClonable. Note bot the Clone() and DeepClone() seemed to work but I suspect on more complex Objects a DeepClone will be needed.

**Comment by GioviQ** [comment]
I suggest to use some existing framework / library to manage Dto, because it is a common issue and do we need to reinvent the wheel?

This is just the question https://github.com/enkodellc/blazorboilerplate/issues/213.

**Comment by GioviQ** [comment]
See https://github.com/enkodellc/blazorboilerplate/pull/230
