### ISSUE TITLE
SQLServer / Sqlite config mixup

### ISSUE THREAD

**Issue by nstohler** [enkodellc/blazorboilerplate#24]
In https://github.com/enkodellc/blazorboilerplate/commit/907aabd4a5f20bfaa1e653e3eb6fef4f9fa31f83, `startup.cs`, I had to change 

`if (Convert.ToBoolean(Configuration["Authentication:UseSqlServer"] ?? "false"))`

to

`if (Convert.ToBoolean(Configuration["BlazorBoilerplate:UseSqlLite"] ?? "false"))`

Then I was able to `dotnet ef database update` and create and use the SQLServer db.

**Comment by enkodellc** [comment]
Thanks will update now.

**Comment by nstohler** [comment]
...in appsettings.json / appsettings.development.json, `UseSqlServer` is under `BlazorBoilerplate` not under `Authentication`

**Comment by nstohler** [comment]
https://github.com/enkodellc/blazorboilerplate/blob/3109a3782e600dee1df6ba8c5382d91ad392aee5/src/BlazorBoilerplate.Server/Startup.cs#L83

Haven't tested it myself, but shouldnt it be "BlazorBoilerplate`:`RequireConfirmedEmail"?

**Comment by enkodellc** [comment]
Yes, I was going to push the fix soon but caught up in a big change..
