### ISSUE TITLE
How to switch hosting mode

### ISSUE THREAD

**Issue by Blackleones** [enkodellc/blazorboilerplate#241]
I've noticed that you are using #if preprocessor to identity which hosting mode is enabled. How can you set `ServerSideBlazor` to `true`?

**Comment by mobinseven** [comment]
Read the [wiki](https://github.com/enkodellc/blazorboilerplate/wiki/Dual-Mode-CSB---SSB-Tips). It is done by VS build configurations.

**Comment by mobinseven** [comment]
@Blackleones Also, ask your questions in [gitter](https://gitter.im/blazorboilerplate/community). Your questions will be answered faster. Issues section is for reporting issues.

**Comment by enkodellc** [comment]
@Blackleones Thanks for using Blazor Boilerplate. Should see it in the VS Debug Dropdown options

@mobinseven thanks for your quick response! 
https://github.com/enkodellc/blazorboilerplate/wiki/Dual-Mode-CSB---SSB-Tips
