### ISSUE TITLE
launchSettings.json in BlazorBoilerplate.CommonUI

### ISSUE THREAD

**Issue by GioviQ** [enkodellc/blazorboilerplate#245]
![Annotazione 2020-03-27 180516 copy](https://user-images.githubusercontent.com/7103057/77781723-5859cd00-7056-11ea-989e-2f3aade3dc77.jpg)

I suppose it is useless, but I cannot remove it.

???

**Comment by enkodellc** [comment]
I tried this but didn't seem to work either.  This is a VS issue and not a direct BB issue.

Here are some links to review.
https://stackoverflow.com/questions/48604764/how-to-prevent-launchsettings-json-from-being-created-in-visual-studio-2017

https://developercommunity.visualstudio.com/content/problem/648360/launchsettingsjson-is-created-every-time-i-open-my.html?childToView=652195#comment-652195

I tried this but it did not help me. I could have been doing it wrong. <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
