### ISSUE TITLE
signalR Forum Page Error on load

### ISSUE THREAD

**Issue by np-at** [enkodellc/blazorboilerplate#247]
On first load of the Forum page (configuration: Debug_SSB ):
``` 
Microsoft.JSInterop.JSException: 'Failed to invoke 'Register' due to an error on the server.
Error: Failed to invoke 'Register' due to an error on the server.
    at _this.callbacks.<computed> (http://localhost:53416/_content/BlazorBoilerplate.CommonUI/javascript/signalr.min.js:18:16746)
```

**Comment by enkodellc** [comment]
I am sure this is an issue. I get an error when I use SSB in general.

**Comment by enkodellc** [comment]
I made some minor changes to the repo... not sure if it will help but I was able to get SSB going and could not recreate the issue you have specified. Please pull the latest and let me know if you still have the issue. thanks

**Comment by enkodellc** [comment]
@np-at I am closing as we have updated the code and I cannot recreate.
