### ISSUE TITLE
APIResponseRequestLogginMiddleware produces invalid JSON response

### ISSUE THREAD

**Issue by nstohler** [enkodellc/blazorboilerplate#25]
- I've added my own dto class into the shared project. One of the field is a `decimal`. 
- I added a service and a controller to the server project for reading all records/a single record. 

Basically all I did was copy the logic from the ToDo example.

I'm using SQL Server. 

But the produced JSON is then somehow not valid. It looks like there's some duplicate data at the end... 

Here's an example:
```
{"Version":"0.1.9","StatusCode":200,"Message":"Retrieved SI-Einträge","Result":{"moniker":"xxx","sicherheitsIndikatorMoniker":"xx-7","facilityMoniker":"xxx","bewertungMoniker":"normalitaet","userMoniker":"xxx","wertText":"111","wert":16789.123456789122,"bemerkung":"","year":"2018","month":"1","monthsValid":"1","timestamp":"2019-01-01T00:00:00","rowVersion":""}}on":""}}
```

If I remove the decimal data type (or change it to int), the response is fine. 

Edit:

Here's the code that produces the problematic JSON;
```
public async Task<APIResponse> Get(string moniker)
{
	var siEintrag = await _db.SicherheitsIndikatorEintraege.FirstOrDefaultAsync(t => t.Moniker == moniker);

	if (siEintrag != null)
	{
		var mapped = _autoMapper.Map<SicherheitsIndikatorEintragDto>(siEintrag);
		return new APIResponse(200, "Retrieved SI-Eintrag", mapped);
	}
	else
	{
		return new APIResponse(400, "Failed to Retrieve SI-Eintrag");
	}
}
```

The following code works (the response gets automatically wrapped in a APIResponse by the middleware):
```
public async Task<SicherheitsIndikatorEintrag> GetTest(string moniker)
{
	var siEintrag = await _db.SicherheitsIndikatorEintraege.FirstOrDefaultAsync(t => t.Moniker == moniker);
	return siEintrag;
}
```

**Comment by nstohler** [comment]
I've stepped through with the debugger and found the following so far:

The following line shortens my decimal values from 16789.12345678912345678912 to 16789.123456789122:
https://github.com/enkodellc/blazorboilerplate/blob/3109a3782e600dee1df6ba8c5382d91ad392aee5/src/BlazorBoilerplate.Server/Middleware/APIResponseRequestLogginMiddleware.cs#L235

I replaced the following line 
https://github.com/enkodellc/blazorboilerplate/blob/3109a3782e600dee1df6ba8c5382d91ad392aee5/src/BlazorBoilerplate.Server/Middleware/APIResponseRequestLogginMiddleware.cs#L249
simply with 
```
jsonString = bodyText;
```
and then the response is valid JSON. 

Of course I'm not suggesting that is a fix, I did not really try to understand any of the code of the middleware. But it seems that `JsonConvert.DeserializeObject<dynamic>(bodyText);` and `apiResponse = JsonConvert.DeserializeObject<APIResponse>(bodyText);` are not 100% working correctly with decimals.

**Comment by enkodellc** [comment]
@nstohler, looks like you need a lot of precision. Unfortunately since this is my first stab at most all the technologies in Blazor Boilerplate I am using others examples to build the functionality I need. I can only guess that you could try to edit your model and set some additional properties [DataAnnotations] or build a custom Serializer / Deserializer and have the middleware use that.   Another option is to contact the guy who wrote the middleware and see what he thinks: https://github.com/proudmonkey/RESTApiResponseWrapper.Core

**Comment by enkodellc** [comment]
One more thing is I am refactoring the architecture in major ways right now so please be patient. Thanks again for testing and finding issues.

**Comment by nstohler** [comment]
> looks like you need a lot of precision.  

I've tried first with the default precision for decimals in SQL Server and stored values like `111.0` and the same thing happened; the value got shortened to `111` in the middleware and the JSON was garbled too. 

> Another option is to contact the guy who wrote the middleware and see what he thinks: https://github.com/proudmonkey/RESTApiResponseWrapper.Core

I'll do that, thanks.

> One more thing is I am refactoring the architecture in major ways right now so please be patient. Thanks again for testing and finding issues.

Should keep I reporting what I find through github issues? Or through some other channel?

**Comment by enkodellc** [comment]
@nstohler feel free to use the https://gitter.im/blazorboilerplate/community  and tag me. If it is something that is directly blazorboilerplate then we can post it in issues. This could be considered that but other properties are fine so it is more specific to a decimal.  

Did you try the DataAnnotations attribute for precision?  https://stackoverflow.com/questions/19811180/best-data-annotation-for-a-decimal18-2

**Comment by nstohler** [comment]
> Did you try the DataAnnotations attribute for precision? https://stackoverflow.com/questions/19811180/best-data-annotation-for-a-decimal18-2

I've tried this too, same result. 

In https://github.com/enkodellc/blazorboilerplate/blob/9763b57fb72edf9020a0e08667f13b9cd8e3e792/src/BlazorBoilerplate.Server/Data/ApplicationDbContext.cs#L25
I have this to configure all decimals in my DB the same way:

```
// set decimal precision
const int decimalPrecision  = 26;
const int decimalScale      = 20;
string    decimalColumnType = $"decimal({decimalPrecision},{decimalScale})";

foreach (var property in builder.Model.GetEntityTypes()
    .SelectMany(t => t.GetProperties())
    .Where(p => p.ClrType == typeof(decimal)))
{
    property.SetColumnType(decimalColumnType);
}
```

**Comment by enkodellc** [comment]
Looks like you need to some additional serializer converter https://stackoverflow.com/questions/17871720/jsonserializer-serialize-decimal-places-with-n2-formatting

**Comment by enkodellc** [comment]
I was able to make a little progress but still got weird result

16789.12345678912345678912 => 
16,789.123456789122428745031357 

So instead of rounding the decimal it changed it I gave up. It is definitely an issue with Newtonsoft serializer / deserializer.  So if anything you review their issues and contact them. 

You could also edit the code and return the bodyText 


```
            if (!body.ToString().IsValidJson())
            {
                return httpContext.Response.WriteAsync(JsonConvert.SerializeObject(apiResponse, new DecimalFormatConverter()));
            }
            else
            {
               return body.ToString();
}
```

             


```
        public class DecimalFormatConverter : JsonConverter
        {
            public override bool CanConvert(Type objectType)
            {
                return (objectType == typeof(decimal) || objectType == typeof(decimal?));
            }

            public override void WriteJson(JsonWriter writer, object value,
                                           JsonSerializer serializer)
            {
                writer.WriteValue(string.Format("{0:N24}", value));
            }

            public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
            {
                JToken token = JToken.Load(reader);
                if (token.Type == JTokenType.Float || token.Type == JTokenType.Integer)
                {
                    return token.ToObject<decimal>();
                }
                if (token.Type == JTokenType.String)
                {
                    // customize this to suit your needs
                    return Decimal.Parse(token.ToString(),
                           System.Globalization.CultureInfo.GetCultureInfo("es-ES"));
                }
                if (token.Type == JTokenType.Null && objectType == typeof(decimal?))
                {
                    return null;
                }
                throw new JsonSerializationException("Unexpected token type: " + token.Type.ToString());
            }
        } 
```

**Comment by nstohler** [comment]
Thanks for your effort. I've tried using the custom serializer converter too, but somehow did not manage to get it running at all (breakpoints in the converter never got hit, no idea what I did wrong...). 

I guess the cleanest way to do this is at the moment is to use `string` in the dto class and use automapper serverside to convert to/from decimal in the db entity class.

**Comment by enkodellc** [comment]
No Problem. I was able to get the breakpoints to hit but I think it deserialized was off and then serialized and was incorrect. I had to give up. Running into several other issues with the latest code. .NET core updates and incomplete code examples are making it a challenge.

**Comment by nstohler** [comment]
I just noticed there's a successor to RESTApiResponseWrapper.Core:

https://github.com/proudmonkey/AutoWrapper
http://vmsdurano.com/autowrapper-prettify-your-asp-net-core-apis-with-meaningful-responses/

I did not analyze that part of the project in too much detail, maybe there are advantages to switch...

**Comment by enkodellc** [comment]
Thanks I will take a look at it now.

**Comment by nstohler** [comment]
> I am not sure initial issue will be resolved

@proudmonkey did something for the initial issue here: https://github.com/proudmonkey/RESTApiResponseWrapper.Core/issues/12#issuecomment-529042437

I am not using decimals on the client side anymore, so I did not have time to validate this. 

But anyway, I just wanted to let you know (not really related to the original issue).

**Comment by PatronizeKh** [comment]
Hey,
The problem is the response content length remains the same length of the original body, so the browser will take that length and try to parse it which causes the problem.
I've just added this code : 
context.Response.ContentLength = responseBody.Length;
at the beginning of finally scope 

https://github.com/enkodellc/blazorboilerplate/blob/3109a3782e600dee1df6ba8c5382d91ad392aee5/src/BlazorBoilerplate.Server/Middleware/APIResponseRequestLogginMiddleware.cs#L124

**Comment by enkodellc** [comment]
@PatronizeKh do you want to submit a PR?

**Comment by PatronizeKh** [comment]
@enkodellc I have forked the repository and commit the changes, what should I do else I'm new to Github xD

**Comment by PatronizeKh** [comment]
@enkodellc I've done a pull request
