### ISSUE TITLE
Got error message on iPhone

### ISSUE THREAD

**Issue by jbngan** [enkodellc/blazorboilerplate#251]
Will this template works on mobile devices? I've tried Chrome on iPhone XS Max and got a message "An unhandled error has occurred." Reload.

**Comment by GioviQ** [comment]
Do you mean https://blazorboilerplate.com/?
Or http://localhost.....

**Comment by enkodellc** [comment]
I have not tested with the latest version 0.8.0. I know version 6 which is the live demo version https://blazorboilerplate.com/ works on my android / iphone. 

I plan on publishing 0.8.0 to the demo site soon. Just was waiting for MatBlazor update to fix a menu glitch that really annoys me.

**Comment by jbngan** [comment]
> https://blazorboilerplate.com/

I meat  https://blazorboilerplate.com/ - thank for replying from enkodellc

**Comment by enkodellc** [comment]
@jbngan I can replicate a bug in IPhone 7 with the live demo, It does work on my Android. The real answer is that Blazor has been going through growing pains and some releases seem to work on IPhone / IOS and some don't. In the past there was nothing specific that can be done. Right webassembly Blazor / CSB and not fully released so this will be marked a known issue that I personally will not be addressing until later.

**Comment by enkodellc** [comment]
@jbngan, I just published 0.8.0 and it works on my Ipad.. Please test on your Iphone. thanks

**Comment by enkodellc** [comment]
Seems to work on Iphone I tested as well.
