### ISSUE TITLE
Do you log the Manager or the Controller?

### ISSUE THREAD

**Issue by justSteve** [enkodellc/blazorboilerplate#254]
Browsing the new Manager classes I'm not seeing logging statements embedded in (at a minimum) the `catch` blocks of the Manager. I'm wondering if there is convention that establishes any sort of preference of where best to log.

In the project I've recently stepped away from I was probably logging too much for most devs tastes. As I transition to .Core I'm finding things are quite different than they used to be. For example, not many projects seem to use ELMAH which used to be pretty much assumed to be present.

Looking forward I'd be happy to contribute some efforts to refining/backfilling the log stream but I'm not the one to take the lead on strategic decisions like where and how much is too much.

For example... look to the Update method of the Tenant manager - I'd be inclined to log both sides of the `try/catch` block but wonder if .Core has other, _'closer to the metal'_ ways of seeing that info.

Looking forward to your thoughts...

**Comment by enkodellc** [comment]
@justSteve  I have not used ELMAH and honestly I write bug free code. LOL. In real honesty I normally only add extra logging inside catch's when testing new code or when a new bug is found. So to ask me is not much help. 

When faced with this type of question I do what you are doing. Ask questions and look at other projects for examples. Might need some others to chime in on this question. Post it to the Gitter and see if anyone wants to join the discussion.

**Comment by GioviQ** [comment]
ApiResponseException attribute https://github.com/enkodellc/blazorboilerplate/blob/development/src/Server/BlazorBoilerplate.Server/Managers/AccountManager.cs#L38 adds try catch to all methods logging errors.
