### ISSUE TITLE
Floating label over placeholder

### ISSUE THREAD

**Issue by emakis** [enkodellc/blazorboilerplate#256]
If you write something f.e. ccc to filter the ToDo List and then delete the text, the floating label of textbox comes over of the placeholder as shown in the image. 
![image](https://user-images.githubusercontent.com/24392871/77941140-5eec7c80-72c2-11ea-821f-46eaa3f232c1.png)
It happens in both Edge(Beta) and Firefox

### Expected Behavior

After deleting the text of the filter textbox, this should return to the initial state, showing only the "Filter" word in gray and not in purple without the placeholder "Title"

**Comment by GioviQ** [comment]
In Chrome after losing the focus the text returns to initial state.
Anyway it is an issue of MatBlazor see https://www.matblazor.com/Table and in the bottom you will experience the same behaviour. Post an issue in https://github.com/SamProf/MatBlazor

**Comment by emakis** [comment]
Just for reference, I've created the issue
https://github.com/SamProf/MatBlazor/issues/475

**Comment by enkodellc** [comment]
Since this is a MatBlazor issue and it is reported there I am closing. 

Thanks for reporting there and for using Blazor Boilerplate
