### ISSUE TITLE
sign out is not complete issues

### ISSUE THREAD

**Issue by sTeaPig** [enkodellc/blazorboilerplate#257]
using SSB
if click signout icon Navigate To "/account/login" and refresh page, then will return to the logged-in state.

**Comment by sTeaPig** [comment]
I found out what is causing this problem
because in SSB
when login Succeeded, NavigateTo does not refresh RequestHeaders
so when i click signout to trigger /CommonUI/Services/Implementations/AuthorizeApi Logout()
This code will not get the correct cookies
```
if (_httpClient.DefaultRequestHeaders.TryGetValues("Cookie", out IEnumerable<string> cookieEntries))
    cookies = cookieEntries.ToList();
```
then i found a way to solved this problem.
in /CommonUI/Pages/Account/Login.razor OnParametersSetAsync()
enable forceload to forces the browser to load the new page from the server.
```
protected override async Task OnParametersSetAsync()
{
    var user = (await authenticationStateTask).User;

    if (user.Identity.IsAuthenticated)
    {
        //navigationManager.NavigateTo(navigationManager.BaseUri + navigateTo);
        navigationManager.NavigateTo(navigationManager.BaseUri + navigateTo, , forceLoad: true);
    }
}
```

**Comment by enkodellc** [comment]
@sTeaPig Thanks for diving into this. Did you want to submit a PR for the changes?
