### ISSUE TITLE
Http loading

### ISSUE THREAD

**Issue by solidcloudio** [enkodellc/blazorboilerplate#267]
In your hosted site under blazorboilerplate.com, everything is Lightning fast!

I cloned the code and started customizing things,  my load times are much slower,  does the boilerplate site use caching or something to increase load times?  

Seems it’s still using http to a controller vs using signalr..   is there a plan to use signalr instead of the json api requests?

**Comment by solidcloudio** [comment]
When loading todos for example, I dont see an HTTP request made, and the todos load in 0.25 seconds...  How is this done ?
![image](https://user-images.githubusercontent.com/11837859/79138435-5c316300-7d69-11ea-8277-e6dc0699f196.png)

**Comment by enkodellc** [comment]
Hi @solidcloudio I am hosting on my own server and ther is no special caching. I only do a Gzip Compression done with IIS / web.config. 

Right now I have no plans to use Signlr instead of API requests... busy working on other features. I am not opposed to it but just not on my list of items to do.

**Comment by enkodellc** [comment]
It definitely makes an Http Request. I think that is a question for the https://gitter.im/aspnet/Blazor  group. 

https://docs.microsoft.com/en-us/aspnet/core/blazor/call-web-api?view=aspnetcore-3.1

As a side note I see you are in Chandler. I am in Phoenix, if you want to connect: https://gitter.im/enkodellc
