### ISSUE TITLE
WASM live demo is not working

### ISSUE THREAD

**Issue by ahmetsekmen** [enkodellc/blazorboilerplate#292]
https://blazorboilerplate.com/

**Comment by enkodellc** [comment]
Watch country are you in? It looks like Turkey and that country is blocked by my firewall as described in the readme. Please read the full ReadMe,

Try this one: https://openid.quarella.net/

**Comment by ahmetsekmen** [comment]
Yes i am in Turkey, i missed that part. 
I tried to enter with VPN now its working.
https://blazorboilerplate.com/

But in network tab it seems like its Server side Blazor. 
Am i wrong?
![image](https://user-images.githubusercontent.com/10855574/80862239-1686fc80-8c7c-11ea-9045-d1b426196fed.png)

**Comment by GioviQ** [comment]
@ahmetsekmen Yes it is server side.

**Comment by ahmetsekmen** [comment]
Document says that this(blazorboilerplate.com/) is Client side
I am looking for Client side live sample
Do you know any adress which i can check ?

**Comment by ahmetsekmen** [comment]
> @ahmetsekmen Yes it is server side.

Document says that this(blazorboilerplate.com/) is Client side
I am looking for Client side live sample
Do you know any adress which i can check ?

**Comment by GioviQ** [comment]
@ahmetsekmen I have recently update development branch live demos:
https://blazor-server.quarella.net/
https://blazor-wasm.quarella.net/ this is what you are looking for

**Comment by ahmetsekmen** [comment]
@GioviQ 
Thanks . For care

**Comment by enkodellc** [comment]
https://blazorboilerplate is CSB / WASM. 

Demo is server-side hosted by @GioviQ  https://blazor-server.quarella.net/
