### ISSUE TITLE
MatSelect

### ISSUE THREAD

**Issue by mhartwig123** [enkodellc/blazorboilerplate#298]
I cannot seem to get a MatSelect to work.

`<MatSelect Label="Enable Reviews" @bind-Value="@reviewsEnabled">
                <MatOptionString Value="1">Reviews Enabled</MatOptionString>
                <MatOptionString Value="0">Reviews Disabled</MatOptionString>
            </MatSelect>`

![image](https://user-images.githubusercontent.com/64933934/81238043-e1e5ae80-8fb5-11ea-930b-c0cbf9f08bf2.png)

I can get other elements, checkbox, etc... to work just fine, just not MatSelect. Any ideas?

**Comment by enkodellc** [comment]
I would suggest to start with using the default code from MatBlazor first, then that will tell you you have all the MatBlazor configured. Then try plugging your code into a BlazorFiddle to test it outside BB. You should be able to find your issue from those steps.

https://www.matblazor.com/Select
https://blazorfiddle.com/temp/13ecc13d-ce59-4d18-b890-d22a275ed93f

**Comment by mhartwig123** [comment]
Your right, my bad. I was doing wrong. I apologize. Thanks.

**Comment by enkodellc** [comment]
No worries, Thanks for using Blazor Boilerplate! Please give the repo a star if you haven't already
