### ISSUE TITLE
[Enhancement] Allow use of MariaDB/MySQL as a database sevice

### ISSUE THREAD

**Issue by Laikar** [enkodellc/blazorboilerplate#299]
On the [official Documentation for Entity Framework](https://docs.microsoft.com/en-us/ef/) microsoft states support for MariaDB/MySQL via the [Pomelo provider](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql).

**Comment by enkodellc** [comment]
@Laikar are you requesting that I do this integration?

**Comment by Laikar** [comment]
Not a request, but a suggestion, sorry if it sounded like i was demanding anything. I am trying to adapt it to use MariaDB for a personal project but i think it is way out of my scope.
If i get anything working i will make a pull request/provide information for its implementation.

**Comment by enkodellc** [comment]
@Laikar no worries, it just wasn't clear if you wanted help or were just leaving information for others.  I can make a note of it in the read me but like the postgres integration it is not something I will maintain as I am a SQL guy, and that is the most common db among MS devs. I will be willing to post any tutorial or create a branch if necessary to do third party databases so that it may help others.

**Comment by Laikar** [comment]
I have managed to get it working, setting up the MariaDB connection with the pomelo connector and building the migrations,

I used these commands to build the migrations.

```
dotnet ef migrations add --project BlazorBoilerplate.Storage InitialApplicationDbMigration --context ApplicationDbContext -o Migrations\ApplicationDb -s BlazorBoilerplate.Server
dotnet ef migrations add --project BlazorBoilerplate.Storage InitialConfigurationDbMigration --context ConfigurationDbContext -o Migrations\ConfigurationDb -s BlazorBoilerplate.Server
dotnet ef migrations add --project BlazorBoilerplate.Storage PersistedGrantDbContext --context PersistedGrantDbContext -o Migrations\PersistedGrantDb -s BlazorBoilerplate.Server
```

I don't really know how should the database info be implemented, i made a quick class for it, and used this on Server/startup.cs  and Storage/ServiceColletionExtrensions.cs replacing the other database context builders.

```
 builder.UseMySql(info.ConnectionString, mysqloptions =>
                {
                    mysqloptions.ServerVersion(info.Version, info.ServerType).MigrationsAssembly(migrationsAssembly);
                });
```

**Comment by enkodellc** [comment]
@Laikar  thanks for sharing. I will close this but others should be able to search the issues for it. If you want to submit a PR for adding anything additional to the readme or documentation, feel free.
