### ISSUE TITLE
user name not displayed after login

### ISSUE THREAD

**Issue by nstohler** [enkodellc/blazorboilerplate#3]
# Problem
When I logged in, the index page only displayed "Hello  !!!" (missing username). When I refreshed the page, I got the correct result: "Hello tester !!!"

# How to fix it

in AuthorizeApi.cs:
```
public async Task<UserInfo> Login(LoginParameters loginParameters)
{
    var result = await _httpClient.PostJsonAsync<UserInfo>("api/Authorize/Login", loginParameters);
    return result;
}
```

**Comment by enkodellc** [comment]
@nstohler Thanks for the contribution, looks good. Do you have an example on how to catch BadRequests / error handling?  I could not find one.

**Comment by nstohler** [comment]
@enkodellc  I will look into the error handling during the next few days and get back to you if I find anything useful.
