### ISSUE TITLE
Question: Modified version of the boilerplate shows the loading screen only

### ISSUE THREAD

**Issue by SeppPenner** [enkodellc/blazorboilerplate#30]
I have the following problem and maybe you see a quick solution (or had this issue before):

I'm using the boilerplate in a modified way in my project. (I used the version from preview8 and updated the project to preview9 on my own). However, since the update, I only see the loading screen and the project itself isn't shown. The swagger page works correctly when you navigate to it with the browser.

I know, it's quite difficult to tell where this comes from as I can't provide you the exact code, but maybe you already had a similar issue, @enkodellc?

**Comment by SeppPenner** [comment]
Oh, I guess, I will put this to gitter as a question as well.

**Comment by enkodellc** [comment]
I am published Preview9 and am getting a similar issue:  "Failed to execute 'querySelector' on 'Document': '0' is not a valid selector"  Will try and debug but I couldn't find anything on this last night. It was happening on debugging but now on server not sure where to look.

**Comment by enkodellc** [comment]
I got it working by creating a new project and using that new project's client project... Going to try and see what the difference is.

**Comment by enkodellc** [comment]
I have it working now, remove <CascadingAuthenticationState> from the app.razor file and see if that works for you. I published to my server and it is now working. If that works for you please close this issue.

**Comment by SeppPenner** [comment]
I will check this tomorrow and come back to you here.

**Comment by SeppPenner** [comment]
I found the issue: I forgot to call

```csharp
<app>
    @(await Html.RenderComponentAsync<App>(RenderMode.Server))
</app>
```

in my server side project's `_Host.cshtml` file... Stupid little issue 😣
