### ISSUE TITLE
Building the template?

### ISSUE THREAD

**Issue by isc30** [enkodellc/blazorboilerplate#301]
Hi, I'm trying to build the template locally and get the following error:
![imagen](https://user-images.githubusercontent.com/10807051/81495489-e0b3ca80-92b0-11ea-8e7f-b320ffa51f1b.png)

- dotnet sdk 3.1.201
- visual studio 16.4.2

Is it possible to get a guide on how to build and test (demo?) the template properly?

**Comment by isc30** [comment]
Pinging @GioviQ

**Comment by isc30** [comment]
Ok the error seems to be: 
>Couldn't connect to Docker daemon. You might need to start Docker for Windows.

Is this 100% required? I'm running multiple virtual machines in this host and I cannot disable HyperV

**Comment by enkodellc** [comment]
Not required. Exclude docker project and it will work.

**Comment by GioviQ** [comment]
I answered by email, but I cannot see it 😞 
Anyway like Keith said docker project is not necessary. I cannot install docker on my Windows 10 Home, so I never tested. After my projects reworking docker config has to be fixed (paths).

**Comment by isc30** [comment]
Great thanks :)
