### ISSUE TITLE
Client side login not working with Firefox v76

### ISSUE THREAD

**Issue by conficient** [enkodellc/blazorboilerplate#307]
Created a blank application using the template (excellent work BTW!) for client-side Blazor

Works fine on Chrome and Edge, able to log in

Firefox (version 76.0.1)  accepts the login details, returns a 200 response from the `Login` and `GetUser` but the login box remains. There is an error in the browser console:
```
Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed.
```
from `blazor.webassembly.js`

I suspect this is not an issue with BlazorBoilerplate but possibly a mono/webassembly incompatibility so perhaps something you can't fix.

**Comment by GioviQ** [comment]
Please try development branch.

**Comment by knight1219** [comment]
This might be silly, but what was the fix for this? I've got this same
issue with a blazor site  after an upgrade to the RC of blazor. I know this
isn't directly tied to BBP, but I can't find anywhere that has this issue.

**Comment by enkodellc** [comment]
@conficient / @knight1219   please look at the latest commits. I updated all the nugets and tested with CSB on FF 76.0.1 on the master branch without issue.  If you are using development branch let me know I have not tested that as @GioviQ has been managing that branch.

```
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
```

**Comment by conficient** [comment]
Hmm no, I used the "template" option to create a test repo on my account. Could be the template was out of date. I updated the references to 3.1.4 and still have the same error. I decided the problem was probably with Firefox, so I reinstalled FF - and guess what it now works.

Thanks for the help
