### ISSUE TITLE
Demo blocked some IP ranges

### ISSUE THREAD

**Issue by marciogoularte** [enkodellc/blazorboilerplate#33]

**Comment by marciogoularte** [comment]
I am trying to access and https does not load the demo page ERR_CONNECTION_TIMED_OUT. 
http displays this error.
![image](https://user-images.githubusercontent.com/215987/64621267-c4772b00-d3bb-11e9-8c8a-80b76cbff991.png)

I can access for my VPS from UK

**Comment by enkodellc** [comment]
Yes there is a GEO IP block on my firewall.  Unfortunately we live in a world where people attack others servers for either for fun or for profit. I have received such attacks before so in response my security team suggested I block IP addresses from Nations where my business is not monetized. I apologize for this but I will not be changing anything. Blazorboilerplate should be fairly easy for you to download and publish on your own server for testing. And as you have done found a work-around with a VPN.
