### ISSUE TITLE
Issue under Azure

### ISSUE THREAD

**Issue by quantisiamo** [enkodellc/blazorboilerplate#330]
Deployed under Azure: unable to login. 
After user is succesfully logged in, it remains as NotAuthorized on frontend side.

Any help really appreciated

**Comment by GioviQ** [comment]
Did you also try development branch?

**Comment by enkodellc** [comment]
Closing as the opener is non-responsive.

**Comment by quantisiamo** [comment]
Hi all, I'm sorry for the delay.
I solved partially enabling "WebSocket" under azure, but still randomly logout, probably cause from some signalR configuration, but not checked anymore.
So I moved to webassembly, and it works fine.
Thank you
