### ISSUE TITLE
Http statuscode always returns 200Ok

### ISSUE THREAD

**Issue by Staalkoper** [enkodellc/blazorboilerplate#331]
Goodday,

I noticed that every time you request an endpoint it always returns the ApiResponse object with a `200 Ok` statuscode.

Reproduction:
1. Request: GET endpoint `api/todo/{integerThatDoesntExistInTheDatabase}/`

Result: 
Http Statuscode: `200 Ok`
JSON object : 
`{
    "Version": "1.0.0.0",
    "StatusCode": 400,
    "IsError": false,
    "Message": "Failed to Retrieve Todo"
}`

Problem: The Http Statuscode should show `400 Bad Request` instead of `200 Ok`

Question: Am I missing something or is this a genuine issue?

**Comment by GioviQ** [comment]
It is a design decision to wrap the API results in ApiResponse class, so the http status code is a property of this object as you see.

**Comment by enkodellc** [comment]
@GioviQ has it the answer!  We do this as this allows for a softer response to the user. In most cases this a toast message.
