### ISSUE TITLE
Issues SSB Login

### ISSUE THREAD

**Issue by ToanHT** [enkodellc/blazorboilerplate#336]
I am working with a copy of the boilderplate.
I have login issues in SSB.
Step:
1. Enter url: https://localhost/account/login => Enter username and password, submit=> Login success and system auto redirect to https://localhost, but system still NotAuthorize
2. Enter Url: https://localhost/account/login again, i check IsAuthenticated function OnParametersSetAsync in Login.razor, IsAuthenticated = true. And system auto redirect to MainPage (https://localhost)
3. But Main Page still not Authorize

So, i cheat, i remove function OnParametersSetAsync for enter username, password again=> Login successful and MainPage Authorize then i press F5, system loss authorize again. I don't know why 

If in MainPage, i **click button Login** , login worked, but if i enter url account/login not work.

Any ideas on how I can fix the issue?

**Comment by GioviQ** [comment]
Please try development branch.

**Comment by ToanHT** [comment]
Thanks @GioviQ, development branch worked.
