### ISSUE TITLE
swagger page down

### ISSUE THREAD

**Issue by imtrobin** [enkodellc/blazorboilerplate#337]
This link down

https://blazorboilerplate.com/swagger/index.html

**Comment by enkodellc** [comment]
Working for me. Does this work https://blazorboilerplate.com?

**Comment by imtrobin** [comment]
Nope, still doesn't work for me. You have IP block on region?

**Comment by enkodellc** [comment]
Yes, I block several countries with my firewall that I do not do business in to help reduce attacks on my server. This is described in the readme. That is why I asked if https://blazorboilerplate.com also doesn't work.
