### ISSUE TITLE
BlazorBoilerplate.CommonUI  httpclient   PutJsonAsync/GetJsonAsync/.... not found.

### ISSUE THREAD

**Issue by git-net** [enkodellc/blazorboilerplate#340]
all httpclient  method PutJsonAsync/GetJsonAsync/....

need some package?

**Comment by GioviQ** [comment]
These issues have been fixed in development branch.

**Comment by gratiaterra** [comment]
FYI, I just updated to development branch and noticed these errors. They are easily fixed, however when I started testing I got this runtime exception and am unable to authenticate:
"Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed."
I've yet to find out why this occurs, anyone know?

**Comment by GioviQ** [comment]
The last development branch is published in
https://blazor-server.quarella.net/
https://blazor-wasm.quarella.net/

The authentication issue was fixed in commit https://github.com/enkodellc/blazorboilerplate/commit/dbee57e2aa6a09604e3138643d1bb270c14c5288

**Comment by gratiaterra** [comment]
Thanks! Unfortunately, I noticed that Breeze 0.9 won't load and 0.8 targets .NET Standard 2.0 so the project won't load. What are the plans for Breeze?

**Comment by GioviQ** [comment]
@gratiaterra you have to sync the last commits. See https://github.com/enkodellc/blazorboilerplate/issues/344

Let me know

**Comment by GioviQ** [comment]
Breeze is use in ToDo list

**Comment by osaaso1** [comment]
I have the same issue...

**Comment by GioviQ** [comment]
@osaaso1 did you try development branch?

**Comment by osaaso1** [comment]
Thanks Giovanni,
Yes, the Development works. But I used to put my customized pages in CommonUI project module.
I hope you gonna come up with a solution or let me know what can I do. I keep getting that message even with fresh project and cannot run the new versions anymore. Best.

**Comment by GioviQ** [comment]
@osaaso1 you can put application specific pages in a module like https://github.com/enkodellc/blazorboilerplate/tree/development/src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo

**Comment by osaaso1** [comment]
Thanks again, would it be a temporary issue to get fixed soon or a part of your plan we didn't know about. I use MS VS community, last updates by the way.

**Comment by GioviQ** [comment]
I am trying to modularize UI:

Base UI theme with general purpose pages
https://github.com/enkodellc/blazorboilerplate/tree/development/src/Shared/Modules/BlazorBoilerplate.Theme.Material

Admin UI
https://github.com/enkodellc/blazorboilerplate/tree/development/src/Shared/Modules/BlazorBoilerplate.Theme.Material.Admin

Demo pages
https://github.com/enkodellc/blazorboilerplate/tree/development/src/Shared/Modules/BlazorBoilerplate.Theme.Material.Demo

Google Analytics module
https://github.com/enkodellc/blazorboilerplate/tree/development/src/Shared/Modules/BlazorBoilerplate.GoogleAnalytics

I am trying to find inspiration from Oqtane project.

**Comment by osaaso1** [comment]
Thanks Giovanni, That is great.

**Comment by GioviQ** [comment]
I'll write some info in the wiki

**Comment by GioviQ** [comment]
@gratiaterra Please read https://github.com/enkodellc/blazorboilerplate/wiki/RoadMap#breeze

@osaaso1 Please read https://github.com/enkodellc/blazorboilerplate/wiki/RoadMap#modularization

**Comment by osaaso1** [comment]
Dear Giovanni, 
Just to let you know that I just realized that the Httpclient error message is related to MatBlazor, latest update 2.6.
The master branch works fine with earlier versions.

**Comment by GioviQ** [comment]
There is a namespace conflict.

**Comment by enkodellc** [comment]
I have been trying to replace ApiResponse with HttpResponseMessage. I have made some headway. I am just not a great developer or it doesn't work as it should. Probably both:  https://stackoverflow.com/questions/62605390/httpresponsemessage-send-receive-list-or-array-of-t

**Comment by enkodellc** [comment]
For now I rolled back System.Net.Http.Json and re-added Microsoft.AspNetCore.Blazor.HttpClient . This fixes the issues until I figure out HttpResponseMessage

**Comment by enkodellc** [comment]
Latest Master has it resolved.
