### ISSUE TITLE
login broken

### ISSUE THREAD

**Issue by 274188A** [enkodellc/blazorboilerplate#35]
step to reproduce:
1. use local sql server
2. run migrations scripts
3. start app
4. inspect AspNetUsers Table for user named `user` - all good.
click login
enter `user` & `user123` for username & pw

problem - put a break point in the accountcontroller line 326 for `builduserinfo`
the line

`var user = await _userManager.GetUserAsync(User);`

`user` is null

**Comment by enkodellc** [comment]
@274188A Sorry to hear you are having issues logging in. I have not seen this issue. Using the latest code I deleted my Sql database. Ran the Seed / migration and I was able to login fine. Please double check your appsettings and make sure you have the latest code.

Also I am assuming you clicked the Login button after entering the user name and pw?

**Comment by 274188A** [comment]
hmm, strange - maybe a browser issue (cookies blocked) so will re-try.  yes i did click the login button ...

**Comment by 274188A** [comment]
yup - it was a chrome issue.  used another browser and all good
