### ISSUE TITLE
Implement IMustHaveTenant and IMayHaveTenant

### ISSUE THREAD

**Issue by las3r** [enkodellc/blazorboilerplate#355]
As with a similar package (Asp.net boilerplate) they are using the following interfaces to make entities automatically implement TentantId on entity rows. THey are automatically filtered on where clauses:

IMustHaveTenant - TenantId field required, and automatically queried in the where clause to do data restriction based on the current tenant the user is logged in for (where tenantid = {id}.

IMayHaveTenant - Used for data that MIGHT be tenant-specific, but doesn't have to be. Good example would be todo-categories - a set of defaults for every tenant (open, completed) but specific statusses for a single tenants "in-progress". (where tenantId = null or tenantId = {id}) 

Would this be a good approach for BBP to use?

**Comment by GioviQ** [comment]
This project currently uses https://www.finbuckle.com/MultiTenant

I also implemented tenant settings in development branch.

**Comment by las3r** [comment]
Ah fantastic! Let me close this then.
