### ISSUE TITLE
Replace Azure set up PDF with wiki+ARM template

### ISSUE THREAD

**Issue by las3r** [enkodellc/blazorboilerplate#356]
The current repo has a pdf outlining all requirements for deploying to Azure.
Imho this should move to a wiki here. Additionally, folks who are used to deploying stuff to Azure with e.g. Azure DevOps are usually working with Azure Resource Manager templates (ARM-templates) that act as infrastructure as code. 

I can help by adding this ARM template as well as writing a wiki on the matter if there are more people interested and looking for this.

**Comment by enkodellc** [comment]
@las3r , If you want to submit a PR for the ARM Template and Wiki I think it would be a great benefit. Thanks!

**Comment by enkodellc** [comment]
@las3r  Take a look at this PR:  https://github.com/enkodellc/blazorboilerplate/pull/523/files

**Comment by enkodellc** [comment]
@las3r this is over a year old now and I think @12step  has been doing several Azure updates. #612 and #611  If you want to review and add additional info please re-open and submit a PR. Thanks
