### ISSUE TITLE
Using Flurl instead of HttpClient

### ISSUE THREAD

**Issue by krishnan2784** [enkodellc/blazorboilerplate#360]
I forked your code to test its use as a potential for an app I am building. However I see that currently the source uses the default HttpClient. I think using Flurl (https://flurl.dev/) would make the code a lot cleaner and easier for people using the template to create api calls. Flurl is also a recommended Nuget Package By Scott Hanselman and James Montemagno

For example in AuthorizeApi:
` public async Task<ApiResponseDto> Login(LoginDto loginParameters)
        {
            ApiResponseDto resp;

            var httpRequestMessage = new HttpRequestMessage(HttpMethod.Post, "api/Account/Login");
            httpRequestMessage.Content = new StringContent(JsonConvert.SerializeObject(loginParameters));
            httpRequestMessage.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");

            using (var response = await _httpClient.SendAsync(httpRequestMessage))
            {
                response.EnsureSuccessStatusCode();

//if ServerSideBlazor

                if (response.Headers.TryGetValues("Set-Cookie", out var cookieEntries))
                {
                    var uri = response.RequestMessage.RequestUri;
                    var cookieContainer = new CookieContainer();

                    foreach (var cookieEntry in cookieEntries)
                    {
                        cookieContainer.SetCookies(uri, cookieEntry);
                    }

                    var cookies = cookieContainer.GetCookies(uri).Cast<Cookie>();

                    foreach (var cookie in cookies)
                    {
                       await _jsRuntime.InvokeVoidAsync("jsInterops.setCookie", cookie.ToString());
                    }
                }
//endif

                var content = await response.Content.ReadAsStringAsync();
                resp = JsonConvert.DeserializeObject<ApiResponseDto>(content);
            }

            return resp;
        }`

Will Become:
`
 public async Task<ApiResponseDto> Login(LoginDto loginParameters)
        {
            using var response = await $"{_navigationManager.BaseUri}api/Account/Login".PostJsonAsync(loginParameters);
            response.EnsureSuccessStatusCode();

            if (response.Headers.TryGetValues("Set-Cookie", out var cookieEntries))
            {
                var uri = response.RequestMessage.RequestUri;
                var cookieContainer = new CookieContainer();

                foreach (var cookieEntry in cookieEntries)
                {
                    cookieContainer.SetCookies(uri, cookieEntry);
                }

                var cookies = cookieContainer.GetCookies(uri).Cast<Cookie>();

                foreach (var cookie in cookies)
                {
                    await _jsRuntime.InvokeVoidAsync("jsInterops.setCookie", cookie.ToString());
                }
            }

            var resp = await response.Content.ReadFromJsonAsync<ApiResponseDto>();

            return resp;
        }

`
I am happy to refactor this change I have a lot of experience using Flurl.

**Comment by GioviQ** [comment]
It cannot be used everywhere. There are some classes that requires a httpclient .
Look at development branch.

**Comment by enkodellc** [comment]
@krishnan2784 thanks for the option but with the new System.Net.Http.Json I was able to change it to this, which to me looks like the same amount of code as Flurl.  Am I missing something?:


        public async Task<ApiResponseDto> Login(LoginDto loginParameters)
        {
            ApiResponseDto resp;

            HttpResponseMessage response = await _httpClient.PostAsJsonAsync("api/Account/Login", loginParameters);
            using (response)
            {
                response.EnsureSuccessStatusCode();

`#if` ServerSideBlazor

                if (response.Headers.TryGetValues("Set-Cookie", out var cookieEntries))
                {
                    var uri = response.RequestMessage.RequestUri;
                    var cookieContainer = new CookieContainer();

                    foreach (var cookieEntry in cookieEntries)
                    {
                        cookieContainer.SetCookies(uri, cookieEntry);
                    }

                    var cookies = cookieContainer.GetCookies(uri).Cast<Cookie>();

                    foreach (var cookie in cookies)
                    {
                       await _jsRuntime.InvokeVoidAsync("jsInterops.setCookie", cookie.ToString());
                    }
                }
`#endif`

                var content = await response.Content.ReadAsStringAsync();
                resp = JsonConvert.DeserializeObject<ApiResponseDto>(content);
            }

            return resp;
        }

**Comment by enkodellc** [comment]
@krishnan2784 one of the goals I like to pursue with BB is to minimize 3rd party controls unless needed for functionality. Though I think Flurl might be a great solution for many people as of now it is something that is absolutely needed and is something that any developer wanting to implement it could do so without it being on BB. Thanks for the offer but I don't think it is quite needed. Please feel free to continue to make suggestions!
