### ISSUE TITLE
HttpClient Compilation error

### ISSUE THREAD

**Issue by cmsdesigner** [enkodellc/blazorboilerplate#362]
Hi
I forked the the BlazorBoilerplate repository to test it when compiled it i had error
'HttpClient' does not contain a definition for 'PostJsonAsync'
in french 
"Gravité	Code	Description	Projet	Fichier	Ligne	État de la suppression
Erreur	CS1061	'HttpClient' ne contient pas de définition pour 'PostJsonAsync' et aucune méthode d'extension accessible 'PostJsonAsync' acceptant un premier argument de type 'HttpClient' n'a été trouvée (une directive using ou une référence d'assembly est-elle manquante ?)	BlazorBoilerplate.CommonUI	...\BlazorBoilerplate.CommonUI\Pages\Account\Profile.razor	110	N/A"

**Comment by GioviQ** [comment]
Duplicate of #340
