### ISSUE TITLE
Login on Enter is broken (blocked by ASP bug)

### ISSUE THREAD

**Issue by Nick-W** [enkodellc/blazorboilerplate#38]
You'll need to add @bind-value:event="oninput" in order for the data binding to update to the MatTextField password element since onchange isn't triggered until focus is lost, however due to an upstream issue, this will cause a crash on Blazor 3.0, and is triaged in 3.1

More details can be found here:
https://github.com/aspnet/Blazor/issues/236
https://github.com/aspnet/AspNetCore/issues/13192
https://github.com/aspnet/AspNetCore/issues/13181

A dirty workaround would be to call a JS interop in the meantime

**Comment by enkodellc** [comment]
I just removed this for now until it is resolved. I will add a feature request issue to keep open.

**Comment by enkodellc** [comment]
Looks like wrapping Login in a form with ValidSubmit will work for the On Enter. Please test. Thanks!
