### ISSUE TITLE
Changement de droits

### ISSUE THREAD

**Issue by cedriccbcomputer** [enkodellc/blazorboilerplate#388]
Hello,
I cloned your version and I realized that it is not possible to change the rights of a user and there is an error "}" Do you have a solution?

And I have updated the packages and nothing works is normal?

At the same time I take advantage of asking you a question.
Is it possible to use Windows authentication instead of Login because very often companies want to use Windows authentication.
Thank you for your reply
Cédric
 CBCOMPUTER.FR

**Comment by enkodellc** [comment]
- If you update rights you will may need update the code to the rights you wish to change
- Updating packages WILL break things. That is the nature of code. The repo is a couple months out of date. I am too busy to maintain it at this point. You can try the "develop" branch as that is more up to date but also more complex.

- I do not know the exact answer for the Windows Auth. It most likely can be done but I have not done so. You might want to ask here:  https://gitter.im/aspnet/Blazor

**Comment by GioviQ** [comment]
It's not so complex :smile:
