### ISSUE TITLE
IS4 Branch: Serialized claims cannot be put into a Dictionary

### ISSUE THREAD

**Issue by Nick-W** [enkodellc/blazorboilerplate#39]
You cannot serialize ExposedClaims as a Dictionary, as claim types are not unique.  A drop-in fix for this is to swap List<KeyValuePair<string,string>> for Dictionary<string,string> for ExposedClaims in UserInfoDto/UserSession, and change the lambda in AccountController to:
ExposedClaims = User.Claims.Select(claim => new KeyValuePair<string,string>(claim.Type,claim.Value)).ToList()

Edit:
Since newtonsoft.json can't serialize this type properly (causes a self-referencing loop), this will need to be reworked slightly.

**Comment by enkodellc** [comment]
@Nick-W thanks for bringing this to my attention. To be honest the ExposedClaims was taken from another repo and isn't really being used yet. I updated the code per your suggestion. Please review. I am still learning Claims.

**Comment by Nick-W** [comment]
No problem! If I have some free time I'll fork this and throw you a pull request which properly fixes it.  The KVP list won't serialize to json, so while it fixes the immediate crash/breakage for the preseeded admin account, the client won't receive the claims.

**Comment by enkodellc** [comment]
@Nick-W if you don't have the time can you send me over some more details so we can close this out? Thanks!

**Comment by Nick-W** [comment]
Looks like you already fixed the Dictionary bug in an earlier commit, and I just verified that the other issues have been fixed in .NET Core, so this can be closed out.  Thanks!
