### ISSUE TITLE
[Feature] npm packages easy support

### ISSUE THREAD

**Issue by HarelM** [enkodellc/blazorboilerplate#393]
I'm still new to blazor and the whole eco-system so this might not be a "good" request.
I doubt that you can fully code in blazor without using third party javascript packages (I might be wrong).
Although some can be wrapped with a blazor nuget package, I doubt it will be done for most of the exiting packages.
Hence there's probably a need to be able to `npm install` some package and use them from C# code.
After installation and for easy deploy and usage a webpack command is probably needed too.
I think this might be a good fit for this repository.
I haven't started using it since I'm still learning and reading about blazor, but I believe this might be needed.
I would like to hear what you think about it :-)

**Comment by GioviQ** [comment]
One of the aims of Blazor is to replace javascript. Now it is impossible to replace javascript completly, but Blazor is still in an evolution phase. .NET 5 is near. The next evolution is MAUI.

My advice is: if you want to be a Blazor developer start thinking to use javascript as least as possible.

**Comment by HarelM** [comment]
While I like C# and .Net very much, and admire your enthusiasm the number of NuGet packages in Blazor is so little compared to Angular/React/Vue and just plain javascript.
It is not reasonable **at this stage** to think that you can replace all javascript code with .Net code - you'll be working on reimplementing everything that's already implemented and that's not possible for a single person and wrapping your required JS library can take time which can be used for other stuff. 
In two years time maybe this will be the case but currently it's not.
Just an example from my personal usage: mapbox-gl-js - I don't see a blazor implementation anytime soon or anything similar, so until this is wrapped in a Blazor component this needs to be pulled from npm.
I'm guessing this is not the only example, and this is just from the top of my head for my personal current needs.
I agree that this can be removed once the blazor community will implement 80-90% of the UI use cases, I don't think this is the current state, unfortunately... :-(

**Comment by GioviQ** [comment]
You're right, but this is just a Blazor boilerplate not a JavaScript boilerplate.

**Comment by HarelM** [comment]
Well... I thought about sending a pull request if I was able to properly solve this. But I guess it is not welcome.
Thanks anyway...

**Comment by GioviQ** [comment]
Sorry @HarelM ...
If you like Blazor, maybe it is bettet to put your effort to blazorize some javascript components.
This project in fact is base on https://www.matblazor.com/ and contributors are welcome :smile:
