### ISSUE TITLE
_Framework hosting

### ISSUE THREAD

**Issue by solidcloudio** [enkodellc/blazorboilerplate#399]
In my clone of this project, something has changed to where the _framework resources aren't hosted on my site.  So, Blazor fails to load because of the missing _framework resources.

I don't see where these are hosted or stored?  If I add a reference to https://www.nuget.org/packages/Microsoft.AspNetCore.Components.WebAssembly.Build/3.2.1?_src=template

It seems to work, but this shouldn't be required..   Thoughts on this?

**Comment by solidcloudio** [comment]
It works fine with a clone of the this repo...  not sure what I changed..   just trying to understand what hosts _framework ?  Where is this defined ?

**Comment by GioviQ** [comment]
It is generated during build to support wasm.

**Comment by solidcloudio** [comment]
yeah thats why I dont get that without a reference to Microsoft.AspNetCore.Components.WebAssembly.Build, my _framework isnt there...  too much "magic" going on in these .nuget packages...

**Comment by solidcloudio** [comment]
Do you know anywhere in the ASP.NET docs it talks about this _framework being hosted ?

**Comment by solidcloudio** [comment]
https://docs.microsoft.com/en-us/aspnet/core/blazor/fundamentals/additional-scenarios?view=aspnetcore-3.1
This talks about it a bit...  I'm still confused between the differences in code to run this client side vs server side..

**Comment by GioviQ** [comment]
https://blazor-boilerplate.readthedocs.io/en/latest/
