### ISSUE TITLE
Drawer close animation only works every other time

### ISSUE THREAD

**Issue by tpups** [enkodellc/blazorboilerplate#411]
The drawer close slide animation only works on every other click. On first click of 'Toggle Navigation' button, the drawer will close with no animation. Expanding the menu and closing again will close the drawer _with_ the animation. Repeating will not show the animation, and so on.

I believe the issue may be related to the classes being applied to the aside element.

_**Closed State**_

After closing with the animation, the aside has the following classes:

`mdc-drawer mat-drawer mdc-drawer--dismissible mdc-drawer--open`

However after closing with no animation, the aside has these classes:

`mdc-drawer mat-drawer mdc-drawer--dismissible`

_**Open State**_

Before closing with the animation, the aside has the following classes:

`mdc-drawer mat-drawer mdc-drawer--dismissible mdc-drawer--open mdc-drawer--animate mdc-drawer--opening`

Before closing with no animation, the aside has the these classes. These are the classes the drawer has on page load:

`mdc-drawer mat-drawer mdc-drawer--dismissible mdc-drawer--open`

I tried to repro this issue on MatBlazor's demo site and could not. It seems to be specific to this implementation.

**Comment by enkodellc** [comment]
Thanks, I did notice this but didn't want to spend more time on it, focus on other coding issues. BB has a bit more complicated that MatBlazor implementation since it has 3 steps Closed, Min, Open. MatBlazor has only Open and Closed. So somewhere in the CSS it has a glitch.  Feel free to dive into the css and sort it out. Always looking for contributors.

**Comment by tpups** [comment]
I did dig into it a bit but I can't seem to find the culprit. Something about the transitions seems to be preventing the removal of the 'mdc-drawer--open' class. I also noticed that moving the _navMenuOpened toggle below the bbDrawerClass if/else in MainLayout.razor prevents the drawer from working at all on half the clicks. The other half, the animations fire.

I've considered trying to build the drawer with https://github.com/mikoskinen/Blazor.Animate rather than straight CSS.

**Comment by enkodellc** [comment]
I have been out of the loop on Blazor.. but I thought I read there is some interesting features in the latest releases that might be beneficial. I don't know when I will be able to dive into it though. My suggestion if you REALLY need this 100% is to either switch to ON / OFF only and not MIN.  Other options are to get rid of the transitions. You could try posting to StackOverflow for some outside help. Sorry I am very swamped with client work.

**Comment by tpups** [comment]
It's nothing critical by any means. I really like the way you designed the drawer with 3 states, so I was interested in fixing the transitions. Trying to debug the issue in the boilerplate, it seemed like building a 3-state drawer on top of MatBlazor's 2-state drawer was causing some conflicts I couldn't solve.

I've built a similar drawer on top of Visual Studio's blank Blazor boilerplate. It has some nifty features like different initial states depending on device width - closed on mobile, min on tablet, full on desktop. It doesn't use Material Design (although I may add it for the menu items themselves) so it may not be a good fit for your boilerplate. In either case, I'll try to share a demo link soon!

Thanks for the resource!

**Comment by enkodellc** [comment]
Closing this as we have moved to MudBlazor.
