### ISSUE TITLE
Post-build event should check if Logs folder exists

### ISSUE THREAD

**Issue by peterthomastlc** [enkodellc/blazorboilerplate#428]
Just a minor one:-
The first build of BlazorBoilerplate.Server on a clean solution fails because the Logs folder does not yet exist.
BlazorBoilerplate.Server.csproj should be changed from
`<Exec Command="del &quot;$(ProjectDir)Logs\*.*&quot; /q" />`
to
`<Exec Command="if exist &quot;$(ProjectDir)Logs&quot; del &quot;$(ProjectDir)Logs\*.*&quot; /q" />`

**Comment by enkodellc** [comment]
@peterthomastlc  did you want to submit a PR?
