### ISSUE TITLE
Localization... error in path for publish to IIS

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#429]
Could be my fault but I was getting Localization errors when publishing / release to IIS. Had to put in a try catch  as this path is hardcoded and I am not sure if that is the correct thing to do:

   `                 foreach (var resxFile in Directory.GetFiles(@"..\..\Shared\BlazorBoilerplate.Localization", "*.resx"))
                    `

My solution was to at least catch the error then the app worked but not localization.. Will debug / communicate with @GioviQ  on this issue.

**Comment by GioviQ** [comment]
At the moment resx files are used only to init db, for publishing you have to transfer db.
I know it is not production ready like I said in https://blazor-boilerplate.readthedocs.io/en/latest/quickstarts/localization.html
and https://github.com/enkodellc/blazorboilerplate/projects/1#card-46695516

**Comment by osaaso2** [comment]
Hi Giovi and Keith,
Please add upload functionality using MatIpload for things like this, at least in the admin settings section.
Best

**Comment by GioviQ** [comment]
@osaaso2 I am migrating resx to PO files for translations, so I will add an "Import" in admin section.

**Comment by osaaso2** [comment]
That's Great, Thanks!

**Comment by osaaso2** [comment]
and plz for email templates too

**Comment by GioviQ** [comment]
@osaaso2 in development branch I am completing the new localization with PO files import and export.
Can you test email templates?

PO files are a common format for translators. See https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html

**Comment by osaaso2** [comment]
Thanks Gioviani, sure I will, though I have been using master branch so far.

**Comment by osaaso2** [comment]
Localization works fine, good job! But I don't know what to do for checking email template. Please let me know how can I find out, have you removed those template files and associated codes? and replaced by API?
Cheers

**Comment by GioviQ** [comment]
The templates are initialized in db with https://github.com/enkodellc/blazorboilerplate/blob/development/src/Server/BlazorBoilerplate.Server/Localization/en-US/EmailFactory.po

The templates are now common translated strings used in https://github.com/enkodellc/blazorboilerplate/blob/development/src/Server/BlazorBoilerplate.Server/Factories/EmailFactory.cs

Soon I will release plural management and merge with master.

**Comment by osaaso2** [comment]
Great! 
Any plan/idea regarding .net 5?
Best

**Comment by GioviQ** [comment]
I'm waiting the final release in November to upgrade.

**Comment by osaaso2** [comment]
Good News, Thanks!

**Comment by GioviQ** [comment]
Fix in with last merge
