### ISSUE TITLE
Sliding Nav Shelf animation a little glitchy

### ISSUE THREAD

**Issue by JeroMiya** [enkodellc/blazorboilerplate#43]
The animation that plays when the side-bar navigation slides in and out or transitions is sometimes a little bit glitchy. I think the text elements jump to the left before sliding and fading out to the right, and there are text-wrapping issues as the drawer width animates.

Also, when in auto-hide mode, the expand/collapse arrow shifts down after the drawer slides out:

![image](https://user-images.githubusercontent.com/320332/65248222-d2196880-dabf-11e9-968f-6cd212f831b8.png)

Where it normally looks like this:
![image](https://user-images.githubusercontent.com/320332/65248356-0bea6f00-dac0-11e9-99f9-428b84290a37.png)

**Comment by enkodellc** [comment]
@JeroMiya  Thanks for the issue / feedback. Yes it is not perfect. I spent several hours to get it where I was at least happy with a release. I am currently swamped with several other features. If you like please review the CSS transitions and padding and submit a PR to fix the issue. We need more contributors to help make BlazorBoilerplate a great platform.
