### ISSUE TITLE
[Question] Reducing WebAssembly install size/time

### ISSUE THREAD

**Issue by GFoley83** [enkodellc/blazorboilerplate#431]
General question to see what, if anything, can be done currently to reduce the amount of DLLs that need to be downloaded for a fresh load of the Blazor Boilerplate size?

Currently the size downloads 36.6MB, which is quite a lot; especially if you are on mobile w/ 4G.

![image](https://user-images.githubusercontent.com/838788/96660704-c5dc9a80-13a6-11eb-85ed-f2935060635f.png)

**Comment by GioviQ** [comment]
With .NET 5 we all look forward to performance improvements.

The issue is not specific to this repository, please see https://github.com/dotnet/aspnetcore/projects/12

**Comment by GFoley83** [comment]
I get you're eager to close this off but given the default Blazor WebAssembly project is currently half the size of this project, so this is obviously something that the .NET 5 improvements won't be able to address:

![image](https://user-images.githubusercontent.com/838788/96777315-ad23c180-1446-11eb-9572-be4b691f18d0.png)

**Comment by GioviQ** [comment]
The default Blazor WebAssembly Project does nothing...

The screenshot does not focus the real workload... i.e. wasm libraries

In a production application you add more  and more dll, you cannot compare with that basic project. You can try to upgrade this repository to .NET 5 rc and see the difference.

In the meanwhile you can use blazor server mode. No wasm to download.

**Comment by GFoley83** [comment]
Yep I take your point there but even for a production app, downloading 36MB for a fresh install in a hell of a lot and I doubt that .NET 5 will fix all that; it's more the amount of dependencies in this project. My initial question was around if there's any recommendations or plans around reducing that, beyond waiting to see what .NET 5 does. 

No interest in Blazor server side as using SignalR for DOM events is a terrible idea IMO.

**Comment by GioviQ** [comment]
I know download size is an issue. In fact at the moment I prefer Blazor Server mode. SignalR for DOM changes is amaizing to me.

I hope you can contribute to suggest ways to improve Blazor Boilerplate.
