### ISSUE TITLE
The README file in this repo has some bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [enkodellc/blazorboilerplate#436]
The markup version of the readme that is displayed for the main page in this repo contains the following links:
Status code [404:NotFound] - Link: https://github.com/enkodellc/blazorboilerplate/blob/master/support@blazorboilerplate.com
Status code [404:NotFound] - Link: https://github.com/enkodellc/blazorboilerplate/blob/master/oneparameter
(The link in the readme’s raw markdown may appear in a different format to the link above)

Theses bad links were found by a tool I very recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback.

**Comment by GioviQ** [comment]
I don't understand where those llinks are...

**Comment by GioviQ** [comment]
It is the first fake issue I see bot genereted: look at https://github.com/search?q=The+README+file+in+this+repo+has+some+bad+links&type=issues

**Comment by MrCull** [comment]
Hi @GioviQ 
Thank you for the feedback.
As descried in the initial Issue report this tool is not a bot and the Issue was manually logged after the links have been verified as being broken.
The tool checks the markup and I manually verify these links are broken in the markup.
It is usually down to a person who maintains the repo to find these in the markdown.

It would be really neat if the tool could identify the exact lines of code in the raw markdown, but unfortunately this feature may be some way off.

For now for these issues I've taken some screenshots to help you find these broken links.
Hope this helps

![image](https://user-images.githubusercontent.com/16634034/98437777-f299ed00-20dc-11eb-84a2-428a76899f4e.png)

![image](https://user-images.githubusercontent.com/16634034/98437785-03e2f980-20dd-11eb-841f-5d98fb660997.png)

**Comment by GioviQ** [comment]
@MrCull so you have a lot of time to do manually all these issues https://github.com/search?q=The+README+file+in+this+repo+has+some+bad+links&type=issues almost identical

I don't think... 

I think you are smart and you created a bot.

**Comment by MrCull** [comment]
Hi @GioviQ,
I can assure you I have taken the time too create all of those Issues manually to try and help people.
Most of the feedback I have received has been very rewarding and justified the significant time I have spent on this so far.
