### ISSUE TITLE
Navigation links don't auto-activate based on current URL

### ISSUE THREAD

**Issue by JeroMiya** [enkodellc/blazorboilerplate#44]
Not sure if this is a blazorboilerplate issue or a matblazor issue, but I noticed that the navigation items in the drawer menu don't automatically become "active" when the URL changes, or on initial load/reload. They only change to the active state when you click on them. This means the active state of nav links are out of sync initially, and also if you navigate away from a link outside the drawer.

Would be nice if they worked like the built-in NavLink component and do URL path matching for active/inactive state.

**Comment by enkodellc** [comment]
@JeroMiya I agree this would be a nice feature. This is a MatBlazor / Navmenu issue but not addressed yet. I built the NavMenu for MatBlazor and I didn't have the time to dive into that feature. Mostly as the Blazor Router is still very rough. Please post this as a MatBlazor issue.
