### ISSUE TITLE
Failed to build the latest version

### ISSUE THREAD

**Issue by goldmannyc** [enkodellc/blazorboilerplate#449]
Error	CS1061	'Todo' does not contain a definition for 'CreatedBy' and no accessible extension method 'CreatedBy' accepting a first argument of type 'Todo' could be found (are you missing a using directive or an assembly reference?)	BlazorBoilerplate.Server	\blazorboilerplate\src\Server\BlazorBoilerplate.Server\Controllers\ApplicationController.cs

**Comment by osaaso3** [comment]
Happened to too, when updated my MS VS 2019 Community to 16.8. When commented/removed that method, worked fine.
Need to be fixed...

**Comment by GioviQ** [comment]
I merged now development to master where I updated Source Generator for VS 16.8.1
