### ISSUE TITLE
Login function doesn't work

### ISSUE THREAD

**Issue by Discovery-support** [enkodellc/blazorboilerplate#46]
If you try to login using user 'user' with password 'user123', it gives an error saying you are not authorised

**Comment by enkodellc** [comment]
- Where are you testing from? You local machine? Online Demo?
- The online demo app could easily be changed by anyone online so create your own and test.
- Did you try creating your own user and logging in?
- Are your sure your ConnectionString is correct?

**Comment by leonibr** [comment]
I had a similar problem, cleaning the browser cookies did the magic
