### ISSUE TITLE
Localization broken in Server Side?

### ISSUE THREAD

**Issue by UrizielTSD** [enkodellc/blazorboilerplate#460]
Hey,

I tried to ask this in gitter but I didnt receive a reply there.
I setup the repo in my visual studio, and it worked great.

Just when using Server Side all text look like this:
![image](https://user-images.githubusercontent.com/27346238/100429570-cd721c00-3095-11eb-9779-af07abfd6168.png)

While in Web Assembly it looks fine:
![image](https://user-images.githubusercontent.com/27346238/100429629-e11d8280-3095-11eb-82cc-cf681f8f3e43.png)

Any ideas?
Thanks

**Comment by GioviQ** [comment]
I do not see your message here https://gitter.im/blazorboilerplate/community

**Comment by GioviQ** [comment]
I cannot reproduce your issue.

Is your code in sync with commits of yesterday?

**Comment by UrizielTSD** [comment]
Hey,

I realized that I joined the general Blazor Gitter and not the boilerplate one. 

I did download the code yesterday evening. The only changes I made was to introduce MySQL as DB provider for the Entity Framwork.

**Comment by GioviQ** [comment]
MySql is not tested.

Look in logs for errors.

**Comment by UrizielTSD** [comment]
@GioviQ As I wrote in my Edit, I just redownloaded the code as Zip opened VS, made 0 changes and it happened again.

This is the Vanilla code without MySQL which produces the same result.

FYI supporting MySql only requires 3 changes. And works fine in my other version.

**Comment by UrizielTSD** [comment]
@GioviQ If you would be so kind and tell me where I can find the logs which would log those kind of errors.
All logs in the Db are empty and the debug output has no error listed.

**Comment by GioviQ** [comment]
Running from Visual Studio 16.8 you'll find log folder under https://github.com/enkodellc/blazorboilerplate/tree/master/src/Server/BlazorBoilerplate.Server

**Comment by UrizielTSD** [comment]
@GioviQ Thank you for the direction.

I found the problem, for anyone interested in using BlazorBoilerplate with MySQL.
It wont be possible without rewriting/adjusting an unknown amount of code.
Making MySQL work is easy, but the major problem is that MySQL doesnt support MARS which this project uses.

Personally I dont know how to resolve that, and will use SQL Server for the time being.
