### ISSUE TITLE
Missing CLR Entity Type

### ISSUE THREAD

**Issue by UrizielTSD** [enkodellc/blazorboilerplate#462]
Hey,

I started implementing my own Model, I added the Dto objects too.
But whenever I execute the app, i receive the following error with each Entity model I created. Even tho they arent used yet:

Error: System.Exception: Unable to locate metadata resource for: http://localhost:53414/api/data/
 ---> System.Exception: Metadata errors encountered: 
Metadata mismatch classification: 'Missing CLR Entity Type' - for StructuralType: 'ControlState:#BlazorBoilerplate.Infrastructure.Storage.DataModels'.  
Metadata mismatch classification: 'Missing CLR Entity Type' - for StructuralType: 'Device:#BlazorBoilerplate.Infrastructure.Storage.DataModels'.  
Metadata mismatch classification: 'Missing CLR Entity Type' - for StructuralType: 'DeviceGroup:#BlazorBoilerplate.Infrastructure.Storage.DataModels'.  
Metadata mismatch classification: 'Missing CLR Entity Type' - for StructuralType: 'DeviceState:#BlazorBoilerplate.Infrastructure.Storage.DataModels'.  
Metadata mismatch classification: 'Missing CLR Entity Type' - for StructuralType: 'DeviceType:#BlazorBoilerplate.Infrastructure.Storage.DataModels'.  
Metadata mismatch classification: 'Missing CLR Entity Type' - for StructuralType: 'DeviceXRuntypeProfile:#BlazorBoilerplate.Infrastructure.Storage.DataModels'. 

Any idea what am I missing here?
Thank you

**Comment by GioviQ** [comment]
You have manually to create DTO in https://github.com/enkodellc/blazorboilerplate/tree/master/src/Shared/BlazorBoilerplate.Shared/Dto/Db

or run https://github.com/enkodellc/blazorboilerplate/tree/master/src/Utils/BlazorBoilerplate.EntityGenerator

**Comment by UrizielTSD** [comment]
Thats an absolute fantastic helper!

I used the generator to auto re-create my Dtos, now it works

**Comment by enkodellc** [comment]
This also can happen if you add Models with new Namespaces.  The SourceGenerator default namespace is 
BlazorBoilerplate.Infrastructure.Storage.DataModels. Like Gio said if it is not in that namespace you will have to create your own DTO, or possibly update the SourceGenerator to handle the updated namespaces.
