### ISSUE TITLE
Doc Localization outdated

### ISSUE THREAD

**Issue by UrizielTSD** [enkodellc/blazorboilerplate#463]
Hello,

in the online Docs the Localization chapter seems outdated. Several links lead to 404 pages.
And as far as i can see resx files arent used but .po files for the localization.

Is there a tool to manage those files, or only text editor to edit/add new entries?
And to update the Db with new entries, whats the best way? ATM i delete the old one and let it be reinstalled.

Regards

**Comment by GioviQ** [comment]
I know https://blazor-boilerplate.readthedocs.io/en/latest/quickstarts/localization.html is obsolete, but I am busy now.

https://poedit.net/
http://www.eazypo.ca/

And in admin section you can manage translations.
