### ISSUE TITLE
Controller Endpoint Protection

### ISSUE THREAD

**Issue by NPadrutt** [enkodellc/blazorboilerplate#47]
So far you can login, but all controller are open for anonymous request. Some have the Authorize Attribute on it but are overwritte by the AllowAnonymous from the controller itself. So I can always request for example all users via PostMan.
As soon as I take out the one from the controller so that the the one from the endpoint comes into effect I always get an 401 Unautherized back.

I'm not sure if that is a bug or something that was not fully implemented :)

**Comment by enkodellc** [comment]
This is a known / undocumented issue with IS4 version.  The main contributor ganmuru is working on a refactor of the IS4 now but not sure when that is to be completed. I am new to IS4 so I was going to spend my time doing other projects and let him handle the refactor.

**Comment by NPadrutt** [comment]
oh, I see. Maybe a stupid question, but why Identity Server at all and not just the asp.net identity system? There is a blazor project using just that: https://github.com/stavroskasidis/BlazorWithIdentity withing a short look seems to work as expected and to be a bit simpler. Is there something missing featurewise?

**Comment by enkodellc** [comment]
If you read the read me you will see Ver 0.2.3 is all asp.net Identity so if that is the route you wish to take then download that.  I have been reading good things on IS4 so I thought I would try it out. If you have another opinion and or experience with both please let me know.

**Comment by enkodellc** [comment]
@NPadrutt  do you use gitter?  https://gitter.im/NPadrutt  Let's chat there if you do.

**Comment by enkodellc** [comment]
Also, my project was originally based off of https://github.com/stavroskasidis/BlazorWithIdentity  that is mentioned on home page of Blazor boilerplate
