### ISSUE TITLE
There is already an open DataReader associated with this Connection which must be closed first.

### ISSUE THREAD

**Issue by ema2ooo** [enkodellc/blazorboilerplate#473]
Hello

i've deployed the application to azure and getting the below error , i'm using sql server , i've added ;MultipleActiveResultSets=true to the connection string but no luck 

An exception occurred while iterating over the results of a query for context type 'BlazorBoilerplate.Storage.LocalizationDbContext'.
System.InvalidOperationException: There is already an open DataReader associated with this Connection which must be closed first.

Regards.

**Comment by GioviQ** [comment]
It seems that MultipleActiveResultSets=true is not set.

I cannot test Azure behavoiur, can you try to restart web app?

**Comment by GioviQ** [comment]
Anyway it is not related to this project

Look at https://stackoverflow.com/questions/12690453/sql-azure-getting-an-error-there-is-already-an-open-datareader-associated-wit

**Comment by ema2ooo** [comment]
> It seems that MultipleActiveResultSets=true is not set.
> 
> I cannot test Azure behaviour, can you try to restart web app?

yes , restarted the app , i programmatically added the connection string and now works , but i've updated the connection string all places but still having the issue 
anyway will work with the temp solution till i figure out the issue , Thank you .
