### ISSUE TITLE
Can read, cannot Write Entities with Breeze.Sharp

### ISSUE THREAD

**Issue by Stephen250** [enkodellc/blazorboilerplate#474]
Hello @GioviQ,

Within the past few days I have started to encounter the follow error when changing Translations in the UI:

Message:

- Method not found: 'Microsoft.EntityFrameworkCore.Metadata.INavigation Microsoft.EntityFrameworkCore.ChangeTracking.NavigationEntry.get_Metadata()'.

StackTrace: 

   at Breeze.Persistence.EFCore.EFPersistenceManager`1.<>c.<MarkEntryAndOwnedChildren>b__32_0(NavigationEntry n)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at Breeze.Persistence.EFCore.EFPersistenceManager`1.MarkEntryAndOwnedChildren(EntityEntry entry, EntityState state)
   at Breeze.Persistence.EFCore.EFPersistenceManager`1.HandleModified(EFEntityInfo entityInfo)
   at Breeze.Persistence.EFCore.EFPersistenceManager`1.ProcessEntity(EFEntityInfo entityInfo)
   at Breeze.Persistence.EFCore.EFPersistenceManager`1.ProcessSaves(Dictionary`2 saveMap)
   at Breeze.Persistence.EFCore.EFPersistenceManager`1.SaveChangesCore(SaveWorkState saveWorkState)
   at Breeze.Persistence.PersistenceManager.OpenAndSave(SaveWorkState saveWorkState)
   at Breeze.Persistence.PersistenceManager.SaveChanges(JObject saveBundle, TransactionSettings transactionSettings)
   at TPG_Insights.Server.Controllers.LocalizationController.__a$_around_SaveChanges_100663619_o(JObject saveBundle) in C:\git\Cobalt3\Server\TPG_Insights.Server\Controllers\LocalizationController.cs:line 123

Any thoughts as to what could be causing it? Any help would be greatly appreciated as I am still learning Breeze.Sharp.

**Comment by GioviQ** [comment]
You updated EF Core to v.5.
Look at https://github.com/Breeze/breeze.server.net/issues/102

**Comment by Stephen250** [comment]
@GioviQ, okay that makes sense, is this something that you will be looking at or switching out for a different module at some-point?

As I would imagine others would be in the same boat.

**Comment by GioviQ** [comment]
At the moment I do not need EF Core 5. If you do not have special need, revert to previous version or fix Breeze.Server yourself.

**Comment by osaaso3** [comment]
Hi Giovi,
I don't know if I am posting this issue to the right place or not, but I am not able to edit roles after online deployment.
I can create a new role but cannot update it later. 
Cheers,
Ahmad

**Comment by GioviQ** [comment]
Can you post the error in your log file?

**Comment by osaaso1** [comment]
![image](https://user-images.githubusercontent.com/62982900/106945364-f02b4b80-673c-11eb-9d0a-1a296eeeca40.png)
No relevant error is added to DbLog viewer if you mean that.
only this, when deployed: 
2021-02-04 22:43:32.303 +03:30 [WRN] No XML encryptor configured. Key {5dd3e942-4e83-4407-b0a7-048f036009ad} may be persisted to storage in unencrypted form.

**Comment by GioviQ** [comment]
I see in the top left corner, that the user is not admin, so I suspect you do not have permission to update the role.
Look at https://github.com/enkodellc/blazorboilerplate/blob/master/src/Server/BlazorBoilerplate.Server/Controllers/AdminController.cs#L66

**Comment by osaaso1** [comment]
Thanks Giovi, but that user is admin (with administrator role and access to the database). Do you mean that admin name has to be Admin, otherwise doesn't work?

**Comment by osaaso1** [comment]
I made a user named Admin with Administrator role, still got that error when tried to update User role.
Does it need to be the database user too?
Best

**Comment by GioviQ** [comment]
Consider also that in https://blazor-server.quarella.net/ I cannot reproduce the error.

**Comment by osaaso1** [comment]
You're right it works in https://blazor-server.quarella.net/.
Perhaps your username for the database is "admin" too.
Do you think changing the code that checks the policies would be a good idea, or the database username needs to be changed to admin? 
Take Care

**Comment by GioviQ** [comment]
The user in the db connection string must be able to manage all db tables.

I suggest trying with a new repository clone without your customization, but with your current connection string.

**Comment by osaaso3** [comment]
Hi Giovi,
A fresh clone didn't work either. My db user may have restricted access. I will ask the provider.
Thank

**Comment by osaaso3** [comment]
Giovi, Just to let you know that I came up with a solution that might be useful to those with the mentioned problem. I first changed default user and role names to another name inside related codes. Then created a User role online. Finally changed the codes to their original and deployed them again. Now I have a User role with customized permissions!
Take Care

**Comment by GioviQ** [comment]
@osaaso3 I still do not understand your issue, because I cannot reproduce it.

**Comment by osaaso2** [comment]
As you said it might be due to my database restrictions. Not a problem with BBP.
Thanks

**Comment by enkodellc** [comment]
@charlierlee If you are interested in contributing more to Open Source and have time maybe you want to look at creating a .Net 5 PR for Breeze:  https://github.com/Breeze/breeze.server.net/issues/103   Then it would not only help out anybody using BB but also anybody using Breeze.Server.Net.
