### ISSUE TITLE
NullReferenceException on return GetValue

### ISSUE THREAD

**Issue by kyotr** [enkodellc/blazorboilerplate#481]
Hello,

i am not able to integrate Syncfusion datagrid , I am getting a NullReferenceException on return GetValue when i hit Edit or Update

I managed to make it somehow  work by removing all `GetValue `and `SetValue`
  ```
 public partial class Todo : BaseEntity, ITodo
public Int64 Id
        {
            get { **return GetValue<Int64>();** }
            set { SetValue(value); }
        }
```
To

```
 public partial class Todo : BaseEntity, ITodo
    {
        public Int64 Id  { get; set; }

```

I am not getting errors but datagrid have empty items and i dont think that it is the right way for fixing this issue

Many Thanks

**Comment by GioviQ** [comment]
Your changes are not valid. See https://blazor-boilerplate.readthedocs.io/en/latest/quickstarts/breeze_sharp_with_blazor.html
There are other errors in your code and I cannot support Syncfusion integration. Sorry.
