### ISSUE TITLE
Issue publishing in test production

### ISSUE THREAD

**Issue by agorota** [enkodellc/blazorboilerplate#498]
I am testing this project in a development environment and it seems very complete to me.

I am carrying out some publication tests in a simulation environment but I encounter difficulties, certainly some of my technical deficiencies ...
The project I'm going to publish is by default without any changes to the code, the latest version downloadable from GitHub.

I followed the 4 steps indicated in the publication instructions step by step
application on IIS and SQL, with Let's Encrypt certification

Application configured at this URL:
**https://app.[mydomain].it**

I renamed the **appsettings.developement.json** file in the ISS to **appsettings.production.json** and changed it as follows

**{
  "BlazorBoilerplate": {
    "ApplicationUrl": "https://app.[Mydomain].it",
    "IS4ApplicationUrl": "https://app.[Mydomain].it",
    "DetailedErrors": "true"
  },
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug"
    }
  }
}**

when the application starts, the database is successfully created in SQL
but I don't get the rendering of the application in the browser.
I just get the classic Blazor message:
**"An error has occurred. This application may no longer respond until reloaded. Reload"**
Looking at the logs it seems that the system is unable to match my url and the "Tenant"

If it can be useful to send logs, tell me what you need ...

Thank you

**Comment by charlierlee** [comment]
Do you get any console errors in the browser?

**Comment by agorota** [comment]
No,  blank page!
Only popup "An error has occurred. This application may no longer respond until reloaded. Reload"

**Comment by charlierlee** [comment]
Did any javascript components get loaded, or attempt to download?

**Comment by agorota** [comment]
How do i check it?

**Comment by charlierlee** [comment]
In the developer tools. Next to the console tab, there is a source or debugger tab. First check the console for console errors.

**Comment by agorota** [comment]
![immagine](https://user-images.githubusercontent.com/30776363/107558126-b645c380-6bda-11eb-885d-b3c850033bd9.png)

**Comment by charlierlee** [comment]
Check the readme.md file. The section starting with: In ASPNETCORE_ENVIRONMENT=Production: http will redirect to https. If you are using a self signed/invalid ssl certificate the following will occur:

**Comment by charlierlee** [comment]
I found this: https://github.com/dotnet/aspnetcore/issues/10475

"As I was writing above, I found out what the issue was. I followed signalr documentation: https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.0&tabs=visual-studio and I used incorrect url for HubConnectionBuilder. Previous version of Signalr didn't need to specify domain just the /hub."

**Comment by agorota** [comment]
> 
> 
> Check the readme.md file. The section starting with: In ASPNETCORE_ENVIRONMENT=Production: http will redirect to https. If you are using a self signed/invalid ssl certificate the following will occur:

I can't find the paragraph "ASPNETCORE_ENVIRONMENT = Production"
in readme.md, are you sure?

**Comment by agorota** [comment]
> 
> 
> I found this: [dotnet/aspnetcore#10475](https://github.com/dotnet/aspnetcore/issues/10475)
> 
> "As I was writing above, I found out what the issue was. I followed signalr documentation: https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-3.0&tabs=visual-studio and I used incorrect url for HubConnectionBuilder. Previous version of Signalr didn't need to specify domain just the /hub."

it's for my issue?

**Comment by charlierlee** [comment]
try changing this
"ApplicationUrl": "https://app.[Mydomain].it",
"IS4ApplicationUrl": "https://app.[Mydomain].it",
to this:
"ApplicationUrl": "https://app.[Mydomain].it/",
"IS4ApplicationUrl": "https://app.[Mydomain].it/",

**Comment by agorota** [comment]
don't work...

**Comment by charlierlee** [comment]
Same error?

**Comment by agorota** [comment]
> 
> 
> Same error?

Yes

**Comment by GioviQ** [comment]
You need to check the log file.

**Comment by agorota** [comment]
[log-20210210_001.log](https://github.com/enkodellc/blazorboilerplate/files/5961208/log-20210210_001.log)
[log-warning-20210210_001.log](https://github.com/enkodellc/blazorboilerplate/files/5961211/log-warning-20210210_001.log)

**Comment by charlierlee** [comment]
Can you back up/delete your log and start your log from scratch, generate the error, and then post it?

**Comment by GioviQ** [comment]
Check the connection string, because you changed MultipleActiveResultSets=true

**Comment by agorota** [comment]
> MultipleActiveResultSets=true

with this: 
HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit

**Comment by agorota** [comment]
[log-20210210_003.log](https://github.com/enkodellc/blazorboilerplate/files/5961353/log-20210210_003.log)

**Comment by charlierlee** [comment]
If the database is not important, maybe you could delete the db. Then boot up the server again. See if that fixes it. Keep a log of the process and resubmit the log.

**Comment by agorota** [comment]
> 
> 
> If the database is not important, maybe you could delete the db. Then boot up the server again. See if that fixes it. Keep a log of the process and resubmit the log.

[log-20210210.log](https://github.com/enkodellc/blazorboilerplate/files/5961475/log-20210210.log)


same error

**Comment by agorota** [comment]
I'm sorry to trouble you. This is most likely a problem with my server. In the next few days I will prepare a new virtual machine and I will try to redo everything ... Let's hope so!

Thanks everyone for the moment, if you can think of something let me know!

Thanks for your work ..

**Comment by charlierlee** [comment]
It looks like a problem with the SupportedCultures. Is yours setup for: en-US?
The code failed on line 32 of LocalizationProvider.cs
var pluralFormRule = pluralFormRules.SingleOrDefault(i => i.Language == culture);
Specifically the SingleOrDefault. The culture was not found in the database.

**Comment by GioviQ** [comment]
The IMPORTANT error is there is already an open DataReader associated with this Connection which must be closed first.

This is cause by MultipleActiveResultSets=false (ricontrolla anche le stringhe di connessione in tutti i json che hai pubblicato)

**Comment by charlierlee** [comment]
Would it be ok that we enforce this setting somewhere?

**Comment by GioviQ** [comment]
> Would it be ok that we enforce this setting somewhere?

what do you propose?

**Comment by charlierlee** [comment]
Just prior to loading the sql connection string. The simplest thing to do is throw an Exception with a message stating MultipleActiveResultSets was set to fault and must be set to true.
if (useSqlServer)
                //parse connection string and look for MultipleActiveResultSets. enforce the setting here. Throw an exception if not correct
                builder.UseSqlServer(configuration.GetConnectionString("DefaultConnection"), options =>
                {
                    options.CommandTimeout(60);
                    options.MigrationsAssembly(migrationsAssembly);
                });

**Comment by agorota** [comment]
> 
> 
> It looks like a problem with the SupportedCultures. Is yours setup for: en-US?
> The code failed on line 32 of LocalizationProvider.cs
> var pluralFormRule = pluralFormRules.SingleOrDefault(i => i.Language == culture);
> Specifically the SingleOrDefault. The culture was not found in the database.

Windows server 2016 + iis + SQL Express 2014 in Italian

**Comment by agorota** [comment]
> 
> 
> The IMPORTANT error is there is already an open DataReader associated with this Connection which must be closed first.
> 
> This is cause by MultipleActiveResultSets=false (ricontrolla anche le stringhe di connessione in tutti i json che hai pubblicato)

Ho solo la connessione al database di boilerplate, non ho nessun altra connessione. Ho il vostro progetto di default senza modifiche solo per verificarlo lato produzione. Sto preparando un nuova VM con Server 2019 + IIS +SQL 2019 spero di risolvere con questo. Comunque mettendo in stringa di connessione MultipleActiveResultSets=true sembra peggiorare il problema. Comunque se le Vostre specifiche lo richiedono lo manterrò. Di fatti sul mio ambiente di sviluppo è  impostato ed è tutto ok.

Appena ho risolto aggiorno il caso. 
Grazie

**Comment by charlierlee** [comment]
> > It looks like a problem with the SupportedCultures. Is yours setup for: en-US?
> > The code failed on line 32 of LocalizationProvider.cs
> > var pluralFormRule = pluralFormRules.SingleOrDefault(i => i.Language == culture);
> > Specifically the SingleOrDefault. The culture was not found in the database.
> 
> Windows server 2016 + iis + SQL Express 2014 in Italian

RE: SingleOrDefault(). I can make this FirstOrDefault() if that helps. I'd have to do some research first to find out how another culture could make it in as a parameter that is outside of what is in the db.

**Comment by GioviQ** [comment]
@agorota  with new commits we (I and @charlierlee) made MultipleActiveResultSets=true mandatory.
So with the correct connection string it is better to delete the db for a fresh start.
@charlierlee the culture was not found because the incorrect connection string compromised the db init from PO files.

**Comment by GioviQ** [comment]
@agorota remember also to enable websockets in IIS.

**Comment by agorota** [comment]
> enable websockets in IIS
> 
> 
> @agorota remember also to enable websockets in IIS.

I solved it by adding the WebSocket role to Windows server 2019 as suggested by @GioviQ:

- On the Add Roles and Features Wizard, select Server Roles.
- In the Roles pane, under Web Server> Application Development, select WebSocket Protocol.

I suggest to add the indication in the readme.me in the paragraph on the publication of IIS
