### ISSUE TITLE
CascadingAuthenticationState/Policies/Claims

### ISSUE THREAD

**Issue by nstohler** [enkodellc/blazorboilerplate#5]
Hi

I tried to add `CascadingAuthenticationState` into blazorboilerplate, using the following sources:

- https://gist.github.com/SteveSandersonMS/175a08dcdccb384a52ba760122cd2eda
- https://github.com/dotnet-presentations/blazor-workshop/blob/master/docs/06-authentication-and-authorization.md

Since I've run into some problems merging it back into a fork of your current project, I've created a copy here for now:

https://github.com/nstohler/blazorboilerplateCopy

I also played around with policies/claims. 

It's not very clean so far, but compiling and working. 

Maybe something to integrate into the project at some point...

**Comment by enkodellc** [comment]
@nstohler Great thanks I will take a look. I have reviewed those repos before and definitely wanted to integrate something to that effect. Though I was hoping Microsoft would have included some built in mechanisms in the last preview. I might not get to this today but this weekend definitely.

**Comment by enkodellc** [comment]
I pushed most of your code with some minor changes to repo to try and clean it up but there still is more work in this area to be done. If you want setup a UI page to test out the API calls with Toasts showing the results. Thanks again for the suggestion and repo referral.   At some point in the near future I want to get a UI to control Roles / Policies / Claims for users in an admin dashboard.

**Comment by nstohler** [comment]
Thanks, it's looking great so far. 

I've since forked your repo and worked on migrating my server side code from ASP.NET Core 2.2 into the BlazorBoilerplate.Server. All the changes I made so far are under the branch `iis-test` so far:

https://github.com/nstohler/blazorboilerplate/tree/iis-tests

Whats in there:
- fixed the project so it references `MatBlazor.dll` in the repo
- added `appsettings.Production.json` support + code to load it (otherwise it did not run on my IIS server)
- added `Autofac` IoC container. I know ASP.NET Core has its own DI system, but I have used Autofac extensively in the past and like how it can scan and register all the project assemblies. Maybe there's an option to do the same using ASP.NET Core that offers the same features I am getting from Autofac...
- added `AutoMapper`
- added a `BlazorBoilerplate.Startup` project that takes care of scanning assemblies for Autofac/AutoMapper registration
- added `LibLog` (into project `Core.LibLog`) that works nicely together with `Serilog`.
- Refactored Program.Main 
  - added entry point for data seeder
    - seeding (new) country table from json file 
    - seeding user roles from here instead of authorize controller action

There's still quite a lot of code that could be improved or refactored (or just cleaned up). I'll work some more on that now and push it into the same branch. 

I'm aware that most of the above changes might be very specific to my coding and project structure preferences. I usually split up my solution into many small projects (rather than one big project that handles everything and is split into many folders). This forces me to minimize dependencies (and I can make my service classes internal and only have public interfaces, and then Autofac does the rest).

**Comment by enkodellc** [comment]
@nstohler  another gentleman wants to help with the server side Users / Roles / Authentication.  He has referenced: https://github.com/emonney/QuickApp  and I have used this code in the past for a demo.  Can we together start a discussion on this on https://gitter.im/blazorboilerplate/community . 

Yes I agree some of the changes are quite specific. I think a few of the items would be a good addition.  I really want to get a UI / backend for added Users / Roles / Claims / Policies in place. As well as CRUD for a generic example. I feel these are crucial for others to utilize. Thanks for keeping me in the loop
