### ISSUE TITLE
Add external webapi

### ISSUE THREAD

**Issue by agorota** [enkodellc/blazorboilerplate#517]
Hi,
I developed an ASP.NET Core Web Api with Entity Framework Core to manage my database. Various clients and Windows services that load data and finally a Blazor application to manage everything but I am not satisfied with the latter.
I would like to replace my Blazor Web App with your BlazorBoilerplate project to make the leap in quality while maintaining my Web APIs and taking full advantage of the functionality of your system.
Is it possible to add access to another Web Api other than the native one to the BlazorBoilerPlate?
Also I would like to touch as little as possible about the BlazorBoilerPlate project so that I can easily apply the next developments of the same.
Analyzing the system I noticed in the admin section: IdentityServer4 with API Resource, here could I add references to my WebApi? The concept is not very clear to me ...
Could you tell me if I am on the right track for what I would like to do?
Do you have any guidelines for applying this?
Thanks for any information ...

**Comment by GioviQ** [comment]
You need Identity Server only if you need to protect Api with OpenId Connect. To call your Api you don't need this.
Just create an ApiClient calling your own Api.

**Comment by mobinseven** [comment]
@agorota [This repo](https://github.com/cradle77/BlazorSecurityDemo) and the related article might help. Applicable on BB or any other IS4 project.
