### ISSUE TITLE
Does not compile on first install - error with Todo.CreatedBy

### ISSUE THREAD

**Issue by jeanpoulin** [enkodellc/blazorboilerplate#526]
Just installed from Gihub & it failed to build with error  on line 71 of ApplicationControler.cs   error= 'Todo' does not contain a definition for 'CreatedBy' and no accessible extension method 'CreatedBy' accepting a first argument of type 'Todo' could be found (are you missing a using directive or an assembly reference?)	BlazorBoilerplate.Server	...\src\Server\BlazorBoilerplate.Server\Controllers\ApplicationController.cs Line 71

ps: I also had 2 errors as Docker was not installed on this station but after I innstalled it the errors are gone.

**Comment by GioviQ** [comment]
You have to use last version of Visual Studio.
Rebuild all so https://github.com/enkodellc/blazorboilerplate/blob/master/src/Utils/BlazorBoilerplate.SourceGenerator/AuditableGenerator.cs takes effect.
