### ISSUE TITLE
named pipes provider / created in shadow state

### ISSUE THREAD

**Issue by wvmstr** [enkodellc/blazorboilerplate#54]
I have a fully functional dev environment with connection to SQL Server Express, TCP/IP enabled an open port, allowed remote access etc, i.e. all the checks done to prevent error 40, yet:

The server was not found or was not accessible / Named pipes provider, error 40
and
'0.3.2.0perty '{property}' on entity type '{entityType}' was created in shadow state because there are no eligible CLR members with a matc'

databaseInitializer. SeedAsync().Wait() is where it fails.

I have both created the db (blazor_boilerplate) as well as left it up to the application, same result.

**Comment by enkodellc** [comment]
From what you have written it sounds like a Permissions issue with SQL possibly your IISPool having access to your SQL database. 

Try setting app pool permissions to LocalSystem. And make sure your connectionstring / database user has db create  permission.

**Comment by enkodellc** [comment]
Also look through stackoverflow. 
https://stackoverflow.com/questions/9945409/how-do-i-fix-the-error-named-pipes-provider-error-40-could-not-open-a-connec

This is a configuration issue for you specifically and most likely not an issue with BlazorBoilerplate.  Please post your solution when you figure it out so if others do have a similar issue they might be able to find it here.

**Comment by wvmstr** [comment]
Did look at the SO thread earlier.

I have several web site projects on this machine all connecting fine to server\\SQLSERVER

Created another db there and changed the connection string, still the same result. Is there a specific SQL server version necessary for this to work?

**Comment by enkodellc** [comment]
Sorry you are having issues. 
No there is nothing specific about the SQL server. I am using 2014 / 12.2.50 Standard edition on my production server and version 2016 / 13.0.1742.0 on my dev machine. Should be pretty basic SQL so I would think any version newer than 2005 would be fine.

Please check the log files in the log folder created by the app... might have to create it. Might have more details in there.

**Comment by enkodellc** [comment]
You could also try switching to SQLLite / file db to at least get going.

**Comment by wvmstr** [comment]
By the way aspnet-BlazorAuthenticationSample, did by itself create the db when I ran it the other day.

The connection string is different, so I modified what is in boilerplate appsettings.json, but that didn't do the trick.

"DefaultConnection": "Server=(localdb)\\MSSQLLocalDB;Database=blazor_boilerplate;Trusted_Connection=True;MultipleActiveResultSets=True"

**Comment by enkodellc** [comment]
Post your appsettings.json for your server. I know this is something specific to you as I know of several others running BlazorBoilerplate on production / demo servers including myself. This is not something I can debug because it is your config on your server. Having the aspnet-BlazorAuthenticationSample working does show that you could use that connectionstring again and it should work.


Here is mine, with redacted credentials, I setup my server to use "localhost" though instead of "(localdb)\MSSQLLocalDB". 

 ```
 "ConnectionStrings": {
    "DefaultConnection": "Data Source=localhost;Initial Catalog=blazor_boilerplate;MultipleActiveResultSets=true;User ID=YYYYYYYYY;Password=XXXXXXXXXXX",
    "SqlLiteConnectionFileName": "data.db"
  },

  "BlazorBoilerplate": {
    "ApplicationUrl": "https://blazorboilerplate.com",
    "RequireConfirmedEmail": false,
    "APILogging": {
      "Enabled": true,
      "IgnorePaths": [ "/api/userprofile" ]
    },
    "UseSqlServer": true,
    "UseSqlLite": false,
    "IS4ApplicationUrl": "https://blazorboilerplate.com",
    "UseLocalCertStore": "true",
    "CertificateThumbprint": "‎143fbd7bc76d78b1acf9a53c17326eaebe78353a"
  },

```

**Comment by enkodellc** [comment]
You could also try this:  https://github.com/stavroskasidis/BlazorWithIdentity  as that is what I started BlazorBoilerplate with and see if you can get that repo running on your server.

**Comment by enkodellc** [comment]
Status update??

**Comment by wvmstr** [comment]
Still looking at the same issue.

VS2019 16.3.0

Running without a db connection string works and the site comes up with the Authorizing spinner. This tell me asp.net core is working, right?

Tried several connection strings both to localdb as well as to my sql server. None work.

Even copied a connection string from a asp.net 4.8 project that works, changed the initial catalog ==> does not work either.

Toggled the UseSqlServer / UseSqlLite flags and still get the named pipes error message (against your original combo connection string. What else does it need to run against SQLite?

The blazorauthentication sample works.

BlazorwithIdentity works against SQLite db.

I have some screenclips for you.

**Comment by enkodellc** [comment]
Robert,

Ha, read this out of order.

Sorry you are having these issues. I have one other guy having dll issues
and they are very strange as much as your connection string issues are.

First off Update VS to 16.4. That shouldn't make much of a difference but
it might be worth a try.

For it to work on SQL Lite it just needs folder access to write to a local
file both apps should work with that.

BlazorWithIdentity works with SQLLite db, that is a good start. Does it
also work with SQL Server?  ON your production correct?

If that is the case you should try Version 0.2.3 of BlazorBoilerplate as
that doesn't use Identity Server 4... Then we know the issue for you has
something to do with that.

Thanks,
Keith

**Comment by wvmstr** [comment]
I will reply here.

First of all there is no urgency. I am educating myself on core. All my sites are currently on 4.5 – 4.8, and it is unlikely I will redo those due to the amount of work involved.

I just updated to 16.3.5, go with the preview then?

My applications are pretty complex and I am using SQL Express exclusively (everything works), so far not had a need to use SQLite. But I don’t mind attempting to get it going to eliminate possible reasons why your app won’t get a connection.

How can I see that blazor templates are actually installed? They don’t show with dotnet –info

How do I get Version 0.2.3 of BlazorBoilerplate?


________________________________

**Comment by enkodellc** [comment]
I just updated to 16.3.5, go with the preview then? 
- You don't have to do that anymore according to Microsoft.

My applications are pretty complex and I am using SQL Express exclusively (everything works), so far not had a need to use SQLite. But I don’t mind attempting to get it going to eliminate possible reasons why your app won’t get a connection.  
- Doing SQLLite to start is a good just to avoid SQL issues to start.

How can I see that blazor templates are actually installed?
 - Personally I don't use them but they are another way of testing to make sure your server will work with Blazor

How do I get Version 0.2.3 of BlazorBoilerplate?
- Look at the github page and click "release" link near the top / middle.
-  Here are the releases: https://github.com/enkodellc/blazorboilerplate/releases-  
-  Try this one specifically: https://github.com/enkodellc/blazorboilerplate/tree/0.2.3

**Comment by wvmstr** [comment]
Complete all Blazor dependencies.

  *   .Net Core SDK 3.1.100-preview1-014459<https://dotnet.microsoft.com/download/dotnet-core/3.1>
  *   Visual Studio 2019 Preview with the ASP.NET and web development workload selected.
  *   The Blazor templates on the command-line: dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.1.0-preview1.19508.20
  *   For Entity Framework Core on the command-line tools: dotnet tool install --global dotnet-ef --version 3.1.100
0.2.3 does the same thing



________________________________

**Comment by enkodellc** [comment]
So 0.2.3 errors the same as 0.3. BlazorWithIdentity works right? : 

Just to be 100% clear this is the repo you tried and it published?https://github.com/stavroskasidis/BlazorWithIdentity

**Comment by wvmstr** [comment]
See below:

**Comment by wvmstr** [comment]
Keith, do I have everything I need?

PM> Get-Package

Id                                  Versions                                 ProjectName
--                                  --------                                 -----------
Microsoft.EntityFrameworkCore       {3.0.0}                                  BlazorBoilerplate.Server
Microsoft.EntityFrameworkCore.Sq... {3.0.0}                                  BlazorBoilerplate.Server
AutoMapper                          {9.0.0}                                  BlazorBoilerplate.Server
MailKit                             {2.3.1.6}                                BlazorBoilerplate.Server
Microsoft.EntityFrameworkCore.De... {3.0.0}                                  BlazorBoilerplate.Server
NSwag.AspNetCore                    {13.0.6}                                 BlazorBoilerplate.Server
Microsoft.EntityFrameworkCore.Tools {3.0.0}                                  BlazorBoilerplate.Server
Serilog.Settings.Configuration      {3.1.1-dev-00209}                        BlazorBoilerplate.Server
Microsoft.AspNetCore.Mvc.Newtons... {3.0.0}                                  BlazorBoilerplate.Server
Microsoft.EntityFrameworkCore.Sq... {3.0.0}                                  BlazorBoilerplate.Server
Serilog.Sinks.File                  {4.1.0-dev-00850}                        BlazorBoilerplate.Server
Microsoft.AspNetCore.Identity.En... {3.0.0}                                  BlazorBoilerplate.Server
Microsoft.AspNetCore.Blazor.Server  {3.0.0-preview9.19465.2}                 BlazorBoilerplate.Server
Serilog                             {2.9.0-dev-01124}                        BlazorBoilerplate.Server
Serilog.AspNetCore                  {3.0.1-dev-00099}                        BlazorBoilerplate.Server
Newtonsoft.Json                     {12.0.3-beta1}                           BlazorBoilerplate.Shared
System.ComponentModel.Annotations   {4.6.0}                                  BlazorBoilerplate.Shared
Microsoft.AspNetCore.Authorization  {3.0.0}                                  BlazorBoilerplate.Shared
NETStandard.Library                 {2.0.3}                                  BlazorBoilerplate.Shared
Microsoft.AspNetCore.Components.... {3.0.0}                                  BlazorBoilerplate.Client
Microsoft.AspNetCore.Blazor.Build   {3.0.0-preview9.19465.2}                 BlazorBoilerplate.Client
Microsoft.AspNetCore.Blazor.DevS... {3.0.0-preview9.19465.2}                 BlazorBoilerplate.Client
MatBlazor                           {1.9.0}                                  BlazorBoilerplate.Client
Toolbelt.Blazor.LoadingBar          {7.0.0}                                  BlazorBoilerplate.Client
Microsoft.AspNetCore.Blazor         {3.0.0-preview9.19465.2}                 BlazorBoilerplate.Client
Microsoft.AspNetCore.Blazor.Http... {3.0.0-preview9.19465.2}                 BlazorBoilerplate.Client
NETStandard.Library                 {2.0.3}                                  BlazorBoilerplate.Client



________________________________

**Comment by enkodellc** [comment]
It looks like you are missing IdentityServer4.. What version of BlazorBoilerplate are you using? Here is my List:

Newtonsoft.Json                     {12.0.3-beta2}                           BlazorBoilerplate.Shared                                                                                                                                                       
System.ComponentModel.Annotations   {4.7.0-preview1.19504.10}                BlazorBoilerplate.Shared                                                                                                                                                       
Microsoft.AspNetCore.Authorization  {3.1.0-preview1.19508.20}                BlazorBoilerplate.Shared                                                                                                                                                       
NETStandard.Library                 {2.0.3}                                  BlazorBoilerplate.Shared                                                                                                                                                       
Microsoft.AspNetCore.Components.... {3.1.0-preview1.19508.20}                BlazorBoilerplate.Client                                                                                                                                                       
Microsoft.AspNetCore.Blazor.Build   {3.1.0-preview1.19508.20}                BlazorBoilerplate.Client                                                                                                                                                       
Microsoft.AspNetCore.Blazor.DevS... {3.1.0-preview1.19508.20}                BlazorBoilerplate.Client                                                                                                                                                       
MatBlazor                           {1.10.0}                                 BlazorBoilerplate.Client                                                                                                                                                       
Toolbelt.Blazor.LoadingBar          {7.0.0}                                  BlazorBoilerplate.Client                                                                                                                                                       
Microsoft.AspNetCore.Blazor         {3.1.0-preview1.19508.20}                BlazorBoilerplate.Client                                                                                                                                                       
Microsoft.AspNetCore.Blazor.Http... {3.1.0-preview1.19508.20}                BlazorBoilerplate.Client                                                                                                                                                       
NETStandard.Library                 {2.0.3}                                  BlazorBoilerplate.Client                                                                                                                                                       
Microsoft.EntityFrameworkCore       {3.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
Microsoft.EntityFrameworkCore.Sq... {3.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
AutoMapper                          {9.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
MailKit                             {2.3.1.6}                                BlazorBoilerplate.Server                                                                                                                                                       
Microsoft.EntityFrameworkCore.De... {3.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
IdentityServer4                     {3.0.1}                                  BlazorBoilerplate.Server                                                                                                                                                       
IdentityServer4.AccessTokenValid... {3.0.1}                                  BlazorBoilerplate.Server                                                                                                                                                       
NSwag.AspNetCore                    {13.1.2}                                 BlazorBoilerplate.Server                                                                                                                                                       
Microsoft.EntityFrameworkCore.Tools {3.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
Serilog.Settings.Configuration      {3.1.1-dev-00209}                        BlazorBoilerplate.Server                                                                                                                                                       
Microsoft.AspNetCore.Mvc.Newtons... {3.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
Microsoft.EntityFrameworkCore.Sq... {3.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
Serilog.Sinks.File                  {4.1.0-dev-00850}                        BlazorBoilerplate.Server                                                                                                                                                       
Microsoft.AspNetCore.Identity.En... {3.0.0}                                  BlazorBoilerplate.Server                                                                                                                                                       
IdentityServer4.EntityFramework     {3.0.1}                                  BlazorBoilerplate.Server                                                                                                                                                       
Microsoft.AspNetCore.Blazor.Server  {3.0.0-preview9.19465.2}                 BlazorBoilerplate.Server                                                                                                                                                       
Serilog                             {2.9.0-dev-01124}                        BlazorBoilerplate.Server                                                                                                                                                       
Serilog.AspNetCore                  {3.0.1-dev-00116}                        BlazorBoilerplate.Server                                                                                                                                                       
IdentityServer4.AspNetIdentity      {3.0.1}                                  BlazorBoilerplate.Server

**Comment by enkodellc** [comment]
I took an old laptop, installed the latest VS 2019 Preview and .net Core 3.1 Preview to test out a very fresh BlazorBoilerplate. You don't need any of the VS templates. I did find an issue with the database code that I just pushed a fix. Did you ever open up the Logs and show me the full log of your errors? Any updates otherwise?

**Comment by MrMetallon** [comment]
I had the same problem, so maybe this may help you.
I have changed the database settings in appsettings.json but forgot to change them in appsettings.Development.json.

**Comment by wvmstr** [comment]
@MrMetallon ...... thank you!

That was it. Completely missed that triangle
