### ISSUE TITLE
"Switch from Entity Framework Core to Dapper" ?!

### ISSUE THREAD

**Issue by glazkovalex** [enkodellc/blazorboilerplate#55]
In your road map it is written that: "Switch from Entity Framework Core to Dapper. So far EF is not my cup of Tea. I think dapper will be stronger and faster"

Entity Framework Core does not slow down the database in any way. The speed is limited not by Entity Framework Core, but by the relational DBMS itself. Dapper will be just as slow, but will consume a little less CPU time for mapping and tracking objects. To accelerate, you do not need to downgrade to dapper. To speed up, you need to add a second level cache to the perfect Entity Framework Core!

**Comment by enkodellc** [comment]
@glazkovalex  I am not going to go into a deep dive into the speed of Dapper vs EF, frankly I might even use it if it was slower if it was faster for me to develop with. I have read a few posts and comparisons and in most cases Dapper was faster. Though I doubt most of the calls I make will ever be noticed by the end user.  I might just go ADO.net...

I have not used Dapper or EF extensively but my existing project that I want to convert with BlazorBoilerplate already has an extensive set of Stored Procedures and I am decent with SQL so in that specific scenario it appears that Dapper will be easier to develop with. I will take some time in the future to test out that theory. Hasn't been done yet.

My experience with EF has not been great so I will be trying Dapper.  So if my opinion is that I feel Dapper is faster to develop with and more user friendly then that is the approach I will use for BlazorBoilerplate. I appreciate your feedback but either way
