### ISSUE TITLE
Cannot run project from command line

### ISSUE THREAD

**Issue by captainkout** [enkodellc/blazorboilerplate#561]
# A quick summary and/or background
I am able to run the project from Visual Studio (VS) using the existing launch settings. However, I want to use the functionality provided by `dotnet watch run`. If I run from cmd/powershell/gitbash, I see the same ef-core related console output that is produced when running from VS, but NOT the subsequent output that says the server is now listening.

# Steps to run in VS
1. Clone repo
2. Go to server project and update appsettings.json with my local db and db name.
3. Select BlazorBoilerplate.Server(IIS profile works the same) launch profile and click 'play'
4. This is the output.
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      SELECT [l].[Id], [l].[ContextId], [l].[Culture], [l].[MsgId], [l].[MsgIdPlural], [l].[Translation], [p].[Id], [p].[Index], [p].[LocalizationRecordId], [p].[Translation]
      FROM [LocalizationRecords] AS [l]
      LEFT JOIN [PluralTranslations] AS [p] ON [l].[Id] = [p].[LocalizationRecordId]
      ORDER BY [l].[Id], [p].[Id]

[brief pause, developer added note]
      
Hosting environment: Production
Content root path: C:\ckDev\blazorboilerplate\src\Server\BlazorBoilerplate.Server
Now listening on: http://127.0.0.1:49978
Application started. Press Ctrl+C to shut down.
```
# Steps to run via command line
1. Clone repo
2. Go to server project and update appsettings.json with my local db and db name.
3. Opend cmd inside BlazorBoilerplate.Server project directory and run command w
```
dotnet run --launch-profile BlazorBoilerplate.Server
...
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
      SELECT [l].[Id], [l].[ContextId], [l].[Culture], [l].[MsgId], [l].[MsgIdPlural], [l].[Translation], [p].[Id], [p].[Index], [p].[LocalizationRecordId], [p].[Translation]
      FROM [LocalizationRecords] AS [l]
      LEFT JOIN [PluralTranslations] AS [p] ON [l].[Id] = [p].[LocalizationRecordId]
      ORDER BY [l].[Id], [p].[Id]

[The pause lasts forever, developer added note]
```
# What you expected would happen
I expect that the console will be identical between the two scenarios. And that the application viewed via the browser will be identical.

# What actually happens
Running from command line Never completes, the application is not served.

# Notes 
- I tried opening to the application url and there is no response from the application.
- I tried following the same procedure from the BlazorWithIdentity project and I successfully ran the application both ways.
- I turned on verbose diagnostics but there are no additional diagnostic messages from the point of failure. All messages prior to this point represented successes.
- The sql produced executes without error in sql server.

**Comment by GioviQ** [comment]
Did you check the profile?
What application url have you open in the browser?

**Comment by captainkout** [comment]
I've tried running under all potential profiles. Default and BlazorBoilerplate.Server. If I try to run under IIS, it errors.
```
c;\blazorboilerplate\src\Server\BlazorBoilerplate.Server> dotnet run 
c;\blazorboilerplate\src\Server\BlazorBoilerplate.Server> dotnet run --launch-profile BlazorBoilerplate.Server
```
