### ISSUE TITLE
IAuditable is not being generated for Todo class.

### ISSUE THREAD

**Issue by JGaffel** [enkodellc/blazorboilerplate#563]
BlazorBoilerplate.EntityGenerator does not generate IAuditable breaking the Todo class.

**Comment by enkodellc** [comment]
@JGaffel  please let me know what you did to resolve your issue. I want to update the Readme a bit more and having some insight on issues will help.

**Comment by JGaffel** [comment]
Hi @enkodellc,
This turned out to be missing dependencies on my machine related to BlazorBoilerplate.SourceGenerator.
What was obscure about this issue was that visual studio could build BlazorBoilerplate.SourceGenerator without error but would fail and log an error to output window when building BlazorBoilerplate.Infrastructure.Storage.
Upgrading Visual Studio from 16.8 to 16.9 resolved the issue.
