### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'  Microsoft.AspNetCore.Http.IHttpContextAccessor.HttpContext.get 

### ISSUE THREAD

**Issue by EmergentCybernetics** [enkodellc/blazorboilerplate#567]
I'm running into this error on startup with a fresh clone of the repo today:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

Microsoft.AspNetCore.Http.IHttpContextAccessor.HttpContext.get 
```

It is coming from here:
https://github.com/enkodellc/blazorboilerplate/blob/141cfdc51c6fb4613899483cbe2ff6a8fa38f311/src/Server/BlazorBoilerplate.Server/Startup.cs#L553

![httpContextAccessor HttpContext](https://user-images.githubusercontent.com/42426103/116738424-0a7d6a00-a9b8-11eb-8255-656c400a492c.png)

I have blazorboilerplate running on another computer without issue. I'm not sure why there's an error on this one. I'm able to get around the error by patching it with:

```diff
diff --git a/src/Server/BlazorBoilerplate.Server/Startup.cs b/src/Server/BlazorBoilerplate.Server/Startup.cs
index 186bd58..cf501a0 100644
--- a/src/Server/BlazorBoilerplate.Server/Startup.cs
+++ b/src/Server/BlazorBoilerplate.Server/Startup.cs
@@ -550,7 +550,7 @@ namespace BlazorBoilerplate.Server
                 // creating the URI helper needs to wait until the JS Runtime is initialized, so defer it.
                 var navigationManager = s.GetRequiredService<NavigationManager>();
                 var httpContextAccessor = s.GetRequiredService<IHttpContextAccessor>();
-                var cookies = httpContextAccessor.HttpContext.Request.Cookies;
+                var cookies = httpContextAccessor.HttpContext == null ? null : httpContextAccessor.HttpContext.Request.Cookies;
                 var httpClientHandler = new HttpClientHandler(){ UseCookies = false };
                 if (_environment.IsDevelopment())
                 {
@@ -558,7 +558,7 @@ namespace BlazorBoilerplate.Server
                     httpClientHandler.ServerCertificateCustomValidationCallback = (message, cert, chain, errors) => { return true; };
                 }
                 var client = new HttpClient(httpClientHandler);
-                if (cookies.Any())
+                if (cookies != null && cookies.Any())
                 {
                     var cks = new List<string>();
```

**Comment by GioviQ** [comment]
What's the difference with the computer without issue?

**Comment by EmergentCybernetics** [comment]
PC with the issue is running Windows 7 (yes, I know it's EOL).
Just did a clone on a new Windows 10 VM and it's working there.

**Comment by EmergentCybernetics** [comment]
Sorry, I don't have any non-VM Windows 10 installs. Seems to be working fine. Just not on Windows 7.

**Comment by 12step** [comment]
This symptom is exactly what Microsoft say will happen sometimes (but not every time) you try to access httpContext using IHttpContextAccessor from within a Blazor app. In BB, if the accessor fails httpContext will be null when BB requests cookies at startup .  I have some test environments where the accessor works fine and others running the exact same code where the accessor fails at that line.

In the earlier days of Blazor MS were advising to use IHttpContextAccessor. This changed a while ago and now they explicitly state that "you must not use IHttpContextAccessor within Blazor apps. Blazor apps run outside of the context of the ASP.NET Core pipeline. The HttpContext isn't guaranteed to be available within the IHttpContextAccessor, nor is it guaranteed to be holding the context that started the Blazor app". (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0)

The solution they give here fixes the problem: https://docs.microsoft.com/en-us/aspnet/core/blazor/security/server/additional-scenarios?view=aspnetcore-5.0. Also this project uses the new approach: https://github.com/javiercn/blazor-server-aad-sample

**Comment by 12step** [comment]
Possibly related to this issue (from https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-context?view=aspnetcore-5.0) ?

"Additionally, again for security reasons, you must not use IHttpContextAccessor within Blazor apps. Blazor apps run outside of the context of the ASP.NET Core pipeline. The HttpContext isn't guaranteed to be available within the IHttpContextAccessor, nor is it guaranteed to be holding the context that started the Blazor app.

The recommended way to pass request state to the Blazor app is through parameters to the root component in the initial rendering of the app"

I have some test environments that fail at this same line. httpContext is null. The exact same code retrieves httpContext fine on a different environment.

**Comment by maddadder** [comment]
> PC with the issue is running Windows 7 (yes, I know it's EOL).
> Just did a clone on a new Windows 10 VM and it's working there.

Support for Windows 7 has ended. After 10 years, support for Windows 7 ended on January 14, 2020. Are you suggested that blazorboilerplate modify this code base to support it?

**Comment by enkodellc** [comment]
I got this issue on my win7 laptop. Used @EmergentCybernetics  adjusted code and it seems work for me until I get back to my win10 box. I am closing issue.
