### ISSUE TITLE
BlazorBoilerplate.Client.csproj is configured to use netstandard2.0

### ISSUE THREAD

**Issue by tstockwell** [enkodellc/blazorboilerplate#57]
I'm thinking that it's just a typo.  That's not correct, is it?

If I change netstandard2.0 to netcoreapp3.1 and rebuild then I get some errors.

**Comment by enkodellc** [comment]
Not a typo. Blazor webassembly / Client side still runs on netstandard2.0.  It's in the documentation and I believe if you use MS Blazor Webassembly templates you will see the same TargetFramework netstandard2.0.

**Comment by enkodellc** [comment]
https://github.com/aspnet/AspNetCore/issues/10579

**Comment by tstockwell** [comment]
Thanks much!
For other readers, here's why...
>  .NET Standard 2.0 is used on Blazor client because the underlying runtime is mono
