### ISSUE TITLE
Breeze Where

### ISSUE THREAD

**Issue by agorota** [enkodellc/blazorboilerplate#578]
Good morning,

I find myself with a table with many records > 10000, if I use GetToDos as in the example I get an exception.
How do I filter based on a condition? 
GetToDos is only an example...in ApiClient

Original:
public async Task<QueryResult<Todo>> GetToDos()
        {
            return await GetItems<Todo>(from: "Todos", orderByDescending: i => i.CreatedOn);

        }

How Customize it?
 public async Task<QueryResult<Todo>> GetToDos(bool IsCompleted)
        {
            return await GetItems<Todo>(from: "Todos", orderByDescending: i => i.CreatedOn, ??? Where IsCompleted==true???);
        }

Thanks a lot.

**Comment by GioviQ** [comment]
i.IsCompleted == true without Where

Another predicate example in https://github.com/enkodellc/blazorboilerplate/blob/master/src/Shared/Modules/BlazorBoilerplate.Theme.Material.Admin/Pages/Admin/DbLogViewer.razor#L91

**Comment by agorota** [comment]
I have tested with an int or string field and the selection works perfectly
, while in my real case I should select a Guid field but I get the following error from Db Log Viewer:


Log Message:
GetItems: "This EntityQuery ctor requires a valid json string. The following is not json: {\" skip \ ": 0, \" take \ ": 10, \" inlineCount \ ": true, \" where \ ": { \ "device_id \":}} "

Recorded Properties:

     0: This EntityQuery ctor requires a valid json string. The following is not json: {"skip": 0, "take": 10, "inlineCount": true, "where": {"device_id":}}
     SourceContext: BlazorBoilerplate.Shared.Services.ApiClient
     TransportConnectionId: A1eTlTqAmV5Rcatjohr-OA
     RequestId: 8000004d-0000-f800-b63f-84710c7967bb
     RequestPath: / _blazor


Thank you

**Comment by agorota** [comment]
Guid g = new Guid();
 g = Guid.Parse("CB1610EF-303C-4B84-AE22-003FD79D74B3");

Expression<Func<LogVeeam, bool>> predicate = null;
predicate = (i => i.device_id == g);
var result = await apiClient.GetLogVeeams(predicate, pageSize, pageIndex * pageSize);

in the body of predicate have this:
**Body = {(i.device_id == value(BlazorBoilerplate.Theme.Material.Demo.Pages.SigmaAdminDB.LogVeeamView+<>c__DisplayClass22_0).g)}**

How can pass Guid g value in predicate?
Thanks

**Comment by GioviQ** [comment]
I am reading this now
https://stackoverflow.com/questions/358345/hanging-linq-query-with-guid-empty-in-the-where-expression

**Comment by agorota** [comment]
> 
> 
> I am reading this now
> https://stackoverflow.com/questions/358345/hanging-linq-query-with-guid-empty-in-the-where-expression

**Comment by agorota** [comment]
I can't make myself understood ...

I would like to select records for GUID fields
For example, I simulated the modification in the ToDo example page to select only the records modified by a certain user (guid) and I get the error that I cannot solve:

If you want to try it too, below is a real example on the TodoList.razor demo:


    async Task LoadMainEntities()
    {
        try
        {

            // modifica per test Guid

            var g = Guid.Parse("58AF06F9-B958-4822-1767-08D912ED1380");
            Expression<Func<Todo, bool>> predicate = null;
            predicate = (i => i.ModifiedById == g);
            var result = await apiClient.GetToDos2(predicate, pageSize, pageIndex * pageSize);
            todos = new List<Todo>(result);
            viewNotifier.Show(L["One item found", Plural.From("{0} items found", (int)result.InlineCount)], ViewNotifierType.Success, L["Operation Successful"]);

            //
            //var result = await apiClient.GetToDos();
            //todos = new List<Todo>(result);
            //viewNotifier.Show(L["One item found", Plural.From("{0} items found", (int)result.InlineCount)], ViewNotifierType.Success, L["Operation Successful"]);
        }
        catch (Exception ex)
        {
            viewNotifier.Show(ex.GetBaseException().Message, ViewNotifierType.Error, L["Operation Failed"]);
        }
    }

Add In ApiClient.cs:


public async Task<QueryResult<Todo>> GetToDos2(Expression<Func<Todo, bool>> predicate = null, int? take = null, int? skip = null)
        {
            return await GetItems("Todos", predicate, null, null, take, skip);
        }

add in IApiClient.cs
Task<QueryResult<Todo>> GetToDos2(Expression<Func<Todo, bool>> predicate = null, int? take = null, int? skip = null);


It is as if it does not correctly convert the predicate to json only if the field is of type Guid

Please help me...

**Comment by GioviQ** [comment]
Based on what I read, try with:
         
            var result = await apiClient.GetToDos2(i => i.ModifiedById == new Guid("CB1610EF-303C-4B84-AE22-003FD79D74B3"), pageSize, pageIndex * pageSize);

**Comment by agorota** [comment]
ok, so it works
I didn't understand why ...

Very kind

**Comment by agorota** [comment]
Can't I access the details of a linked table with this method?
How do you include it?

    
        predicate = (i => i.Device.customer_id == new Guid(s));
        var result = await apiClient.GetLogVeeams2(predicate, pageSize, pageIndex * pageSize);


using the previous method I could ...

        var result = await apiClient.GetLogVeeams();

Thanks

**Comment by GioviQ** [comment]
I cannot support you developing your application...

**Comment by enkodellc** [comment]
@agorota I agree with @GioviQ  If you want a consultant to help with your application please hire someone. The questions you have are not related to BB specifically. BB offers many code examples and you can find other free examples on how to write API methods.
