### ISSUE TITLE
Duplicate Home > Breadcrumb links

### ISSUE THREAD

**Issue by EmergentCybernetics** [enkodellc/blazorboilerplate#590]
Is there any reason for the breadcrumb link to have both `HOME` AND `BREADCRUMB`?
![Global BreadCrumb](https://user-images.githubusercontent.com/42426103/118326191-dfb80900-b4c1-11eb-9baa-eeb6f9112b89.png)

I can add a translation for it so it is any text I'd like (made it `...` below), but it seems redundant to have both `HOME` AND `BREADCRUMB` in all the breadcrumbs.
![Global BreadCrumb-trans](https://user-images.githubusercontent.com/42426103/118326353-1aba3c80-b4c2-11eb-88a9-dbe82cdc1096.png)

**Comment by GioviQ** [comment]
breadcrumb links have to be reimplemented.
