### ISSUE TITLE
Drag and drop doesn't work in Firefox

### ISSUE THREAD

**Issue by KevinFarrow** [enkodellc/blazorboilerplate#60]
Drag and drop doesn't work - cannot grab anything (see animated gif below)

Windows 10 Pro, Firefox 70.0.1 (64 bit)

![__2019-11-18_12-19-40](https://user-images.githubusercontent.com/1365851/69052102-0ba61b80-09fe-11ea-87c0-1c592c31bdd9.gif)

**Comment by enkodellc** [comment]
Duplicate issue #52

**Comment by enkodellc** [comment]
@KevinFarrow  take a look here for some answers. My example is an example of Chris Sainty's: https://github.com/chrissainty/SimpleDragAndDropWithBlazor/issues/1

If you find a solution please post a PR. Thanks!

**Comment by enkodellc** [comment]
@KevinFarrow . Drag and drop seems to be working in Version 0.5.0 and FF 71.0

**Comment by KevinFarrow** [comment]
Yeah that appear to work now, thanks :-)
