### ISSUE TITLE
Unable to connect to web server 'IIS Express'

### ISSUE THREAD

**Issue by joshmccall221** [enkodellc/blazorboilerplate#61]
- Clone
- Run in VS

and then ...

![image](https://user-images.githubusercontent.com/7776611/69452410-6d27fc00-0d16-11ea-94de-d54dc8a49440.png)

**Comment by joshmccall221** [comment]
#58

**Comment by joshmccall221** [comment]
Duplicate of #58

**Comment by enkodellc** [comment]
@joshmccall221  Sorry to see you are having an issue. I don't know how to approach your issue as you are the first that has brought it up and I would suspect it is machine specific. I would start by checking your dependencies and then your appsettings.   Delete your .vs folder... Below are some other links that might have solutions.

https://developercommunity.visualstudio.com/content/problem/195224/unable-to-connect-to-web-server-iisexpress.html

http://overengineer.net/fixing-unable-to-connect-to-web-server-iis-express

https://forums.asp.net/t/2144945.aspx?Unable+to+connect+to+web+server+IIS+Express+

https://github.com/aspnet/AspNetCore/issues/1671

**Comment by joshmccall221** [comment]
Switched from `IIS` to `BlazorBoilerplate.Server` and changed port on `App URL`. 

And now it runs.

**Comment by joshmccall221** [comment]
Are the client and sever projects 2 different projects or the same thing but different blazor hosting models? 

When I run the client project it hangs at `Authorizing...`

**Comment by enkodellc** [comment]
Please read the ReadMe for BB and more on Client-side / webassembly Blazor.  Here is a link: https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0

As for your "Authorizing" issue it is most likely related to your AppSettings / DB connection. Please check your /Log/*   files and review any issues there. 

Thanks for using Blazor Boilerplate.

**Comment by enkodellc** [comment]
@joshmccall221 what is your status? Did you sort out your configuration? Did the log files help?
