### ISSUE TITLE
contributing : postgres support

### ISSUE THREAD

**Issue by vd3d** [enkodellc/blazorboilerplate#62]
Hi,

I have just start to work on your boilerplate, I wish to contribute.

I have add the postgres support, it is a simple and basic contribution.

If you are interested I wish to work on the roles/permissions now, if you agree ?

Thanks

**Comment by enkodellc** [comment]
Hi @vd3d if you wish feel free to submit a PR that will do postgres that is simple and does not break the code I will merge. I will most likely not be able to test as i don't use postgres. 

I will definitely support additional contributions for roles and permissions. Thanks. If possible please use our gitter for further discussion about contributions. https://gitter.im/blazorboilerplate/community

**Comment by acid12** [comment]
Closing as PR #64 has been created for postgresql support
