### ISSUE TITLE
Postgres NVarchar is not defined

### ISSUE THREAD

**Issue by pomeara** [enkodellc/blazorboilerplate#637]
I have tried to use the postgres database and immediately as the application loads I get the following error

"System.AggregateException: 'One or more errors occurred. (42704: type "nvarchar" does not exist)'"

![image](https://user-images.githubusercontent.com/8163710/126979423-0a6de167-c456-42b6-bf36-cec4a9433a26.png)

I am working on updating the instructions for postgres wouldn't mind some assistance as i wouldn't imagine people would use SQL server typically

![image](https://user-images.githubusercontent.com/8163710/127095657-2a70e244-5234-4bac-ae1f-0cf0f78aa7be.png)

**Comment by enkodellc** [comment]
Sounds like you should replace "nvarchar" with another type that postgres likes. I have not done any work with postgres so you will have to sort it out.
