### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by Coupz** [enkodellc/blazorboilerplate#660]
Not sure if I'm dumb or missing something.
I've had issues because of .NET 6 Preview installed (build process screamed at me thousand times that I'm using a preview version) which I cleared by adding a global.json inside the src folder.

I've created a new DB in SQL Object Explorer and changed the ConnectionString inside the appsettings.json but I still can't run the app. 

Is there a tutorial that I missed? Would love for some help getting started with this template.
Thanks in advance.

**Comment by GioviQ** [comment]
I didn't tested with .NET 6 preview. Use .NET 5.

The db is created by EF migration.

So clone again the project and rebuild all, without changes.

**Comment by Coupz** [comment]
Like I said, I've already fixed the issue with .NET 6 and even tried to uninstall it.
This project is not building when fresh cloned. Maybe something to think about or work on better documentation, because I can't run any migrations when the solution doesn't even build. Multiple projects fail on every try.

**Comment by GioviQ** [comment]
Visual Studio has sometime issues rebuilding project with source generator, so you have to insist.
Rebuild all, close and reopen Visual Studio.
It's not a problem of the project. I am using it every day.

**Comment by enkodellc** [comment]
I use .NET 6 and have not pushed it to the repo yet.  I did often get a lot of build errors. Usually comes down to connection strings or VS cache issues. I would start reviewing all output from the log files and command output.   I will take a look at a fresh  copy of the source later today.

**Comment by mdora7** [comment]
I am using through the VS2020 preview 6 and therefore .NET 6. SourceGenerator sometimes can't generate the DTO class (this just only at compile time) but breeze.sharp would be a problem as didn't generate some dtos. I've not faced other issues except that by now.

Usually, I remove and re-add this OutputType this provides only the source generator works

`<ProjectReference Include="..\..\Utils\BlazorBoilerplate.SourceGenerator\BlazorBoilerplate.SourceGenerator.csproj"  OutputItemType="Analyzer" ReferenceOutputAssembly="false" />`


`<ProjectReference Include="..\..\Utils\BlazorBoilerplate.SourceGenerator\BlazorBoilerplate.SourceGenerator.csproj"  ReferenceOutputAssembly="false" />`

**Comment by enkodellc** [comment]
@Coupz  Do you have some further log file data to show us to help?

**Comment by Coupz** [comment]
Sorry, I've already deleted VS 2022 and didn't had time to test it with @mdora7 his tip. Will look to try this out, hopefully in the next 1-2 weeks.

**Comment by enkodellc** [comment]
I will close. Please re-open / update if and when you get a chance to test again. I strictly use VS '22 with a .Net Core 5 & another fork with 6. So I would assume that it will work for you as well with a little more config.
