### ISSUE TITLE
build no longer works on linux since March 1st, 2021

### ISSUE THREAD

**Issue by maddadder** [enkodellc/blazorboilerplate#669]
The last working build I have found to work after doing a dotnet clean was:
https://github.com/enkodellc/blazorboilerplate/commit/c30f5afd5caa31e1ad5b50779b921f17a7775c59

The commit after that contains a change of Microsoft.CodeAnalysis.CSharp from 3.8.0 to 3.9.0 that breaks the linux build
So that would be this checkin:https://github.com/enkodellc/blazorboilerplate/commit/ba02c700e650a01a8f220d87fbe98255cf91f06b

steps to repro in linux:
cd blazorboilerplate/src/Server/BlazorBoilerplate.Server
dotnet build

**Comment by GioviQ** [comment]
https://github.com/dotnet/roslyn/issues/54710

**Comment by maddadder** [comment]
Installing and using https://dotnet.microsoft.com/download/dotnet/thank-you/sdk-5.0.300-linux-x64-binaries fixed it!

Thanks so much

**Comment by maddadder** [comment]
False alarm. I thought it was working but that was a prior build

**Comment by maddadder** [comment]
ok. Now it works. All I am doing is going back to a point when it worked via git reset --hard $hash, and then working my way forward. Sorry for the spam.

**Comment by maddadder** [comment]
> So now is it working without git reset?

Only if I have the correct dotnet core version running on the system. Specifically aspnet 5.0.6 and built with sdk 5.0.300

**Comment by GioviQ** [comment]
So can you close?
