### ISSUE TITLE
Loading Blazor Boilerplate... slow loading

### ISSUE THREAD

**Issue by vd3d** [enkodellc/blazorboilerplate#68]
Hi,

I have a strange side effects, the "Loading Blazor Boilerplate..." page take a lot of time before continuing... 

I mainly got this the first time I tried your Demo URL  : https://blazorboilerplate.com/

PS: In JavaScript we have "webpack" to manage the bundle, to avoid very long loading at once, not sure it is related.

**Comment by acid12** [comment]
This is quite normal for now when using ClientSide Blazor app.
The mono.wasm, (mono .net runtime compiled to webassembly) has to be download from server first.
Than all 'our' DLLs and then all dependant DLLs have to be downloaded. 
Then initialization starts.

When browser refreshes, it has all the mono/dlls cached - thats why it only occurs once.

This 'issue' is known to Microsft, and they are working on system wide solution, but for the first ClientSide Blazor release (still in preview), this will not change. In the future they plan to enable compiling our code directly to WASM to skip the mono + dotnet dlls middleware altogether (probably in .Net 5)

In the mean time, this 'issue' does not occur in ServerSide Blazor, and we are considering having both platforms supported - see #41

**Comment by enkodellc** [comment]
@vd3d  Did that answer your question? It should load as fast if not faster as it does from https://blazorboilerplate.com
