### ISSUE TITLE
"BlazorBoilerplate:Api:Doc:Enabled" not worked

### ISSUE THREAD

**Issue by toyoda-divakk** [enkodellc/blazorboilerplate#757]
I set "BlazorBoilerplate:Api:Doc:Enabled" in appsettings.json to true.
Next, when I access http://localhost:<port>/swagger, I get "Failed to fetch /swagger/v1/swagger.json".

If you comment out the "LocalizationRecordKeys" method in LocalizationController.cs, Swagger will now work.

**Comment by GioviQ** [comment]
In the last commit I updated NSwag.AspNetCore and the issue is gone.

**Comment by toyoda-divakk** [comment]
It works.
Thank you.
