### ISSUE TITLE
When running locally for development, cannot login with Firefox

### ISSUE THREAD

**Issue by EmergentCybernetics** [enkodellc/blazorboilerplate#778]
I'm not sure what's causing this, but it's working fine in Chrome.

In Firefox, entering the user/pass seems to work, but when redirected to the ReturnUrl page and it loads, the user gets logged out and redirected back to the login page.

Here's a screenshot of the console log and the Firefox dev tools log:
![firefox-login](https://user-images.githubusercontent.com/42426103/150594803-52a1dabc-3afe-4bca-98b8-df2a91744ef7.png)

It probably has something to do with the `SameSite` cookie setting?
```
[13:17:11 WRN] The cookie 'idsrv.session' has set 'SameSite=None' and must also set 'Secure'.
```

**Comment by GioviQ** [comment]
There was a similar issue with Chrome, so it depends on how browser manages cookies and from version to version this can change. 
Do you experience the same with https?

**Comment by EmergentCybernetics** [comment]
No, it seems to be fine when running with https. From here `src/Server/BlazorBoilerplate.Server`:
```
dotnet run --urls=https://*:53416
```

Chrome and Firefox logins work. 
Then only using http, Firefox logins do not:
```
dotnet run --urls=http://*:53416
```

It was working a month or so ago in Firefox for http.

**Comment by GioviQ** [comment]
here https://github.com/enkodellc/blazorboilerplate/blob/master/src/Server/BlazorBoilerplate.Server/Extensions/SameSiteHandlingExtensions.cs#L21

you can set cookies Secure to make experiments with Firefox
