### ISSUE TITLE
Disable Anonymous Authentication on IIS

### ISSUE THREAD

**Issue by ldalipis** [enkodellc/blazorboilerplate#788]
I have configured everything and deployed to my local IIS server. If I leave the Anonymous Authentication enabled on the IIS app config, then everything works great, but I want to make the app available only to a specific domain user group, so that it requires NTLM for all pages that I will create. The concept is that I want to create a web app with the DB data being common for all of them and I don't care about single users.

The problem is that when I disable Anonymous Authentication, then I get some 401 errors on the circuit and I can't understand why. Can you please guide me?

Thanks.

**Comment by enkodellc** [comment]
That question seems like it should be directed to an IIS forum or the https://gitter.im/aspnet/Blazor  forum as it is not directly related to BlazorBoilerplate code but to configuring IIS for your website. 

I currently use Anonymous Authentication on IIS enabled.  

https://stackoverflow.com/questions/49061569/disable-anonymous-authentication-in-iis-cause-error-404-15
