### ISSUE TITLE
Use System.Text.Json instead of NewtonSoft.Json

### ISSUE THREAD

**Issue by acid12** [enkodellc/blazorboilerplate#80]
From all benchmarks, the dotnet integrated JSON is much faster.

**Comment by enkodellc** [comment]
I did try this initially but there were a few functions that were not yet supported on System.Text.Json. Specifically in APIResponseRequestLoggingMiddleware  This might have changed. Feel free to review and check.

**Comment by MarkStega** [comment]
I still have a demonstrable failure of the dotnet integrated JSON in a wasm project (as of Blazor 3.1.Preview4) and would suggest not worrying about speed until the functionality errors are resolved.
Documented originally in [https://github.com/aspnet/AspNetCore/issues/14707](https://github.com/aspnet/AspNetCore/issues/14707) and then in [https://github.com/mono/mono/issues/13314](https://github.com/mono/mono/issues/13314). 14707 got moved to Mono as [https://github.com/mono/mono/issues/17735](https://github.com/mono/mono/issues/17735)
