### ISSUE TITLE
Upgrade to ASP. NET Core 3.1

### ISSUE THREAD

**Issue by acid12** [enkodellc/blazorboilerplate#81]
Check https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-1/
And https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31?view=aspnetcore-3.1&tabs=visual-studio
For release notes and migration information

Notes: even tough 3.1 has shipped, client side Blazor is still in preview, keep that in mind when upgrading nuggets.

**Comment by enkodellc** [comment]
MatBlazor updated, With your previous updates and that we are now able to update the whole solution. Thanks @acid12!
