### ISSUE TITLE
$type and $id appended to all responses

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#870]
@GioviQ have you seen this and have a solution?  I don't really want the class exposed to other users of my API. 

https://github.com/Breeze/breeze.server.net/issues/49

**Comment by GioviQ** [comment]
Even the controllers without Breeze attribute?

**Comment by GioviQ** [comment]
![Immagine 2022-05-20 203207](https://user-images.githubusercontent.com/7103057/169591165-e143f0d3-c1fe-44a6-a6d2-23b1fa7336d8.png)

It is not true

**Comment by enkodellc** [comment]
I think it is related to JsonSerializerSettings, I am testing it out.

https://www.newtonsoft.com/json/help/html/serializetypenamehandling.htm

**Comment by enkodellc** [comment]
I found the issue, It is in the middleware. The logic on this line allows the response to not be modified. I believe I was adding controller paths there I should not have been adding.

https://github.com/enkodellc/blazorboilerplate/blob/41a52c68d2f0ba8ac4e2992dd9660cf365256f7a/src/Server/BlazorBoilerplate.Server/Middleware/APIResponseRequestLoggingMiddleware.cs#L65

**Comment by GioviQ** [comment]
in fact that is the list of paths whose response has not be transformed in an ApiResonse instance.

**Comment by enkodellc** [comment]
Yes, I agree. I didn't write that very clear. :)
