### ISSUE TITLE
Version Microsoft.CodeAnalysis 4.2.0 doesn't work with NET SDK 6.0.200

### ISSUE THREAD

**Issue by AnikeRU** [enkodellc/blazorboilerplate#874]
A NET SDK 6.0.300 is required to upgrade Microsoft.CodeAnalysis.CSharp from 3.10.0 to 4.2.0,

https://github.com/dotnet/roslyn/issues/61333

**Comment by StickieBE** [comment]
This should be a bug, as the latest master is broken because of this.
