### ISSUE TITLE
Problems with EmailConfiguration in Configuration

### ISSUE THREAD

**Issue by Neoplayer** [enkodellc/blazorboilerplate#88]
![image](https://user-images.githubusercontent.com/17293976/70414033-f4d96e80-1a69-11ea-81fc-ea4f1670a832.png)

**Comment by sNakiex** [comment]
I submitted a pull request to fix this issue in this repo.
To fix it locally check out https://github.com/enkodellc/blazorboilerplate/pull/92/commits/269f86fc7b068c5e7705aa8cabdd7163fa432a09

**Comment by enkodellc** [comment]
Thanks Ray, for the Issue and PR
