### ISSUE TITLE
Dynamic ConnectionString MS Sql

### ISSUE THREAD

**Issue by AlexanderZender** [enkodellc/blazorboilerplate#899]
Hello everybody,

for my project I host blazorboilerplate inside a Kubernetes cluster, I need to dynamically set the SQL server address.
But I´m not really sure where changes would need to be provided, in the startup `?

I would really appreciate any leads!

**Comment by enkodellc** [comment]
Look here:

https://github.com/enkodellc/blazorboilerplate/blob/c2ccd54976c0f574daf9f50ddb5062b43e911f8d/src/Server/BlazorBoilerplate.Storage/ServiceCollectionExtensions.cs#L54
