### ISSUE TITLE
Login page flashing

### ISSUE THREAD

**Issue by mobinseven** [enkodellc/blazorboilerplate#94]
why login page shows up again for a moment after logging in? Any ideas on preventing this?

**Comment by enkodellc** [comment]
It looks like it has something to do with loading the userprofile in the SubmitLogin function.  I know that needs more work as it was the best I could hack at the time. There is / wasn't a great solution that I found at the time for user profile. Maybe you can take a look?

` UserProfileDto userProfileDto = await appState.GetUserProfile();`

**Comment by enkodellc** [comment]
If you so chose you can comment out some code at login. This is what is causing the blip. I tried sorting it but couldn't find the best path. Basically this is needed here to load the user profile and take the user to the last page visited after successful login.

```
                    var response = await authStateProvider.Login(loginParameters);
                    if (response.StatusCode == 200)
                    {
                    //Load User Profile // 
                    //UserProfileDto userProfileDto = await appState.GetUserProfile();

                    //if (string.IsNullOrEmpty(userProfileDto.LastPageVisited))
                    //{
                    //    navigationManager.NavigateTo(navigationManager.BaseUri + userProfileDto.LastPageVisited);
                    //}
                    //else
                    //{
                    navigationManager.NavigateTo("/dashboard");
                    //}
```
