### ISSUE TITLE
BuildNewUserConfirmationEmail wrong template parameters

### ISSUE THREAD

**Issue by AlexK555** [enkodellc/blazorboilerplate#975]
Hi, 
Registration process is not working. Failing on generating confirmation email - BuildNewUserConfirmationEmail.
System.Collections.Generic.KeyNotFoundException: 'The parameter "userId" was not present in the lookup dictionary'.

**Reason** 
userId parameter is present in the template but is not passed to the FormatWith method.

**Reproduce**
Use latest version of the template and run account/register flow.

**Comment by AlexK555** [comment]
![image](https://user-images.githubusercontent.com/22810316/204019516-f2ee655a-be78-4cb6-8e5e-e367a282ea44.png)

To fix this part of template can be removed and LocalicationRecords table reinitialized.

**Comment by enkodellc** [comment]
@AlexK555 do you want to submit a PR?

**Comment by enkodellc** [comment]
Thanks for the PR!
