### ISSUE TITLE
.NET 7 migration 

### ISSUE THREAD

**Issue by AlexK555** [enkodellc/blazorboilerplate#978]
Is it planned to migrate it to the lates .NET version?

**Comment by enkodellc** [comment]
Yes of course. Been busy and also normally wait a bit for dependencies to update as well as previously it has been an issue.

**Comment by enkodellc** [comment]
I have migrated the code to .net7. I can build and run locally fine and it builds fine in Azure Pipelines but I am running into errors when I try to deploy to IIS

The type initializer for 'IdentityServer4.EntityFramework.Mappers.ScopeMappers' threw an exception.

**Comment by samuelskottenborg** [comment]
I'm unable to debug locally as I get the 'The type initializer for 'IdentityServer4.EntityFramework.Mappers.ScopeMappers' threw an exception.' error as well.

**Comment by enkodellc** [comment]
Use the Maui Branch  https://github.com/enkodellc/blazorboilerplate/tree/maui

**Comment by wint100** [comment]
I'm having issues running the maui branch. The server project fails to run and the Maui project runs but fails to connect when trying to login. Is there an additional Ste other than updating the appsettings connection string in the server project?

**Comment by wint100** [comment]
Interesting, which should be the  startup up project?

Is there an order to start each for debugging?

**Comment by GioviQ** [comment]
@wint100 if your aim is to test Maui app, you have to start server project first

**Comment by GioviQ** [comment]
It is an issue with your browser, anyway close Visual Studio, run delObjBin.ps1 in the Utils/Script folder. Open Visual Studio, rebuild all and retry.
