### ISSUE TITLE
Track User Logins

### ISSUE THREAD

**Issue by enkodellc** [enkodellc/blazorboilerplate#98]
The admin portion of BB is growing and I think another great feature that my current clients like is to track when users were last logged in. This also has the benefit to see if there are IP Addresses that are trying to brute force / guess logins.

Initially thoughts:
- Create AspNetUsersLogin Table
- After every user login add row
- Create an Admin page to show user login history

Alternative method:
- I suppose a query from the API Audit log could also do if we implement logger at the AccountManager. This would be a simpler process. Then we would only need to replicate the Audit Log screen with a filter for /account/login calls.

**Comment by VR-Architect** [comment]
Thought? Could this be accomplished with the logging service and send to the log table as an event?

**Comment by enkodellc** [comment]
That sounds like a great idea. If you can get BB running and want to take on the task let me know. Also if you haven't gotten on the guitar page you might be able to find other contributors there to help. https://gitter.im/blazorboilerplate/community Also the blazor thread has many helpful people https://gitter.im/aspnet/Blazor

**Comment by GioviQ** [comment]
At the moment you can see user login events in https://blazor-server.quarella.net/admin/dblog
