### ISSUE TITLE
Some Errors I faced.

### ISSUE THREAD

**Issue by IbrahimTimimi** [enkodellc/blazorboilerplate#989]
Thank you for the amazing BlazorBoilerplate project. I have been wanting to try using it for some time, but I was overwhelmed because I am still learning Blazor and was unsure where to begin customizing the project. However, I have improved my skills and am now ready to use your project to increase my productivity. 

I downloaded the source code from the latest release on GitHub at https://github.com/enkodellc/blazorboilerplate/archive/refs/tags/3.4.zip. After opening the project using the latest visual studio (Version 17.4.3), I restored the dependencies and set the server project as the startup project and launched. These are the issues I faced.
____
### 1st Issue - Reconnect Message
I noticed that when I visit some pages, like the login page, a message saying "Attempting to reconnect to the server: 1 of 8" appears. Does this message only appear when I am running the project locally, or will it also appear when I host the project?
![attempting](https://user-images.githubusercontent.com/53964046/210093655-5216fcb2-b8ea-4453-94f7-33a74fd57ab9.PNG)

____
### 2nd Issue - Breeze Error
I received an error page related to Breeze after logging in with the admin credentials. When I refreshed the page, it opened the dashboard page correctly. I did not take a snapshot of the error page, but I can say that the error was visible to the user, which is not ideal. The exception details are as follows:
```
Breeze.Sharp.DataServiceRequestException: Internal Server Error at Breeze.Sharp.DataService.ReadResult(HttpResponseMessage response) at Breeze.Sharp.DataService.GetAsync(String resourcePath, CancellationToken cancellationToken) at Breeze.Sharp.EntityManager.ExecuteQuery(EntityQuery query, CancellationToken cancellationToken) at Breeze.Sharp.EntityManager.ExecuteQuery[T](EntityQuery`1 query, CancellationToken cancellationToken) at BlazorBoilerplate.Shared.Services.ApiClient.GetUserProfile() in C:\Users\Ibrahim\Desktop\blazorboilerplate-3.4\src\Shared\BlazorBoilerplate.Shared\Services\ApiClient.cs:line 19 at BlazorBoilerplate.Shared.Services.AppState.GetUserProfile() in C:\Users\Ibrahim\Desktop\blazorboilerplate-3.4\src\Shared\BlazorBoilerplate.Shared\Services\AppState.cs:line 58 at BlazorBoilerplate.Theme.Material.Admin.Shared.Layouts.AdminLayout.OnInitializedAsync() in C:\Users\Ibrahim\Desktop\blazorboilerplate-3.4\src\Shared\Modules\BlazorBoilerplate.Theme.MudBlazor.Admin\Shared\Layouts\AdminLayout.razor:line 53 at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync() at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```
___
### 3rd Issue  - Visual Studio Error List
The project runs fine, but I noticed some errors in Visual Studio. I am not sure what to do with these errors. Should I ignore them?

(Ignore the spelling mistakes, I used ocr tool to capture the text from image below)
1. CS1061 `UserProfile` does not contain a definition for `LastPageVisited` and no accessible extension method `LastPageVisited` accepting a first argument of type `UserProfile` could be found (are you missing a using directive or an assembly reference?) BlazorBoilerplate.Ul.Base LoginPage.cs 99 Active
2. CS1061 `UserProfile` does not contain a definition for `LastPageVisited` and no accessible extension method `LastPageVisited` accepting a first argument of type `UserProfile` could befound (are you missing 3 using directive or an assembly reference?) BlazorBoilerplate.Ul.Base LoginPage.cs 99 
3. CS0117 `Todo` does not contain a definition for `CreatedByld` BlazorBoilerplate.Storage Databaselnitializer.cs 137
4. CS0246 The type or namespace name `ILocalizationRecord` could not befound (are you missing a using directive or an assembly reference?) BlazorBoilerplate.Client Program.cs 82 

![Some errors](https://user-images.githubusercontent.com/53964046/210092498-ace5175d-169b-42d7-b9e9-f3dd71bfd5f0.PNG)

**Comment by GioviQ** [comment]
The master branch has some issues with .Net 7 .
Try Maui branch instead

**Comment by IbrahimTimimi** [comment]
I did not clone the project. I downloaded the source code from the "Final Release of .net Core 6.0" page at https://github.com/enkodellc/blazorboilerplate/releases/tag/3.4.

**Comment by GioviQ** [comment]
Rebuild Shared project

**Comment by IbrahimTimimi** [comment]
I opened the project using JetBrains Rider and did not see the errors that were shown in Visual Studio. 

Have you encountered the breeze error before? So far I have not seen it again.

Additionally, when I try to access the login page, a message saying "Attempting to reconnect to the server" appears. This is not ideal as it makes it seem like there is an error, even though this is just the behavior of Blazor. Is there a way to prevent this message from being displayed? 

Thank you for your help.

**Comment by GioviQ** [comment]
If you use the last version of Visual Studio all works

**Comment by IbrahimTimimi** [comment]
Thank you.
